# 09 Jul 2003 I1 v2.2 [Koh Han Sing] Add in field GridDocField in UserProcedure.
# 26 Nov 2003 I4 v2.2 [Koh Han Sing] Add in new datatype byte[] and byte[][].
# 01 Dec 2003 I4 v2.2 [Koh Han Sing] Add in username and password in SoapProcedure

USE appdb;
#
# Dumping data for table 'entitymetainfo'
#
DELETE FROM entitymetainfo WHERE EntityName = 'ProcedureDefFile';
DELETE FROM entitymetainfo WHERE EntityName = 'UserProcedure';
DELETE FROM entitymetainfo WHERE EntityName = 'JavaProcedure';
DELETE FROM entitymetainfo WHERE EntityName = 'ShellExecutable';
DELETE FROM entitymetainfo WHERE EntityName = 'SoapProcedure';
DELETE FROM entitymetainfo WHERE EntityName = 'ParamDef';
DELETE FROM entitymetainfo WHERE EntityName = 'ReturnDef';
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','ProcedureDefFile','procedure_definition_file');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.UserProcedure','UserProcedure','user_procedure');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.JavaProcedure','JavaProcedure','');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.ShellExecutable','ShellExecutable','');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.SoapProcedure','SoapProcedure','');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.ParamDef','ParamDef','');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.base.userprocedure.model.ReturnDef','ReturnDef','');

#
# Dumping data for table 'fieldmetainfo'
#

# UserProcedure.
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%UserProcedure';
INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.uid',20,'0','0','0','0','0',999,'displayable=false\r\nmandatory=false\r\neditable=false\r\n','type=uid\r\n');
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.pdip.base.userprocedure.model.UserProcedure","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=range");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.pdip.base.userprocedure.model.UserProcedure","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=enum\r\ncandelete.enabled=true\r\ncandelete.disabled=false");
INSERT INTO fieldmetainfo VALUES (NULL,'_name','NAME','Name','java.lang.String','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.name',15,'0','0','0','1','0',1,'displayable=true\r\neditable.create=true\r\nmandatory=true\r\n','type=text\r\ntext.length.max=30\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_description','DESCRIPTION','Description','java.lang.String','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.description',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=text\r\ntext.length.max=80\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_isSynchronous','IS_SYNCHRONOUS','IsSynchronous','java.lang.Boolean','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.isSynchronous',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nuserProcedure.isSynchronous.yes=true\r\nuserProcedure.isSynchronous.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_procType','PROC_TYPE','ProcType','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procType',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nuserProcedure.procType.executable=1\r\nuserProcedure.procType.java=2\r\nuserProcedure.procType.soap=3\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_procDefFile','PROC_DEF_FILE','ProcDefFile','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procDefFile',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=foreign\r\nforeign.key=procedureDefFile.uid\r\nforeign.display=procedureDefFile.name\r\nforeign.cached=true\r\n"');
INSERT INTO fieldmetainfo VALUES (NULL,'_procDef','PROC_DEF','ProcDef','com.gridnode.pdip.base.userprocedure.model.ProcedureDef','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procDef',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=dynamic\r\ndynamic.types=shellExecutable;javaProcedure;soapProcedure\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_procParamList','PROC_PARAM_LIST','ProcParamList','java.util.Vector','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procParamList',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=embedded\r\nembedded.type=paramDef\r\ncollection=true\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_returnDataType','RETURN_DATA_TYPE','ReturnDataType','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.returnDataType',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nuserProcedure.returnDataType.string=1\r\nuserProcedure.returnDataType.integer=2\r\nuserProcedure.returnDataType.long=3\r\nuserProcedure.returnDataType.double=4\r\nuserProcedure.returnDataType.boolean=5\r\nuserProcedure.returnDataType.date=6\r\nuserProcedure.returnDataType.object=7\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_defAction','DEF_ACTION','DefAction','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.defAction',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nuserProcedure.defAction.continue=1\r\nuserProcedure.defAction.abort=2\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_defAlert','DEF_ALERT','DefAlert','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.defAlert',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=foreign\r\nforeign.key=alert.uid\r\nforeign.display=alert.description\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_procReturnList','PROC_RETURN_LIST','ProcReturnList','java.util.Vector','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procReturnList',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=embedded\r\nembedded.type=returnDef\r\ncollection=true\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gridDocField','GRID_DOC_FIELD','GridDocField','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.gridDocField',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\ngridDocument.custom1=77\r\ngridDocument.custom2=78\r\ngridDocument.custom3=79\r\ngridDocument.custom4=80\r\ngridDocument.custom5=81\r\ngridDocument.custom6=82\r\ngridDocument.custom7=83\r\ngridDocument.custom8=84\r\ngridDocument.custom9=85\r\ngridDocument.custom10=86\r\n');

# ProcedureDefinition File.
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ProcedureDefFile';
INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.uid',20,'0','0','0','0','0',999,'displayable=false\r\neditable=false','type=uid');
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=range");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=enum\r\ncandelete.enabled=true\r\ncandelete.disabled=false");
INSERT INTO fieldmetainfo VALUES (NULL,'_name','NAME','Name','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.name',15,'0','0','0','1','0',1,'displayable=true\r\neditable.create=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=30');
INSERT INTO fieldmetainfo VALUES (NULL,'_description','DESCRIPTION','Description','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.description',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_type','TYPE','Type','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.type',15,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=enum\r\nprocedureDefFile.type.executable=1\r\nprocedureDefFile.type.java=2\r\nprocedureDefFile.type.soap=3\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_fileName','FILE_NAME','FileName','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.fileName',30,'0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=file\r\nfile.downloadable=false\r\nfile.pathKey=procedureDefFile.filePath\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_filePath','FILE_PATH','FilePath','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.filePath',30,'0','0','0','1','0',1,'displayable=false\r\neditable=false\r\nmandatory=false\r\n','type=file\r\n');

# JavaProcedure -- Note SQLName is empty as this are entities are not persistant. To Confirm regd cmdLineExpr (CMDLineExpression).
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%JavaProcedure';
INSERT INTO fieldmetainfo VALUES (NULL,'_classPath','CLASS_PATH','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.classPath','80','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_className','CLASS_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.className','80','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_methodName','METHOD_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.methodName','80','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_jvmOptions','JVM_OPTIONS','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.jvmOptions','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=text\r\ntext.length.max=30');
INSERT INTO fieldmetainfo VALUES (NULL,'_arguments','ARGUMENTS','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.arguments','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=text\r\ntext.length.max=150');
INSERT INTO fieldmetainfo VALUES (NULL,'_isLocal','IS_LOCAL','','java.lang.Boolean','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.isLocal','0','0','0','0','0','','999',"displayable=true\r\neditable=true","type=enum\r\njavaProcedure.isLocal.true=true\r\njavaProcedure.isLocal.false=false");
INSERT INTO fieldmetainfo VALUES (NULL,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.type','0','0','0','0','0','','999',"displayable=false\r\neditable=false","type=enum\r\njavaProcedure.type.executable=1\r\njavaProcedure.type.java=2\r\njavaProcedure.type.soap=3\r\n");

# ShellExecutable -- Note SQLName is empty as this are entities are not persistant
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ShellExecutable';
INSERT INTO fieldmetainfo VALUES (NULL,'_arguments','ARGUMENTS','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ShellExecutable','shellExecutable.arguments','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=text\r\ntext.length.max=150');
INSERT INTO fieldmetainfo VALUES (NULL,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ShellExecutable','shellExecutable.type','0','0','0','0','0','','999',"displayable=false\r\neditable=false","type=enum\r\nshellExecutable.type.executable=1\r\nshellExecutable.type.java=2\r\nshellExecutable.type.soap=3\r\n");

# SoapProcedure -- Note SQLName is empty as this are entities are not persistant. To Confirm regd cmdLineExpr (CMDLineExpression).
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%SoapProcedure';
INSERT INTO fieldmetainfo VALUES (NULL,'_methodName','METHOD_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.methodName','80','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.type','0','0','0','0','0','','999',"displayable=false\r\neditable=false","type=enum\r\nsoapProcedure.type.executable=1\r\nsoapProcedure.type.java=2\r\nsoapProcedure.type.soap=3\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,'_username','USER_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.userName','80','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_password','PASSWORD','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.password','80','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=text\r\ntext.length.max=80');

# ParamDef -- Note SQLName is empty as this are entities are not persistant
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ParamDef';
INSERT INTO fieldmetainfo VALUES (NULL,'_name','NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.name','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=30');
INSERT INTO fieldmetainfo VALUES (NULL,'_description','DESCRIPTION','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.description','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_source','SOURCE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.source','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nparamDef.source.userDefined=1\r\nparamDef.source.gdoc=2\r\nparamDef.source.udoc=3\r\nparamDef.source.attachments=4\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.type','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nparamDef.type.string=1\r\nparamDef.type.integer=2\r\nparamDef.type.long=3\r\nparamDef.type.double=4\r\nparamDef.type.boolean=5\r\nparamDef.type.date=6\r\nparamDef.type.object=7\r\nparamDef.type.datahandler=8\r\nparamDef.type.datahandlerArray=9\r\nparamDef.type.stringArray=10\r\nparamDef.type.byteArray=11\r\nparamDef.type.byteArrayArray=12\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_value','VALUE','','java.lang.Object','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.value','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=255');
INSERT INTO fieldmetainfo VALUES (NULL,'_dateFormat','DATE_FORMAT','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.dateFormat','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n',"type=enum\r\nparamDef.dateFormat.format1=ddMMyyHHmmss\r\nparamDef.dateFormat.format2=ddMMyyyyHHmmss\r\nparamDef.dateFormat.format3=MMddyyHHmmss\r\nparamDef.dateFormat.format4=MMddyyyyHHmmss\r\nparamDef.dateFormat.format5=yyMMddHHmmss\r\nparamDef.dateFormat.format6=yyyyMMddHHmmss\r\nparamDef.dateFormat.format7=yyyyMMdd\r\nparamDef.dateFormat.format8=yyMMdd\r\nparamDef.dateFormat.format9=ddMMyyyy\r\nparamDef.dateFormat.format10=ddMMyy\r\nparamDef.dateFormat.format11=MMddyyyy\r\nparamDef.dateFormat.format12=MMddyy");

# ReturnDef -- Note SQLName is empty as this are entities are not persistant
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ReturnDef';
INSERT INTO fieldmetainfo VALUES (NULL,'_operator','OPERATOR','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.operator','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nreturnDef.operator.equal=0\r\nreturnDef.operator.less=1\r\nreturnDef.operator.lessOrEqual=2\r\nreturnDef.operator.greaterOrEqual=3\r\nreturnDef.operator.greater=4\r\nreturnDef.operator.notEqual=5\r\nreturnDef.operator.between=6\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_value','VALUE','','java.lang.Object','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.value','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=30');
INSERT INTO fieldmetainfo VALUES (NULL,'_action','ACTION','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.actionType','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nreturnDef.actionType.continue=1\r\nreturnDef.actionType.abort=2\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_alert','ALERT','','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.alert','30','0','0','0','1','0',1,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=foreign\r\nforeign.key=alert.uid\r\nforeign.display=alert.description\r\n');
