SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;

--
-- Dumping data for table 'entitymetainfo'
--
-- Field 1 ObjectName: full qualified class name of the entity
-- Field 2 EntityName: short class name of the entity
-- Field 3 SqlName: table name of the entity

--entitymetainfo for document_type
DELETE FROM "entitymetainfo" WHERE "EntityName" IN ('DocumentType','FileType','GridDocument','Attachment','AttachmentRegistry','AS2DocTypeMapping');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.gtas.server.document.model.DocumentType','DocumentType','"document_type"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.gtas.server.document.model.FileType','FileType','"file_type"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.gtas.server.document.model.GridDocument','GridDocument','"grid_document"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.gtas.server.document.model.Attachment','Attachment','"attachment"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.gtas.server.document.model.AttachmentRegistry','AttachmentRegistry','"attachmentRegistry"');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.document.model.AS2DocTypeMapping','AS2DocTypeMapping','as2_doc_type_mapping');



---------- document_type
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%DocumentType';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.document.model.DocumentType','documentType.uid',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_docType','DOC_TYPE','"DocType"','java.lang.String','com.gridnode.gtas.server.document.model.DocumentType','documentType.docType',30,0,1,0,1,'',1,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true','type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_desc','DESCRIPTION','"Description"','java.lang.String','com.gridnode.gtas.server.document.model.DocumentType','documentType.description',80,0,1,1,1,'',2,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.gtas.server.document.model.DocumentType','',0,0,1,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.gtas.server.document.model.DocumentType','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');



---------- file_type
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%FileType';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.document.model.FileType','fileType.uid',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_fileType','FILE_TYPE','"FileType"','java.lang.String','com.gridnode.gtas.server.document.model.FileType','fileType.fileType',10,0,1,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true','type=text'||chr(13)||chr(10)||'text.length.max=10');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_description','DESCRIPTION','"Description"','java.lang.String','com.gridnode.gtas.server.document.model.FileType','fileType.description',80,0,1,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_programName','PROGRAM_NAME','"ProgramName"','java.lang.String','com.gridnode.gtas.server.document.model.FileType','fileType.programName',120,0,1,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=120');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_programPath','PROGRAM_PATH','"ProgramPath"','java.lang.String','com.gridnode.gtas.server.document.model.FileType','fileType.programPath',120,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=120');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_parameters','PARAMETERS','"Parameters"','java.lang.String','com.gridnode.gtas.server.document.model.FileType','fileType.parameters',120,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=120');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_workingDirectory','WORKING_DIR','"WorkingDirectory"','java.lang.String','com.gridnode.gtas.server.document.model.FileType','fileType.workingDirectory',120,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=120');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.gtas.server.document.model.FileType','',0,0,1,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.gtas.server.document.model.FileType','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');


---------- grid_document
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%GridDocument';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.uid',0,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','',0,0,1,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.gtas.server.document.model.GridDocument','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gdocId','G_DOC_ID','"GdocId"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.gdocId',0,0,1,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_refGdocId','REF_G_DOC_ID','"RefGdocId"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.refGdocId',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gdocFilename','G_DOC_FILENAME','"GdocFilename"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.gdocFilename',80,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=file'||chr(13)||chr(10)||'file.downloadable=true'||chr(13)||chr(10)||'file.fixedKey=document.path.gdoc');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocNum','U_DOC_NUM','"UdocNum"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocNum',20,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_refUdocNum','REF_U_DOC_NUM','"RefUdocNum"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.refUdocNum',20,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocFilename','U_DOC_FILENAME','"UdocFilename"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocFilename',80,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=true','type=file'||chr(13)||chr(10)||'file.downloadable=true'||chr(13)||chr(10)||'file.fixedKey=document.path.udoc');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_refUdocFilename','REF_U_DOC_FILENAME','"RefUdocFilename"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.refUdocFilename',80,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocVersion','U_DOC_VERSION','"UdocVersion"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocVersion',10,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range'||chr(13)||chr(10)||'range.min=1');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocDocType','U_DOC_DOC_TYPE','"UdocDocType"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocDocType',30,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=documentType.docType'||chr(13)||chr(10)||'foreign.display=documentType.docType'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocFileSize','U_DOC_FILESIZE','','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocFileSize',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range'||chr(13)||chr(10)||'range.min=0');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocFileType','U_DOC_FILE_TYPE','"UdocFileType"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocFileType',10,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=10');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isExported','IS_EXPORTED','"Exported"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isExported',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isExported.enabled=true'||chr(13)||chr(10)||'gridDocument.isExported.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isViewAckReq','IS_VIEW_ACK_REQ','"ViewAckReq"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isViewAckReq',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isViewAckReq.enabled=true'||chr(13)||chr(10)||'gridDocument.isViewAckReq.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isExportAckReq','IS_EXPORT_ACK_REQ','"ExportAckReq"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isExportAckReq',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isExportAckReq.enabled=true'||chr(13)||chr(10)||'gridDocument.isExportAckReq.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isReceiveAckReq','IS_RECEIVE_ACK_REQ','"ReceiveAckReq"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isReceiveAckReq',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isReceiveAckReq.enabled=true'||chr(13)||chr(10)||'gridDocument.isReceiveAckReq.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isViewed','IS_VIEWED','"Viewed"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isViewed',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isViewed.enabled=true'||chr(13)||chr(10)||'gridDocument.isViewed.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isSent','IS_SENT','"Sent"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isSent',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isSent.enabled=true'||chr(13)||chr(10)||'gridDocument.isSent.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isLocalPending','IS_LOCAL_PENDING','"LocalPending"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isLocalPending',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isLocalPending.enabled=true'||chr(13)||chr(10)||'gridDocument.isLocalPending.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isExpired','IS_EXPIRED','"Expired"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isExpired',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isExpired.enabled=true'||chr(13)||chr(10)||'gridDocument.isExpired.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isRecAckProcessed','IS_REC_ACK_PROCESSED','"RecAckProcessed"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isRecAckProcessed',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isRecAckProcessed.enabled=true'||chr(13)||chr(10)||'gridDocument.isRecAckProcessed.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_encryptionLevel','ENCRYPTION_LEVEL','"EncryptionLevel"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.encryptionLevel',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range'||chr(13)||chr(10)||'range.min=64'||chr(13)||chr(10)||'range.max=1024');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_folder','FOLDER','"Folder"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.folder',10,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=10');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_createBy','CREATE_BY','"CreateBy"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.createBy',50,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=50');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientNodeId','R_NODE_ID','"RecipientNodeId"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientNodeId',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientPartnerId','R_PARTNER_ID','"RecipientPartnerId"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientPartnerId',15,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=partner.partnerId'||chr(13)||chr(10)||'foreign.display=partner.partnerId'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientPartnerType','R_PARTNER_TYPE','"RecipientPartnerType"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientPartnerType',3,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=3');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientPartnerGroup','R_PARTNER_GROUP','"RecipientPartnerGroup"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientPartnerGroup',3,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=3');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientBizEntityId','R_BIZ_ENTITY_ID','"RecipientBizEntityId"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientBizEntityId',4,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=4');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientPartnerFunction','R_PARTNER_FUNCTION','"RecipientPartnerFunction"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientPartnerFunction',30,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientGdocId','R_G_DOC_ID','"RecipientGdocId"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientGdocId',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderNodeId','S_NODE_ID','"SenderNodeId"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderNodeId',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderGdocId','S_G_DOC_ID','"SenderGdocId"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderGdocId',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderPartnerFunction','S_PARTNER_FUNCTION','','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderPartnerFunction',30,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderUserId','S_USER_ID','"SenderUserId"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderUserId',15,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=15');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderUserName','S_USER_NAME','"SenderUserName"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderUserName',50,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=50');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderBizEntityId','S_BIZ_ENTITY_ID','"SenderBizEntityId"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderBizEntityId',4,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=4');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderRoute','S_ROUTE','"SenderRoute"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderRoute',20,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=20');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderPartnerId','S_PARTNER_ID','"SenderPartnerId"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderPartnerId',15,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=partner.partnerId'||chr(13)||chr(10)||'foreign.display=partner.partnerId'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderPartnerType','S_PARTNER_TYPE','"SenderPartnerType"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderPartnerType',3,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=3');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderPartnerGroup','S_PARTNER_GROUP','"SenderPartnerGroup"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderPartnerGroup',3,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=3');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeImport','DT_IMPORT','"DateTimeImport"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeImport',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeSendEnd','DT_SEND_END','"DateTimeSendEnd"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeSendEnd',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeReceiveEnd','DT_RECEIVE_END','"DateTimeReceiveEnd"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeReceiveEnd',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeExport','DT_EXPORT','"DateTimeExport"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeExport',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeCreate','DT_CREATE','"DateTimeCreate"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeCreate',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeTransComplete','DT_TRANSACTION_COMPLETE','"DateTimeTransComplete"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeTransComplete',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeReceiveStart','DT_RECEIVE_START','"DateTimeReceiveStart"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeReceiveStart',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeView','DT_VIEW','"DateTimeView"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeView',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeSendStart','DT_SEND_START','"DateTimeSendStart"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeSendStart',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeRecipientView','DT_RECIPIENT_VIEW','"DateTimeRecipientView"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeRecipientView',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateTimeRecipientExport','DT_RECIPIENT_EXPORT','"DateTimeRecipientExport"','java.util.Date','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.dateTimeRecipientExport',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_partnerFunction','PARTNER_FUNCTION','','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.partnerFunction',30,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_portUid','PORT_UID','"PortUid"','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.portUid',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_actionCode','ACTION_CODE','','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.actionCode',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_srcFolder','SOURCE_FOLDER','"SrcFolder"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.srcFolder',10,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=10');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_notifyUserEmail','NOTIFY_USER_EMAIL','"NotifyUserEmail"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.notifyUserEmail',50,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=50');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientChannelUid','R_CHANNEL_UID','','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientChannelUid',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientChannelName','R_CHANNEL_NAME','','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientChannelName',30,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=channelInfo.name'||chr(13)||chr(10)||'foreign.display=channelInfo.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientChannelProtocol','R_CHANNEL_PROTOCOL','','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientChannelProtocol',10,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=10');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientPartnerName','R_PARTNER_NAME','"RecipientPartnerName"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.recipientPartnerName',20,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=20');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderPartnerName','S_PARTNER_NAME','"SenderPartnerName"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderPartnerName',20,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=20');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_portName','PORT_NAME','"PortName"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.portName',15,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=port.name'||chr(13)||chr(10)||'foreign.display=port.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_rnProfileUid','RN_PROFILE_UID','"RnProfileUid"','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.rnProfileUid',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_processDefId','PROCESS_DEF_ID','"ProcessDefId"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.processDefId',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isRequest','IS_REQUEST','"IsRequest"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isRequest',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isRequest.enabled=true'||chr(13)||chr(10)||'gridDocument.isRequest.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_hasAttachment','HAS_ATTACHMENT','"HasAttachment"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.hasAttachment',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.hasAttachment.enabled=true'||chr(13)||chr(10)||'gridDocument.hasAttachment.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isAttachmentLinkUpdated','IS_ATTACHMENT_LINK_UPDATED','"AttachmentLinkUpdated"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isAttachmentLinkUpdated',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isAttachmentLinkUpdated.enabled=true'||chr(13)||chr(10)||'gridDocument.isAttachmentLinkUpdated.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_attachments','ATTACHMENTS','"Attachments"','java.util.ArrayList','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.attachments',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=attachment.uid'||chr(13)||chr(10)||'foreign.display=attachment.originalFilename'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10)||'collection=true');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_triggerType','TRIGGER_TYPE','"TriggerType"','java.lang.Integer','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.triggerType',0,0,1,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.triggerType.import=0'||chr(13)||chr(10)||'gridDocument.triggerType.receive=1'||chr(13)||chr(10)||'gridDocument.triggerType.manualSend=2'||chr(13)||chr(10)||'gridDocument.triggerType.manualExport=3');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uniqueDocIdentifier','UNIQUE_DOC_IDENTIFIER','"UniqueDocIdentifier"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.uniqueDocIdentifier',80,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_udocFullPath','U_DOC_FULL_PATH','"UdocFullPath"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.udocFullPath',255,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_exportedUdocFullPath','EXPORTED_U_DOC_FULL_PATH','"ExportedUdocFullPath"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.exportedUdocFullPath',255,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isRejected','IS_REJECTED','"Rejected"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isRejected',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isRejected.enabled=true'||chr(13)||chr(10)||'gridDocument.isRejected.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom1','CUSTOM1','"Custom1"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom1',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom2','CUSTOM2','"Custom2"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom2',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom3','CUSTOM3','"Custom3"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom3',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom4','CUSTOM4','"Custom4"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom4',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom5','CUSTOM5','"Custom5"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom5',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom6','CUSTOM6','"Custom6"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom6',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom7','CUSTOM7','"Custom7"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom7',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom8','CUSTOM8','"Custom8"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom8',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom9','CUSTOM9','"Custom9"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom9',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_custom10','CUSTOM10','"Custom10"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.custom10',255,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true','type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_processInstanceUid', 'PROCESS_INSTANCE_UID','"ProcessInstanceUid"','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.processInstanceUid',0,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=processInstance.uid'||chr(13)||chr(10)||'foreign.display=gridDocument.processInstanceId'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_processInstanceID','PROCESS_INSTANCE_ID','"ProcessInstanceID"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.processInstanceId',80,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_userTrackingID','USER_TRACKING_ID','"UserTrackingID"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.userTrackingId',80,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_docTransStatus','DOC_TRANS_STATUS','"DocTransStatus"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.docTransStatus',255,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_messageDigest','MESSAGE_DIGEST','"MessageDigest"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.messageDigest',80,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_auditFileName','AUDIT_FILE_NAME','"AuditFileName"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.auditFileName',200,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false','type=file'||chr(13)||chr(10)||'file.downloadable=true'||chr(13)||chr(10)||'file.fixedKey=common.path.audit');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_receiptAuditFileName','RECEIPT_AUDIT_FILE_NAME','"ReceiptAuditFileName"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.receiptAuditFileName',200,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false','type=file'||chr(13)||chr(10)||'file.downloadable=true'||chr(13)||chr(10)||'file.fixedKey=common.path.audit');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderBizEntityUuid','S_BIZ_ENTITY_UUID','"SenderBizEntityUuid"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.senderBizEntityUuid', 50,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));	
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderRegistryQueryUrl','S_REGISTRY_QUERY_URL','"SenderRegistryQueryUrl"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.senderRegistryQueryUrl', 255,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));	
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientBizEntityUuid','R_BIZ_ENTITY_UUID','"RecipientBizEntityUuid"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.recipientBizEntityUuid', 50,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));	
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_recipientRegistryQueryUrl','R_REGISTRY_QUERY_URL','"RecipientRegistryQueryUrl"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.recipientRegistryQueryUrl', 255,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));	
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_OBPayloadFile','OB_PAYLOAD_FILE','','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument', 'gridDocument.obPayloadFile', 255,0,0,1,1,'', 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));	
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_senderCert','SENDER_CERT','"SenderCert"','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.senderCert',0,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=certificate.uid'||chr(13)||chr(10)||'foreign.display=certificate.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_receiverCert','RECEIVER_CERT','"ReceiverCert"','java.lang.Long','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.receiverCert',0,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=certificate.uid'||chr(13)||chr(10)||'foreign.display=certificate.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_docDateGen','DOC_DATE_GEN','"DocDateGen"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.docDateGen',25,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=25');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_originalDoc','ORIGINAL_DOC','"OriginalDoc"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','',0,0,1,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_tracingID','TRACING_ID','"TracingID"','java.lang.String','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.tracingID',36,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=36');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isRead','IS_READ','"IsRead"','java.lang.Boolean','com.gridnode.gtas.server.document.model.GridDocument','gridDocument.isRead',0,0,0,0,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'gridDocument.isRead.enabled=true'||chr(13)||chr(10)||'gridDocument.isRead.disabled=false');

---------- attachment
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%Attachment';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.document.model.Attachment','attachment.uid',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.gtas.server.document.model.Attachment','',0,0,1,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.gtas.server.document.model.Attachment','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_partnerId','PARTNER_ID','"PartnerId"','java.lang.String','com.gridnode.gtas.server.document.model.Attachment','attachment.partnerId',20,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=20');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_originalUid','ORIGINAL_UID','"OriginalUid"','java.lang.Long','com.gridnode.gtas.server.document.model.Attachment','attachment.originalUid',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_filename','FILENAME','"Filename"','java.lang.String','com.gridnode.gtas.server.document.model.Attachment','attachment.filename',80,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false','type=file'||chr(13)||chr(10)||'file.downloadable=true'||chr(13)||chr(10)||'file.fixedKey=document.path.attachment');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_originalFilename','ORIGINAL_FILENAME','"OriginalFilename"','java.lang.String','com.gridnode.gtas.server.document.model.Attachment','attachment.originalFilename',80,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isOutgoing','IS_OUTGOING','"IsOutgoing"','java.lang.Boolean','com.gridnode.gtas.server.document.model.Attachment','attachment.isOutgoing',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'attachment.isOutgoing.enabled=true'||chr(13)||chr(10)||'attachment.isOutgoing.disabled=false');

---------- attachmentRegistry
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%AttachmentRegistry';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.document.model.AttachmentRegistry','attachmentRegistry.uid',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.gtas.server.document.model.AttachmentRegistry','',0,0,1,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.gtas.server.document.model.AttachmentRegistry','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_partnerId','PARTNER_ID','"PartnerId"','java.lang.String','com.gridnode.gtas.server.document.model.AttachmentRegistry','attachmentRegistry.partnerId',20,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=text'||chr(13)||chr(10)||'text.length.max=20');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_attachmentUid','ATTACHMENT_UID','"AttachmentUid"','java.lang.Long','com.gridnode.gtas.server.document.model.AttachmentRegistry','attachmentRegistry.attachmentUid',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dateProcessed','DATE_PROCESSED','"DateProcessed"','java.util.Date','com.gridnode.gtas.server.document.model.AttachmentRegistry','attachmentRegistry.dateProcessed',0,0,0,0,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime');


-- fieldmetainfo for as2DocTypeMapping
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%AS2DocTypeMapping';

INSERT INTO "fieldmetainfo" VALUES(
DEFAULT,'_uId','UID','"UID"','java.lang.Long',
'com.gridnode.gtas.server.document.model.AS2DocTypeMapping','as2DocTypeMapping.uid',
'0','0','0','0','0','','999',
'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false',
'type=uid'
);

INSERT INTO "fieldmetainfo" VALUES(
DEFAULT,'_as2DocType','AS2_DOC_TYPE','"AS2DocType"','java.lang.String',
'com.gridnode.gtas.server.document.model.AS2DocTypeMapping','as2DocTypeMapping.as2DocType',
'30','0','0','1','1','','1',
'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'editable.create=true',
'type=foreign'||chr(13)||chr(10)||'foreign.key=documentType.docType'||chr(13)||chr(10)||'foreign.display=document_type.docType'||chr(13)||chr(10)||'foreign.cached=false'
);

INSERT INTO "fieldmetainfo" VALUES(
DEFAULT,'_docType','DOC_TYPE','"DocType"','java.lang.String',
'com.gridnode.gtas.server.document.model.AS2DocTypeMapping','as2DocTypeMapping.docType',
'30','0','0','1','1','','1',
'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'editable.create=true',
'type=foreign'||chr(13)||chr(10)||'foreign.key=documentType.docType'||chr(13)||chr(10)||'foreign.display=document_type.docType'||chr(13)||chr(10)||'foreign.cached=false'
);

INSERT INTO "fieldmetainfo" VALUES(
DEFAULT,'_partnerID','PARTNER_ID','"PartnerId"','java.lang.String',
'com.gridnode.gtas.server.document.model.AS2DocTypeMapping','as2DocTypeMapping.partnerId',
'20','0','0','1','1','','999',
'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'editable.create=true',
'type=foreign'||chr(13)||chr(10)||'foreign.key=partner.partnerId'||chr(13)||chr(10)||'foreign.display=partner.name'||chr(13)||chr(10)||'foreign.cached=false'
);

INSERT INTO "fieldmetainfo" VALUES(
DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean',
'com.gridnode.gtas.server.document.model.AS2DocTypeMapping','',
'0','0','1','0','0','','999',
'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false',
'type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false'
);
INSERT INTO "fieldmetainfo" VALUES(
DEFAULT,'_version','VERSION','"Version"','java.lang.Double',
'com.gridnode.gtas.server.document.model.AS2DocTypeMapping','',
'0','0','0','0','0','','999',
'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false',
'type=range'
);
