/**
 * This software is the proprietary information of GridNode Pte Ltd.
 * Use is subjected to license terms.
 *
 * Copyright 2001-2005 (C) GridNode Pte Ltd. All Rights Reserved.
 *
 * File: DocumentInfo.java
 *
 ****************************************************************************
 * Date           Author              Changes
 ****************************************************************************
 * Sep 13, 2005        Tam Wei Xiang       Created
 * Jan 19, 2006        Tam Wei Xiang       Change the instance variable gdocUID to gdocID
 * Apr 26, 2006        Tam Wei Xiang       Added new Field 'processInstanceUID'
 */
package com.gridnode.gtas.server.dbarchive.model;

import com.gridnode.pdip.framework.db.entity.AbstractEntity;

import java.sql.Timestamp;
import java.util.Date;
/**
 * This is a value object for DocumentInfoBean.
 *
 * Tam Wei Xiang
 * 
 * @version
 * @since
 */
public class DocumentMetaInfo 
						 extends AbstractEntity
						 implements IDocumentMetaInfo
{
	private String _docNumber;
	private String _partnerDuns; //to faciliate searching
	private String _partnerID; //""
	private String _partnerName; //""
	private String _docDateGenerated;
	private Date _dateTimeSendStart;
	private Date _dateTimeSendEnd;
	private Date _dateTimeReceiveStart;
	private Date _dateTimeReceiveEnd;
	private Date _dateTimeCreate;
	private Date _dateTimeImport; //may require during archiveByDoc
	private Date _dateTimeExport; //may require during archiveByDoc
	private String _processDef;
	private String _processInstanceID;
	private String _filename;  //it can be audit filename or udoc filename. Depend on archive type
	private String _folder; //the direction
	private String _filePath; //The filepath where we can locate the audit file or udoc file
	private String _originatorID; //it is needed by ProcessInstanceMetaInfo
	private Long _gdocID; //griddocument's gdocID  (gdocID+folder can uniquely identity one gdoc)
	//private String _archiveType; //either archive by processInstance or document
	private Boolean _isArchivedByPI; //01092006 to indicate whether the doc is archived by Process Instance or doc
	
	private String _docType; ////_udocDocType: this field help us to identify the action msg category
  														 //that the grid doc belongs.
  														 //Action msg: eg 3C3  Signal Msg: RN_ACK or RN_Exception
	private String _senderCert; 
	private String _receiverCert; 
	private String _uiFilename; //purely use by UI. no need to exist in DB table since it is dynamic generated by EStore logic
	
	private String _udocFilename; //For those audit file reside in outbound folder, we need to
																//bring over the coresspond udoc file
	
	private String _rnifVersion; 
	
	private String _pathKey = "";    //purely use by UI
	private String _subPathKey = ""; //purely use by UI
	private Long _processInstanceInfoUID; //UID for the process instance meta info 
	private String _gdocFilename;
	private Boolean _isOriginalDoc;
	private String _attachmentFilenames;
	private Boolean _isContainAttachment;
	private String _remark;
	
	private String _receiptAuditFilename; //AS2 may contain such a field
	private String _docTransStatus; //It will specify value if we configure AS2 to request for ACK
	private String _userTrackingID; //this field will contain the failedPI instanceID as indicated within the OA1
	
	/**
	 * Empty constructor is required since the underlying layer dun
	 * know the signature of the constructor.
	 *
	 */
	public DocumentMetaInfo()
	{		
	}
	
	public DocumentMetaInfo(String docType, String docNumber, String partnerDuns, 
			String partnerID, String partnerName, String docDateGenerated, Date dateTimeSendStart, 
			Date dateTimeSendEnd, Date dateTimeReceiveStart, Date dateTimeReceiveEnd, 
			Date dateTimeCreate, Date dateTimeImport, Date dateTimeExport, String processDef, 
			String processInstanceID, String auditFilename, String folder,String filePath,
			String originatorID, Long gdocID, Boolean isArchivedByPI,
			String senderCert, String receiverCert, String uiFilename, String udocFilename,
			String rnifVersion, Long processInstanceUID, String gdocFilename,
			Boolean isOriginalDoc, String attachmentFilenames, Boolean hasAttachment,
			String receiptAuditFilename, String docTransStatus, String userTrackingID)
	{
		// TODO Auto-generated constructor stub
		_docType = docType;
		_docNumber = docNumber;
		_partnerDuns = partnerDuns;
		_partnerID = partnerID;
		_partnerName = partnerName;
		_docDateGenerated = docDateGenerated;
		_dateTimeSendStart = dateTimeSendStart;
		_dateTimeSendEnd = dateTimeSendEnd;
		_dateTimeReceiveStart = dateTimeReceiveStart;
		_dateTimeReceiveEnd = dateTimeReceiveEnd;
		_dateTimeCreate = dateTimeCreate;
		_dateTimeImport = dateTimeImport;
		_dateTimeExport = dateTimeExport;
		_processDef = processDef;
		_processInstanceID = processInstanceID;
		_filename = auditFilename;
		_folder = folder;
		_filePath = filePath;
		_originatorID = originatorID;
		_gdocID = gdocID;
		_isArchivedByPI = isArchivedByPI;
		_senderCert = senderCert;
		_receiverCert = receiverCert;
		_uiFilename = uiFilename;
		_udocFilename = udocFilename;
		_rnifVersion = rnifVersion;
		_processInstanceInfoUID = processInstanceUID;
		_gdocFilename = gdocFilename;
		_isOriginalDoc = isOriginalDoc;
		_attachmentFilenames = attachmentFilenames;
		_isContainAttachment = hasAttachment;
		_receiptAuditFilename = receiptAuditFilename;
		_docTransStatus = docTransStatus;
		_userTrackingID = userTrackingID;
	}
	
  // **************** Methods from AbstractEntity *********************
	public String getEntityName()
  {
    return ENTITY_NAME;
  }

  public String getEntityDescr()
  {
    return new StringBuffer("DocumentMetaInfo ID ").append(this.getProcessInstanceID()).append("/Process Def ").append(this.getProcessDef()).toString();
  }

  public Number getKeyId()
  {
    return UID;
  }
	
  //***************** Getters and Setters for attributes ***********************
	public String getFilename()
	{
		return _filename;
	}
	public void setFilename(String filename)
	{
		this._filename = filename;
	}
	public Date getDateTimeCreate()
	{
		return _dateTimeCreate;
	}
	public void setDateTimeCreate(Date dateTimeCreate)
	{
		this._dateTimeCreate = dateTimeCreate;
	}
	public Date getDateTimeExport()
	{
		return _dateTimeExport;
	}
	public void setDateTimeExport(Date dateTimeExport)
	{
		this._dateTimeExport = dateTimeExport;
	}
	public Date getDateTimeImport()
	{
		return _dateTimeImport;
	}
	public void setDateTimeImport(Date dateTimeImport)
	{
		this._dateTimeImport = dateTimeImport;
	}
	public Date getDateTimeReceiveEnd()
	{
		return _dateTimeReceiveEnd;
	}
	public void setDateTimeReceiveEnd(Date dateTimeReceiveEnd)
	{
		this._dateTimeReceiveEnd = dateTimeReceiveEnd;
	}
	public Date getDateTimeReceiveStart()
	{
		return _dateTimeReceiveStart;
	}
	public void setDateTimeReceiveStart(Date dateTimeReceiveStart)
	{
		this._dateTimeReceiveStart = dateTimeReceiveStart;
	}
	public Date getDateTimeSendEnd()
	{
		return _dateTimeSendEnd;
	}
	public void setDateTimeSendEnd(Date dateTimeSendEnd)
	{
		this._dateTimeSendEnd = dateTimeSendEnd;
	}
	public Date getDateTimeSendStart()
	{
		return _dateTimeSendStart;
	}
	public void setDateTimeSendStart(Date dateTimeSendStart)
	{
		this._dateTimeSendStart = dateTimeSendStart;
	}
	public String getDocDateGenerated()
	{
		return _docDateGenerated;
	}
	public void setDocDateGenerated(String docDateGenerated)
	{
		this._docDateGenerated = docDateGenerated;
	}
	public String getDocNumber()
	{
		return _docNumber;
	}
	public void setDocNumber(String docNumber)
	{
		this._docNumber = docNumber;
	}
	public String getDocType()
	{
		return _docType;
	}
	public void setDocType(String docType)
	{
		this._docType = docType;
	}
	public String getFilePath()
	{
		return _filePath;
	}
	public void setFilePath(String filePath)
	{
		this._filePath = filePath;
	}
	public String getFolder()
	{
		return _folder;
	}
	public void setFolder(String folder)
	{
		this._folder = folder;
	}
	public String getPartnerDuns()
	{
		return _partnerDuns;
	}
	public void setPartnerDuns(String partnerDuns)
	{
		this._partnerDuns = partnerDuns;
	}
	public String getPartnerID()
	{
		return _partnerID;
	}
	public void setPartnerID(String partnerID)
	{
		this._partnerID = partnerID;
	}
	public String getPartnerName()
	{
		return _partnerName;
	}
	public void setPartnerName(String partnerName)
	{
		this._partnerName = partnerName;
	}
	public String getProcessDef()
	{
		return _processDef;
	}
	public void setProcessDef(String processDef)
	{
		this._processDef = processDef;
	}
	public String getProcessInstanceID()
	{
		return _processInstanceID;
	}
	public void setProcessInstanceID(String processInstanceID)
	{
		this._processInstanceID = processInstanceID;
	}

	public Long getGdocID()
	{
		return _gdocID;
	}

	public void setGdocID(Long gdocid)
	{
		_gdocID = gdocid;
	}

	public String getOriginatorID()
	{
		return _originatorID;
	}

	public void setOriginatorID(String duns)
	{
		_originatorID = duns;
	}

	public Boolean isArchivedByPI()
	{
		return _isArchivedByPI;
	}

	public void setIsArchivedByPI(boolean isArchivedByPI)
	{
		_isArchivedByPI = isArchivedByPI;
	}

	public String getSenderCert()
	{
		return _senderCert;
	}

	public void setSenderCert(String cert)
	{
		_senderCert = cert;
	}

	public String getReceiverCert()
	{
		return _receiverCert;
	}

	public void setReceiverCert(String cert)
	{
		_receiverCert = cert;
	}

	public String getUIFilename()
	{
		return _uiFilename;
	}

	public void setUIFilename(String filename)
	{
		_uiFilename = filename;
	}
	
	public String getUDocFilename()
	{
		return _udocFilename;
	}
	
	public void setUDocFilename(String filename)
	{
		_udocFilename = filename;
	}

	public String getRnifVersion()
	{
		return _rnifVersion;
	}

	public void setRnifVersion(String version)
	{
		_rnifVersion = version;
	}

	public String getPathKey()
	{
		return _pathKey;
	}

	public void setPathKey(String key)
	{
		_pathKey = key;
	}

	public String getSubPathKey()
	{
		return _subPathKey;
	}

	public void setSubPathKey(String pathKey)
	{
		_subPathKey = pathKey;
	}

	public Long getProcessInstanceInfoUID()
	{
		return _processInstanceInfoUID;
	}

	public void setProcessInstanceInfoUID(Long instanceInfoUID)
	{
		_processInstanceInfoUID = instanceInfoUID;
	}

	public String getGdocFilename()
	{
		return _gdocFilename;
	}

	public void setGdocFilename(String gdocFilename)
	{
		this._gdocFilename = gdocFilename;
	}

	public String getAttachmentFilenames()
	{
		return _attachmentFilenames;
	}

	public void setAttachmentFilenames(String hasAttachment)
	{
		this._attachmentFilenames = hasAttachment;
	}

	public Boolean isOriginalDoc()
	{
		return _isOriginalDoc;
	}

	public void setIsOriginalDoc(Boolean isOriginalDoc)
	{
		this._isOriginalDoc = isOriginalDoc;
	}

	public Boolean isContainAttachment()
	{
		return _isContainAttachment;
	}

	public void setContainAttachment(Boolean attachment)
	{
		_isContainAttachment = attachment;
	}

	public String getRemark()
	{
		return _remark;
	}

	public void setRemark(String _remark)
	{
		this._remark = _remark;
	}

	public String getDocTransStatus()
	{
		return _docTransStatus;
	}

	public void setDocTransStatus(String transStatus)
	{
		_docTransStatus = transStatus;
	}

	public String getReceiptAuditFilename()
	{
		return _receiptAuditFilename;
	}

	public void setReceiptAuditFilename(String auditFilename)
	{
		_receiptAuditFilename = auditFilename;
	}

	public String getUserTrackingID()
	{
		return _userTrackingID;
	}

	public void setUserTrackingID(String trackingID)
	{
		_userTrackingID = trackingID;
	}
	
	
}
