/* Generated by Together */

package com.gridnode.pdip.base.appinterface.data;

public class AppParam implements java.io.Serializable {
  /**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = 3673763774545654330L;
		public int getAppType(){
            return _appType;
        }

    public void setAppType(int appType){
            this._appType = appType;
        }

    public Object getAppDoc(){
            return _appDoc;
        }

    public void setAppDoc(Object appDoc){
            this._appDoc = appDoc;
        }

    private int _appType;
    private Object _appDoc;
}
