USE appdb;
# version:2.0
# build:2.0.16
# iteration:8
# date:27/02/03
# Updated the sql script to delete the structure before inserting the records,
# for Channel and associated Profiles.

#Definition for Channel - and Associated Profiles. (EntityMetaInfo).
#@Date:21/OCT/2003 @Author Jagadeesh @Comments: To include SOAP TPT Protocol type in ChannelInfo and CommInfo.
# 04 Dec 2003 GT 2.2 [Neo Sok Lay] Display certificate.id in addition to certificate.name in SecurityInfo to avoid confusion
#@Date:18/DEC/2003 @Author Jagadeesh @Comments: To include FlowControl Profile at entitymetainfo and fieldmetainfo.
#@Date:13/JAN/2004 @Author Daniel @Comments: To add back some AS2 Extentions info that got "lost" after merge
#@Date:07/MAY/2004 @Author Neo Sok Lay @Comments: To add back the AS2 packaging envelope type.
# 31 May 2004 GT 2.3 [Daniel] Changed FlowControl's isZip & isSplit to mandatory


DELETE FROM entitymetainfo WHERE EntityName = 'ChannelInfo';
DELETE FROM entitymetainfo WHERE EntityName = 'CommInfo';
DELETE FROM entitymetainfo WHERE EntityName = 'SecurityInfo';
DELETE FROM entitymetainfo WHERE EntityName = 'PackagingInfo';
DELETE FROM entitymetainfo WHERE EntityName = 'AS2PackagingInfoExtension';
DELETE FROM entitymetainfo WHERE EntityName = 'FlowControlInfo';

INSERT INTO entitymetainfo VALUES ("com.gridnode.pdip.app.channel.model.ChannelInfo","ChannelInfo","channel_info");
INSERT INTO entitymetainfo VALUES ("com.gridnode.pdip.app.channel.model.CommInfo","CommInfo","comm_info");
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.app.channel.model.SecurityInfo','SecurityInfo','security_profile');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.app.channel.model.PackagingInfo','PackagingInfo','packaging_profile');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.app.channel.model.AS2PackagingInfoExtension','AS2PackagingInfoExtension','');
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.app.channel.model.FlowControlInfo','FlowControlInfo','');

#
#Meta-Information required for Channel.(FieldMetaInfo)
# Fieldmetainfo for Channel

DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%.ChannelInfo';
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.version","0","0","0","0","0","0","999","displayable=false","");
INSERT INTO fieldmetainfo VALUES(NULL,"_refId","REF_ID","RefId","java.lang.String","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.refId","30","0","0","1","1","0","999","displayable=true\r\neditable=false\r\ndisplayable.create=false","type=text\r\ntext.length.max=30");
INSERT INTO fieldmetainfo VALUES(NULL,"_tptProtocolType","TPT_PROTOCOL_TYPE","TptProtocolType","java.lang.String","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.tptProtocolType","10","0","1","1","1","0","999","displayable=true\r\nmandatory=true","type=enum\r\nchannelInfo.tptProtocolType.jms=JMS\r\nchannelInfo.tptProtocolType.http=HTTP\r\nchannelInfo.tptProtocolType.soap=SOAP-HTTP");
INSERT INTO fieldmetainfo VALUES(NULL,"_description","DESCRIPTION","Description","java.lang.String","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.description","80","0","0","1","1","0","999","displayable=true\r\nmandatory=true","type=text\r\ntext.length.max=80");
INSERT INTO fieldmetainfo VALUES(NULL,"_tptCommInfo","TPT_COMM_INFO","TptCommInfo","com.gridnode.pdip.app.channel.model.CommInfo","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.tptCommInfoUid","0","0","1","1","0","0","999","displayable=true\r\neditable=true\r\nmandatory=true","type=foreign\r\nforeign.key=commInfo.uid\r\nforeign.display=commInfo.name\r\nforeign.cached=true");
INSERT INTO fieldmetainfo VALUES(NULL,"_packagingInfo","PACKAGING_PROFILE","PackagingProfile","com.gridnode.pdip.app.channel.model.PackagingInfo","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.packagingProfile","0","0","1","1","0","0","999","displayable=true\r\neditable=true\r\nmandatory=true","type=foreign\r\nforeign.key=packagingInfo.uid\r\nforeign.display=packagingInfo.name\r\nforeign.cached=true");
INSERT INTO fieldmetainfo VALUES(NULL,"_securityInfo","SECURITY_PROFILE","SecurityProfile","com.gridnode.pdip.app.channel.model.SecurityInfo","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.securityProfile","0","0","1","1","0","0","999","displayable=true\r\neditable=true\r\nmandatory=true","type=foreign\r\nforeign.key=securityInfo.uid\r\nforeign.display=securityInfo.name\r\nforeign.cached=true");
INSERT INTO fieldmetainfo VALUES (NULL,'_flowControlInfo','FLOWCONTROL_PROFILE','FlowControlProfile','com.gridnode.pdip.app.channel.model.FlowControlInfo','com.gridnode.pdip.app.channel.model.ChannelInfo','channelInfo.flowControlProfile',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=embedded\r\nembedded.type=flowControlInfo');

INSERT INTO fieldmetainfo VALUES(NULL,"_uId","UID","UID","java.lang.Long","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.uid","0","0","0","0","0","0","999","displayable=false\r\neditable=false","type=uid");
INSERT INTO fieldmetainfo VALUES(NULL,"_name","NAME","Name","java.lang.String","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.name","30","0","1","1","1","","999","displayable=true\r\neditable.create=true\r\neditable.update=false\r\nmandatory=true","type=text\r\ntext.length.max=30");
INSERT INTO fieldmetainfo VALUES (NULL,"_isMaster","IS_MASTER","isMaster","java.lang.Boolean","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.isMaster","0","0","0","0","0","0","999","displayable=false\r\nmandatory=false\r\neditable=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isPartner","IS_PARTNER","isPartner","java.lang.Boolean","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.isPartner","0","0","0","0","0","0","999","displayable=true\r\nmandatory=true\r\neditable=false\r\neditable.create=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.canDelete","0","0","0","1","1","","999","displayable=true\r\neditable=false\r\nmandatory=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isDisable","IS_DISABLE","isDisable","java.lang.Boolean","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.isDisable","0","0","0","0","0","0","999","displayable=false\r\nmandatory=false\r\neditable=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerCategory","PARTNER_CAT","PartnerCategory","java.lang.Short","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.partnerCategory","80","0","0","1","1","0","999","displayable=true\r\neditable=false\r\nmandatory=false\r\ndisplayable.create=false\r\n","type=enum\r\n##application specific\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_isRelay","IS_RELAY","isRelay","java.lang.Boolean","com.gridnode.pdip.app.channel.model.ChannelInfo","channelInfo.isRelay","0","0","0","1","1","0","999","displayable=false\r\neditable=false\r\nmandatory=false\r\ndisplayable.create=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");

#Meta-Information required for CommInfo.Or Communication Profile.(FieldMetaInfo)

DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%.CommInfo';
INSERT INTO fieldmetainfo VALUES (NULL,"_uId","UID","UID","java.lang.Long","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.uid","0","0","0","0","0","0","999","displayable=false\r\neditable=false","type=uid");
#INSERT INTO fieldmetainfo VALUES (NULL,"_host","HOST","Host","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.host","30","0","1","1","1","0","999","displayable=true\r\nmandatory=true","type=text\r\ntext.length.max=30");
#INSERT INTO fieldmetainfo VALUES (NULL,"_port","PORT","Port","java.lang.Integer","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.port","0","0","1","1","1","0","999","displayable=true\r\nmandatory=true","type=range\r\nrange.min=0\r\nrange.max=65535");
#INSERT INTO fieldmetainfo VALUES (NULL,"_protocolVersion","PROTOCOL_VERSION","ProtocolVersion","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.protocolVersion","10","0","0","0","1","0","999","displayable=false\r\neditable=false","type=text\r\ntext.length.max=10");
INSERT INTO fieldmetainfo VALUES (NULL,"_tptImplVersion","TPT_IMPL_VERSION","TptImplVersion","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.tptImplVersion","6","0","0","1","0","0","999","displayable=false","type=text\r\ntext.length.max=6");
#INSERT INTO fieldmetainfo VALUES (NULL,"_protocolDetail","PROTOCOL_DETAIL","ProtocolDetail","java.util.Hashtable","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.protocolDetail","0","0","0","1","0","0","999","displayable=false\r\neditable=true","");
INSERT INTO fieldmetainfo VALUES (NULL,"_refId","REF_ID","RefId","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.refId","30","0","0","1","1","0","999","displayable=true\r\neditable=false\r\ndisplayable.create=false","type=text\r\ntext.length.max=30");
INSERT INTO fieldmetainfo VALUES (NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.version","0","0","0","0","1","0","999","displayable=false","type=text");
INSERT INTO fieldmetainfo VALUES (NULL,"_protocolType","PROTOCOL_TYPE","ProtocolType","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.protocolType","10","0","1","1","1","0","999","editable=true\r\ndisplayable=true\r\nmandatory=true","type=enum\r\ncommInfo.protocolType.jms=JMS\r\ncommInfo.protocolType.http=HTTP\r\ncommInfo.protocolType.soap=SOAP-HTTP");
INSERT INTO fieldmetainfo VALUES (NULL,"_name","NAME","Name","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.name","30","0","1","1","1","","999","displayable=true\r\neditable.create=true\r\neditable.update=false\r\nmandatory=true","type=text\r\ntext.length.max=30");
INSERT INTO fieldmetainfo VALUES (NULL,"_description","DESCRIPTION","Description","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.description","80","0","0","1","1","","999","displayable=true","type=text\r\ntext.length.max=80");
INSERT INTO fieldmetainfo VALUES (NULL,"_isDefaultTpt","IS_DEFAULT_TPT","IsDefaultTpt","java.lang.Boolean","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.defaultTpt","0","0","0","0","0","","999","displayable=false\r\neditable=false","type=enum\r\ncommInfo.defaultTpt.true=true\r\ncommInfo.defaultTpt.false=false");
INSERT INTO fieldmetainfo VALUES (NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.canDelete","0","0","0","1","1","","999","displayable=true\r\neditable=false\r\nmandatory=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_partnerCategory","PARTNER_CAT","PartnerCategory","java.lang.Short","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.partnerCategory","80","0","0","1","1","0","999","displayable=true\r\neditable=false\r\nmandatory=false\r\ndisplayable.create=false\r\n","type=enum\r\n##application specific\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isDisable","IS_DISABLE","isDisable","java.lang.Boolean","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.isDisable","0","0","0","0","0","0","999","displayable=false\r\nmandatory=false\r\neditable=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isPartner","IS_PARTNER","isPartner","java.lang.Boolean","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.isPartner","0","0","0","0","0","0","999","displayable=true\r\nmandatory=true\r\neditable=false\r\neditable.create=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_url","URL","Url","java.lang.String","com.gridnode.pdip.app.channel.model.CommInfo","commInfo.url","0","0","0","0","0","0","999","displayable=true\r\nmandatory=true\r\neditable=true\r\n","type=text\r\ntext.length.max=255");

#Meta-Information required for Packaging Profile.(FieldMetaInfo)

DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%.PackagingInfo';
INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.uid',0,'0','0','0','0','0',999,'displayable=false','type=uid');
INSERT INTO fieldmetainfo VALUES (NULL,'_name','NAME','Name','java.lang.String','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.name',30,'0','1','1','1','',999,'displayable=true\r\neditable=false\r\nmandatory=true\r\neditable.create=true\r\n','type=text\r\ntext.length.max=30');
INSERT INTO fieldmetainfo VALUES (NULL,'_description','DESCRIPTION','Description','java.lang.String','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.description',80,'0','0','1','1','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
#INSERT INTO fieldmetainfo VALUES (NULL,'_zipThreshold','ZIPTHRESHOLD','ZipThreshold','java.lang.Integer','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.zipThreshold',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=range');
#INSERT INTO fieldmetainfo VALUES (NULL,'_zip','ZIP','Zip','java.lang.Boolean','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.zip',0,'0','0','0','0','',999,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_envelope','ENVELOPE','Envelope','java.lang.String','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.envelope',10,'0','0','1','1','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\npackagingInfo.envelope.none=NONE\r\npackagingInfo.envelope.rnif1=RNIF1\r\npackagingInfo.envelope.rnif2=RNIF2\r\npackagingInfo.envelope.as2=AS2\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.pdip.app.channel.model.PackagingInfo","packagingInfo.canDelete","0","0","0","1","1","","999","displayable=true\r\neditable=false\r\nmandatory=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.pdip.app.channel.model.PackagingInfo","packagingInfo.version","0","0","0","1","1","","999","displayable=false\r\neditable=false\r\nmandatory=false\r\n","type=range\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_refId","REF_ID","RefId","java.lang.String","com.gridnode.pdip.app.channel.model.PackagingInfo","packagingInfo.refId","30","0","0","1","1","0","999","displayable=true\r\neditable=false\r\ndisplayable.create=false\r\n","type=text\r\ntext.length.max=30");
INSERT INTO fieldmetainfo VALUES (NULL,"_partnerCategory","PARTNER_CAT","PartnerCategory","java.lang.Short","com.gridnode.pdip.app.channel.model.PackagingInfo","packagingInfo.partnerCategory","80","0","0","1","1","0","999","displayable=true\r\neditable=false\r\nmandatory=false\r\ndisplayable.create=false\r\n","type=enum\r\n##application specific\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isDisable","IS_DISABLE","isDisable","java.lang.Boolean","com.gridnode.pdip.app.channel.model.PackagingInfo","packagingInfo.isDisable","0","0","0","0","0","0","999","displayable=false\r\nmandatory=false\r\neditable=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isPartner","IS_PARTNER","isPartner","java.lang.Boolean","com.gridnode.pdip.app.channel.model.PackagingInfo","packagingInfo.isPartner","0","0","0","0","0","0","999","displayable=true\r\nmandatory=true\r\neditable=false\r\neditable.create=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
#INSERT INTO fieldmetainfo VALUES (NULL,'_split','SPLIT','Split','java.lang.Boolean','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.zip',0,'0','0','0','0','',999,'displayable=true\r\neditable=true\r\nmandatory=false\r\n\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
#INSERT INTO fieldmetainfo VALUES (NULL,'_splitSize','SPLIT_SIZE','SplitSize','java.lang.Integer','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.zipThreshold',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=range');
#INSERT INTO fieldmetainfo VALUES (NULL,'_splitThreshold','SPLIT_THRESHOLD','SplitThreshold','java.lang.Integer','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.zipThreshold',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=range');
INSERT INTO fieldmetainfo VALUES (NULL,'_pkgInfoExtension','PKG_INFO_EXTENSION','PackagingInfoExtension','com.gridnode.pdip.app.channel.model.PackagingInfoExtension','com.gridnode.pdip.app.channel.model.PackagingInfo','packagingInfo.packagingInfoExtension',0,'0','0','0','0','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=dynamic\r\ndynamic.types=as2PackagingInfoExtension\r\n');

# AS2PackagingInfoExtension.
DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%AS2PackagingInfoExtension';
INSERT INTO fieldmetainfo VALUES (NULL,'_isAckReq','IS_ACK_REQ','','java.lang.Boolean','com.gridnode.pdip.app.channel.model.AS2PackagingInfoExtension','as2PackagingInfoExtension.isAckReq','0','0','0','0','0','0',999,'displayable=true\r\nmandatory=false\r\neditable=true\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_isAckSigned','IS_ACK_SIGNED','','java.lang.Boolean','com.gridnode.pdip.app.channel.model.AS2PackagingInfoExtension','as2PackagingInfoExtension.isAckSigned','0','0','0','0','0','0',999,'displayable=true\r\nmandatory=false\r\neditable=true\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_isNRRReq','IS_NRR_REQ','','java.lang.Boolean','com.gridnode.pdip.app.channel.model.AS2PackagingInfoExtension','as2PackagingInfoExtension.isNrrReq','0','0','0','0','0','0',999,'displayable=true\r\nmandatory=false\r\neditable=true\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_isAckSyn','IS_ACK_SYN','','java.lang.Boolean','com.gridnode.pdip.app.channel.model.AS2PackagingInfoExtension','as2PackagingInfoExtension.isAckSyn','0','0','0','0','0','0',999,'displayable=true\r\nmandatory=false\r\neditable=true\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_returnURL','RETURN_URL','','java.lang.String','com.gridnode.pdip.app.channel.model.AS2PackagingInfoExtension','as2PackagingInfoExtension.returnUrl','200','0','1','1','1','',999,'displayable=true\r\nmandatory=false\r\neditable=true\r\n','type=text\r\ntext.length.max=200');

# Fieldmetainfo for Security Profile

DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%.SecurityInfo';
INSERT INTO fieldmetainfo VALUES (NULL,'_description','DESCRIPTION','Description','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.description',80,'0','0','1','1','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=text\r\ntext.length.max=80');
INSERT INTO fieldmetainfo VALUES (NULL,'_name','NAME','Name','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.name',30,'0','1','1','1','',999,'displayable=true\r\neditable=false\r\nmandatory=true\r\neditable.create=true\r\n','type=text\r\ntext.length.max=30');
INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.uid',0,'0','0','0','0','0',999,'displayable=false','type=uid');
INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionLevel','ENCRYPTION_LEVEL','EncryptionLevel','java.lang.Integer','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.encLevel',0,'0','0','0','0','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.encLevel.40=40\r\nsecurityInfo.encLevel.64=64\r\nsecurityInfo.encLevel.128=128\r\nsecurityInfo.encLevel.168=168\r\nsecurityInfo.encLevel.256=256\r\nsecurityInfo.encLevel.512=512\r\nsecurityInfo.encLevel.1024=1024');
INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionType','ENCRYPTION_TYPE','EncryptionType','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.encType',10,'0','0','1','1','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.encType.none=None\r\nsecurityInfo.encType.asymmetric=Asymmetric\r\nsecurityInfo.encType.smime=S/MIME');
INSERT INTO fieldmetainfo VALUES (NULL,'_signatureEncryptionCertificateId','SIGNATURE_ENCRYPTION_CERTIFICATE_ID','SignatureEncryptionCertificate','java.lang.Long','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.sigEncCert',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=foreign\r\nforeign.key=certificate.uid\r\nforeign.display=certificate.name\r\nforeign.cached=false\r\nforeign.additionalDisplay=id');
INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionCertificateId','ENCRYPTION_CERTIFICATE_ID','EncryptionCertificate','java.lang.Long','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.encCert',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=foreign\r\nforeign.key=certificate.uid\r\nforeign.display=certificate.name\r\nforeign.cached=false\r\nforeign.additionalDisplay=id');
INSERT INTO fieldmetainfo VALUES (NULL,'_signatureType','SIGNATURE_TYPE','SignatureType','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.sigType',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.sigType.none=None\r\nsecurityInfo.sigType.smime=S/MIME');
INSERT INTO fieldmetainfo VALUES (NULL,'_digestAlgorithm','DIGEST_ALGORITHM','DigestAlgorithm','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.digestAlgorithm',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.digestAlgorithm.md5=MD5\r\nsecurityInfo.digestAlgorithm.sha1=SHA1');
INSERT INTO fieldmetainfo VALUES (NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.pdip.app.channel.model.SecurityInfo","securityInfo.canDelete","0","0","0","1","1","","999","displayable=true\r\neditable=false\r\nmandatory=false\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.pdip.app.channel.model.SecurityInfo","securityInfo.version","0","0","0","1","1","","999","displayable=false\r\neditable=false\r\nmandatory=false\r\n","type=range\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_refId","REF_ID","RefId","java.lang.String","com.gridnode.pdip.app.channel.model.SecurityInfo","securityInfo.refId","30","0","0","1","1","0","999","displayable=true\r\neditable=false\r\ndisplayable.create=false\r\n","type=text\r\ntext.length.max=30");
INSERT INTO fieldmetainfo VALUES (NULL,"_partnerCategory","PARTNER_CAT","PartnerCategory","java.lang.Short","com.gridnode.pdip.app.channel.model.SecurityInfo","securityInfo.partnerCategory","80","0","0","1","1","0","999","displayable=true\r\neditable=false\r\nmandatory=false\r\ndisplayable.create=false\r\n","type=enum\r\n##application specific\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isDisable","IS_DISABLE","isDisable","java.lang.Boolean","com.gridnode.pdip.app.channel.model.SecurityInfo","securityInfo.isDisable","0","0","0","0","0","0","999","displayable=false\r\nmandatory=false\r\neditable=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,"_isPartner","IS_PARTNER","isPartner","java.lang.Boolean","com.gridnode.pdip.app.channel.model.SecurityInfo","securityInfo.isPartner","0","0","0","0","0","0","999","displayable=true\r\nmandatory=true\r\neditable=false\r\neditable.create=true\r\n","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES (NULL,'_compressionType','COMPRESSION_TYPE','CompressionType','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.compressionType',10,'0','0','1','1','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.compressionType.none=None\r\nsecurityInfo.compressionType.smime=S/MIME');
INSERT INTO fieldmetainfo VALUES (NULL,'_compressionMethod','COMPRESSION_METHOD','CompressionMethod','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.compressionMethod',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.compressionMethod.zlib=ZLIB');
INSERT INTO fieldmetainfo VALUES (NULL,'_compressionLevel','COMPRESSION_LEVEL','CompressionLevel','java.lang.Integer','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.compressionLevel',0,'0','0','0','0','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.compressionLevel.0=0\r\nsecurityInfo.compressionLevel.1=1\r\nsecurityInfo.compressionLevel.2=2\r\nsecurityInfo.compressionLevel.3=3');
INSERT INTO fieldmetainfo VALUES (NULL,'_sequence','SEQUENCE','Sequence','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo','securityInfo.sequence',10,'0','0','1','1','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\nsecurityInfo.sequence.sign_compress=S;C\r\nsecurityInfo.sequence.compress_sign=C;S\r\nsecurityInfo.sequence.sign_encrypt=S;E\r\nsecurityInfo.sequence.encrypt_sign=E;S\r\nsecurityInfo.sequence.compress_encrypt=C;E\r\nsecurityInfo.sequence.sign_compress_encrypt=S;C;E\r\nsecurityInfo.sequence.compress_sign_encrypt=C;S;E\r\nsecurityInfo.sequence.compress_encrypt_sign=C;E;S');
INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionAlgorithm','ENCRYPTION_ALGORITHM','EncryptionAlgorithm','java.lang.String','com.gridnode.pdip.app.channel.model.SecurityInfo', 'securityInfo.encryptionAlgorithm', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=enum\r\nsecurityInfo.encryptionAlgorithm.TDES_ALG=3DES_EDE/CBC/PKCS5Padding\r\nsecurityInfo.encryptionAlgorithm.RC2_ALG=RC2/CBC/PKCS5Padding');

# Fieldmetainfo for FlowControl Profile

INSERT INTO fieldmetainfo VALUES (NULL,'_isZip','IS_ZIP','','java.lang.Boolean','com.gridnode.pdip.app.channel.model.FlowControlInfo','flowControlInfo.isZip',0,'0','0','0','0','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_zipThreshold','ZIP_THRESHOLD','','java.lang.Integer','com.gridnode.pdip.app.channel.model.FlowControlInfo','flowControlInfo.zipThreshold',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=range');
INSERT INTO fieldmetainfo VALUES (NULL,'_isSplit','IS_SPLIT','','java.lang.Boolean','com.gridnode.pdip.app.channel.model.FlowControlInfo','flowControlInfo.isSplit',0,'0','0','0','0','',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_splitThreshold','SPLIT_THRESHOLD','','java.lang.Integer','com.gridnode.pdip.app.channel.model.FlowControlInfo','flowControlInfo.splitThreshold',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=range');
INSERT INTO fieldmetainfo VALUES (NULL,'_splitSize','SPLIT_SIZE','','java.lang.Integer','com.gridnode.pdip.app.channel.model.FlowControlInfo','flowControlInfo.splitSize',0,'0','1','1','1','0',999,'displayable=true\r\neditable=true\r\nmandatory=true\r\n\r\n','type=range');
