-- -----------------------------------------------------------------
-- This script Creates default data for some of the tables in APPDB
-- -----------------------------------------------------------------
SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;

DELETE FROM "entitymetainfo" WHERE "EntityName" IN ('BusinessEntity','WhitePage','RegistryObjectMapping','SearchRegistryCriteria','SearchRegistryQuery','RegistryConnectInfo','DomainIdentifier');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.model.BusinessEntity','BusinessEntity','"business_entity"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.model.WhitePage','WhitePage','"whitepage"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','RegistryObjectMapping','"registry_object_map"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria', 'SearchRegistryCriteria', '');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'SearchRegistryQuery', '');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','RegistryConnectInfo','"registry_connect_info"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.bizreg.model.DomainIdentifier','DomainIdentifier','"domain_identifier"');

--------- BusinessEntity
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.BusinessEntity';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.uid',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_enterpriseId','ENTERPRISE_ID','"EnterpriseID"','java.lang.String','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.enterpriseId',0,0,0,1,1,'',1,'displayable=true'||chr(13)||chr(10)||'displayable.create=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=20'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_busEntId','ID','"ID"','java.lang.String','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.id',0,0,0,1,1,'',2,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=4'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_desc','DESCRIPTION','"Description"','java.lang.String','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.description',0,0,0,1,1,'',3,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isPartner','IS_PARTNER','"IsPartner"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.forPartner',0,0,0,1,1,'',4,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_partnerCat','PARTNER_CATEGORY','"PartnerCat"','java.lang.Short','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.partnerCategory',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'##application specific'||chr(13)||chr(10)||'generic.partnerCategory.others=0'||chr(13)||chr(10)||'generic.partnerCategory.gridtalk=1');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isPublishable','IS_PUBLISHABLE','"IsPublishable"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.publishable',0,0,0,1,1,'',999,'#temporary setting, kiv for uddi'||chr(13)||chr(10)||'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isSync','IS_SYNC_TO_SERVER','"IsSyncToServer"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.syncToServer',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_state','STATE','"State"','java.lang.Integer','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.beState',0,0,0,1,1,'',5,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'businessEntity.beState.normal=0'||chr(13)||chr(10)||'businessEntity.beState.deleted=1'||chr(13)||chr(10)||'##will need more for application specific'||chr(13)||chr(10)||'businessEntity.beState.active=2'||chr(13)||chr(10)||'businessEntity.beState.inactive=3'||chr(13)||chr(10)||'businessEntity.beState.pending=4'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.canDelete',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.version',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_whitePage','WHITE_PAGE','','com.gridnode.pdip.app.bizreg.model.WhitePage','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.whitePage',0,0,0,1,1,'',999,'','type=embedded'||chr(13)||chr(10)||'embedded.type=whitePage'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_domainIdentifiers','DOMAIN_IDENTIFIERS','','java.util.Collection','com.gridnode.pdip.app.bizreg.model.BusinessEntity','businessEntity.domainIdentifiers',0,0,0,1,1,'',999,'','type=embedded'||chr(13)||chr(10)||'embedded.type=domainIdentifier'||chr(13)||chr(10)||'collection=true'||chr(13)||chr(10));

--------- WhitePage
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.WhitePage';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.uid',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_beUId','BE_UID','"BizEntityUID"','java.lang.Long','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.businessEntity',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=businessEntity.uid'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10)||'foreign.display=businessEntity.description'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_busDesc','BUSINESS_DESC','"BusinessDesc"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.businessDesc',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dUNS','DUNS','"DUNS"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.duns',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=20'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_globalSCCode','G_SUPPLY_CHAIN_CODE','"GlobalSCCode"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.globalSupplyChainCode',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_contactPerson','CONTACT_PERSON','"ContactPerson"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.contactPerson',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_email','EMAIL','"Email"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.email',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_tel','TEL','"Tel"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.tel',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=16'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_fax','FAX','"Fax"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.fax',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=16'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_website','WEBSITE','"Website"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.website',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_address','ADDRESS','"Address"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.address',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_city','CITY','"City"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.city',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_state','STATE','"State"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.state',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=6'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_zipCode','ZIP_CODE','"ZipCode"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.zipCode',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=10'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_pOBox','PO_BOX','"POBox"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.poBox',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=10'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_country','COUNTRY','"Country"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.country',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=countryCode.alpha3Code'||chr(13)||chr(10)||'foreign.display=countryCode.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_language','LANGUAGE','"Language"','java.lang.String','com.gridnode.pdip.app.bizreg.model.WhitePage','whitePage.language',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=languageCode.alpha2Code'||chr(13)||chr(10)||'foreign.display=languageCode.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));


--------- RegistryObjectMapping
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.RegistryObjectMapping';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.uid',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_registryObjectKey','REGISTRY_OBJECT_KEY','"RegistryObjectKey"','java.lang.String','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.registryObjectKey',0,0,0,1,1,'',1,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false','type=text'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_registryObjectType','REGISTRY_OBJECT_TYPE','"RegistryObjectType"','java.lang.String','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.registryObjectType',0,0,0,1,1,'',2,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'registryObjectMapping.registryObjectType.organization=Organization'||chr(13)||chr(10)||'registryObjectMapping.registryObjectType.service=Service'||chr(13)||chr(10)||'registryObjectMapping.registryObjectType.binding=Binding'||chr(13)||chr(10)||'registryObjectMapping.registryObjectType.scheme=Scheme'||chr(13)||chr(10)||'registryObjectMapping.registryObjectType.concept=Concept'||chr(13)||chr(10)||'registryObjectMapping.registryObjectType.specification=Specification'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_registryQueryUrl','REGISTRY_QUERY_URL','"RegistryQueryUrl"','java.lang.String','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.registryQueryUrl',0,0,0,1,1,'',3,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_registryPublishUrl','REGISTRY_PUBLISH_URL','"RegistryPublishUrl"','java.lang.String','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.registryPublishUrl',0,0,0,1,1,'',4,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_proprietaryObjectType','PROPRIETARY_OBJECT_TYPE','"ProprietaryObjectType"','java.lang.String','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.proprietaryObjectType',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=30'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_proprietaryObjectKey','PROPRIETARY_OBJECT_KEY','"ProprietaryObjectKey"','java.lang.String','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.proprietaryObjectKey',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isPublishedObject','IS_PUBLISHED_OBJECT','"IsPublishedObject"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.isPublishedObject',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_state','STATE','"State"','java.lang.Short','com.gridnode.pdip.app.bizreg.pub.model.RegistryObjectMapping','registryObjectMapping.state',0,0,0,1,1,'',5,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'registryObjectMapping.state.sync=0'||chr(13)||chr(10)||'registryObjectMapping.state.deleted=1'||chr(13)||chr(10)||'registryObjectMapping.state.pendDelete=2'||chr(13)||chr(10)||'registryObjectMapping.state.pendUpdate=3'||chr(13)||chr(10));

--------- SearchRegistryCriteria
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.SearchRegistryCriteria';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_match','MATCH','','java.lang.Short','com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria','searchRegistryCriteria.match',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'searchRegistryCriteria.match.all=1'||chr(13)||chr(10)||'searchRegistryCriteria.match.any=2'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_busEntityDesc','BUS_ENTITY_DESC','','java.lang.String','com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria','searchRegistryCriteria.busEntityDesc',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_messagingStandards','MESSAGING_STANDARDS','','java.util.Collection','com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria','searchRegistryCriteria.messagingStandards',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'collection=true'||chr(13)||chr(10)||'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_queryUrl','QUERY_URL','','java.lang.String','com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria','searchRegistryCriteria.queryUrl',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_duns','DUNS','','java.lang.String','com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria','searchRegistryCriteria.duns',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));

--------- SearchRegistryQuery
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.SearchRegistryQuery';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_searchID', 'SEARCH_ID', '', 'java.lang.Long', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.searchId', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_dtSubmitted', 'DT_SUBMITTED', '', 'java.sql.Timestamp', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.dtSubmitted', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_dtResponded', 'DT_RESPONDED', '', 'java.sql.Timestamp', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.dtResponded', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_criteria', 'CRITERIA', '', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryCriteria', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.criteria', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'type=embedded'||chr(13)||chr(10)||'embedded.type=searchRegistryCriteria');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_results', 'RESULTS', '', 'java.util.Collection', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.results', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'collection=true'||chr(13)||chr(10)||'type=embedded'||chr(13)||chr(10)||'embedded.type=searchedBusinessEntity');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_rawResults', 'RAW_RESULTS', '', 'java.util.Collection', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', '', 0, 0, 0, 1, 1, NULL, 999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), '');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_isException', 'IS_EXCEPTION', '', 'java.lang.Boolean', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.isException', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT, '_exceptionStr', 'EXCEPTION_STR', '', 'java.lang.String', 'com.gridnode.pdip.app.bizreg.search.model.SearchRegistryQuery', 'searchRegistryQuery.exceptionStr', 0, 0, 0, 1, 1, NULL, 999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10), 'type=text'||chr(13)||chr(10));

--------- RegistryConnectInfo
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.RegistryConnectInfo';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.uid',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_name','NAME','"Name"','java.lang.String','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.name',0,0,0,1,1,'',1,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_queryUrl','QUERY_URL','"QueryUrl"','java.lang.String','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.queryUrl',0,0,0,1,1,'',3,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_publishUrl','PUBLISH_URL','"PublishUrl"','java.lang.String','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.publishUrl',0,0,0,1,1,'',4,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_publishPassword','PUBLISH_PASSWORD','"PublishPassword"','java.lang.String','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.publishPassword',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=20'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_publishUser','PUBLISH_USER','"PublishUser"','java.lang.String','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.publishUser',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=20'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.model.RegistryConnectInfo','registryConnectInfo.canDelete',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.pdip.pdip.app.model.RegistryConnectInfo','registryConnectInfo.version',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10));

--------- DomainIdentifier
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%.DomainIdentifier';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.bizreg.model.DomainIdentifier','domainIdentifier.uid',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_beUid','BUSINESS_ENTITY_UID','"BizEntityUID"','java.lang.Long','com.gridnode.pdip.app.bizreg.model.DomainIdentifier','domainIdentifier.beUid',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),NULL);
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_domainName','DOMAIN_NAME','"Domain"','java.lang.String','com.gridnode.pdip.app.bizreg.model.DomainIdentifier','domainIdentifier.domainName',0,0,0,1,1,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),NULL);
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_type','TYPE','"Type"','java.lang.String','com.gridnode.pdip.app.bizreg.model.DomainIdentifier','domainIdentifier.type',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'domainIdentifier.type.duns=DunsNumber'||chr(13)||chr(10)||'domainIdentifier.type.as2id=As2Identifier'||chr(13)||chr(10)||'domainIdentifier.type.discoveryUrl=DiscoveryUrl'||chr(13)||chr(10)||'domainIdentifier.type.gln=GlobalLocationNumber'||chr(13)||chr(10)||'domainIdentifier.type.starfishId=StarfishId'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_value','VALUE','"Value"','java.lang.String','com.gridnode.pdip.app.bizreg.model.DomainIdentifier','domainIdentifier.value',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.pdip.app.bizreg.model.DomainIdentifier','domainIdentifier.canDelete',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
