DROP DATABASE IF EXISTS appdb;
CREATE DATABASE appdb;
DROP DATABASE IF EXISTS userdb;
CREATE DATABASE userdb;
DROP DATABASE IF EXISTS archivedb;
CREATE DATABASE archivedb;
DROP DATABASE IF EXISTS jbossdb;
CREATE DATABASE jbossdb;