connect userdb/gridnode;

-- TWX20070617 Update for archive by customer
-- rtprocess uid is set to wrong field.  Added Process Status
CREATE OR REPLACE VIEW "USERDB"."archive_process_view" ("RTProcessUID","EngineType","ProcessType","StartTime","EndTime","ProcessUId","RTProcessDocUID","CustomerBEId","PartnerKey","ProcessStatus") AS SELECT "rtprocess"."UID" AS "RTProcessUID", "rtprocess"."EngineType" AS "EngineType", "rtprocess"."ProcessType" AS "ProcessType","rtprocess"."StartTime" AS "StartTime", "rtprocess"."EndTime" AS "EndTime", "rtprocess"."ProcessUId" AS "ProcessUId","rtprocessdoc"."UID" AS "RTProcessDocUID", "rtprocessdoc"."CustomerBEId" AS "CustomerBEId", "rtprocessdoc"."PartnerKey" AS "PartnerKey", "rtprocessdoc"."Status" AS "ProcessStatus" FROM "rtprocess" JOIN "rtprocessdoc" ON "rtprocess"."UID" = "rtprocessdoc"."RtBinaryCollaborationUId"; 

DELETE FROM "message_template" WHERE "UID"=-23 AND "Name"='ARCHIVE_START_EMAIL';
INSERT INTO "message_template" ("UID", "Name", "ContentType", "MessageType", "FromAddr", "ToAddr", "CcAddr", "Subject", "Message", "Location", "Append", "Version", "CanDelete") 
VALUES (-23,'ARCHIVE_START_EMAIL','Text','EMail','<#USER=admin#>','<#USER=admin#>','','[GRIDTALK] Archive Started','Dear User,'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive by [<%ARCHIVE.ARCHIVE_BY%>] has started at: <%ARCHIVE.START_TIME_UTC%> [<%ARCHIVE.START_TIME%>]'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive [<%ARCHIVE.ARCHIVE_BY%>] Criteria'||chr(13)||chr(10)||'-----------------------------------------------------'||chr(13)||chr(10)||'Is Enable Restore Archive  : <%ARCHIVE.IS_ENABLE_RESTORE_ARCHIVE%>'||chr(13)||chr(10)||'Is Enable Search Archive   : <%ARCHIVE.IS_ENABLE_SEARCH_ARCHIVE%>'||chr(13)||chr(10)||'From Date/Time             : <%ARCHIVE.FROM_DATE_TIME_UTC%> [<%ARCHIVE.FROM_DATE_TIME%>]'||chr(13)||chr(10)||'To Date Time               : <%ARCHIVE.TO_DATE_TIME_UTC%> [<%ARCHIVE.TO_DATE_TIME%>]'||chr(13)||chr(10)||'<%?NProcess Definition         N?ARCHIVE.IS_DOC_TYPE_NULL#Folder                     %>: <%?NN?ARCHIVE.PROCESS_DEF_LIST%><%?NN?ARCHIVE.FOLDER_LIST%>'||chr(13)||chr(10)||'<%?NInclude Incomplete         N?ARCHIVE.IS_DOC_TYPE_NULL#Document Type              %>: <%?NN?ARCHIVE.INCLUDE_INCOMPLETE%><%?NN?ARCHIVE.DOC_TYPE_LIST%>'||chr(13)||chr(10)||'Partners To Archive        : <%ARCHIVE.PARTNER_FOR_ARCHIVE%>'||chr(13)||chr(10)||'Biz Entities To Archive    : <%ARCHIVE.BE_ID_FOR_ARCHIVE%>'||chr(13)||chr(10)||'Is Archive Orphan Record   : <%ARCHIVE.IS_ARCHIVE_ORPHAN_RECORD%>'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive ID                 : <%ARCHIVE.ARCHIVE_ID%>'||chr(13)||chr(10)||chr(13)||chr(10)||chr(13)||chr(10)||'Regards,'||chr(13)||chr(10)||'Gridtalk Server',NULL,NULL,1,0);

DELETE FROM "message_template" WHERE "UID"=-27 AND "Name"='ARCHIVE_COMPLETE_EMAIL';
INSERT INTO "message_template" ("UID", "Name", "ContentType", "MessageType", "FromAddr", "ToAddr", "CcAddr", "Subject", "Message", "Location", "Append", "Version", "CanDelete") 
VALUES (-27,'ARCHIVE_COMPLETE_EMAIL','Text','EMail','<#USER=admin#>','<#USER=admin#>','','[GRIDTALK] Archive Completed','Dear User,'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive by [<%ARCHIVE.ARCHIVE_BY%>] has completed at: <%ARCHIVE.START_TIME_UTC%> [<%ARCHIVE.START_TIME%>]'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive [<%ARCHIVE.ARCHIVE_BY%>] Criteria'||chr(13)||chr(10)||'-----------------------------------------------------'||chr(13)||chr(10)||'Is Enable Restore Archive  : <%ARCHIVE.IS_ENABLE_RESTORE_ARCHIVE%>'||chr(13)||chr(10)||'Is Enable Search Archive   : <%ARCHIVE.IS_ENABLE_SEARCH_ARCHIVE%>'||chr(13)||chr(10)||'From Date/Time             : <%ARCHIVE.FROM_DATE_TIME_UTC%> [<%ARCHIVE.FROM_DATE_TIME%>]'||chr(13)||chr(10)||'To Date Time               : <%ARCHIVE.TO_DATE_TIME_UTC%> [<%ARCHIVE.TO_DATE_TIME%>]'||chr(13)||chr(10)||'<%?NProcess Definition         N?ARCHIVE.IS_DOC_TYPE_NULL#Folder                     %>: <%?NN?ARCHIVE.PROCESS_DEF_LIST%><%?NN?ARCHIVE.FOLDER_LIST%>'||chr(13)||chr(10)||'<%?NInclude Incomplete         N?ARCHIVE.IS_DOC_TYPE_NULL#Document Type              %>: <%?NN?ARCHIVE.INCLUDE_INCOMPLETE%><%?NN?ARCHIVE.DOC_TYPE_LIST%>'||chr(13)||chr(10)||'Partners To Archive        : <%ARCHIVE.PARTNER_FOR_ARCHIVE%>'||chr(13)||chr(10)||'Biz Entities To Archive    : <%ARCHIVE.BE_ID_FOR_ARCHIVE%>'||chr(13)||chr(10)||'Is Archive Orphan Record   : <%ARCHIVE.IS_ARCHIVE_ORPHAN_RECORD%>'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive ID                 : <%ARCHIVE.ARCHIVE_ID%>'||chr(13)||chr(10)||chr(13)||chr(10)||'Number of [<%ARCHIVE.ARCHIVE_BY%>] archived : <%ARCHIVE.NUM_ARCHIVED%>'||chr(13)||chr(10)||chr(13)||chr(10)||'Regards,'||chr(13)||chr(10)||'Gridtalk Server',NULL,NULL,1,0);

DELETE FROM "message_template" WHERE "UID"=-28 AND "Name"='ARCHIVE_FAIL_EMAIL';
INSERT INTO "message_template" ("UID", "Name", "ContentType", "MessageType", "FromAddr", "ToAddr", "CcAddr", "Subject", "Message", "Location", "Append", "Version", "CanDelete") 
VALUES (-28,'ARCHIVE_FAIL_EMAIL','Text','EMail','<#USER=admin#>','<#USER=admin#>','','[GRIDTALK] Archive Failed','Dear User,'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive by [<%ARCHIVE.ARCHIVE_BY%>] has failed at: <%ARCHIVE.START_TIME_UTC%> [<%ARCHIVE.START_TIME%>]'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive [<%ARCHIVE.ARCHIVE_BY%>] Criteria'||chr(13)||chr(10)||'-----------------------------------------------------'||chr(13)||chr(10)||'Is Enable Restore Archive  : <%ARCHIVE.IS_ENABLE_RESTORE_ARCHIVE%>'||chr(13)||chr(10)||'Is Enable Search Archive   : <%ARCHIVE.IS_ENABLE_SEARCH_ARCHIVE%>'||chr(13)||chr(10)||'From Date/Time             : <%ARCHIVE.FROM_DATE_TIME_UTC%> [<%ARCHIVE.FROM_DATE_TIME%>]'||chr(13)||chr(10)||'To Date Time               : <%ARCHIVE.TO_DATE_TIME_UTC%> [<%ARCHIVE.TO_DATE_TIME%>]'||chr(13)||chr(10)||'<%?NProcess Definition         N?ARCHIVE.IS_DOC_TYPE_NULL#Folder                     %>: <%?NN?ARCHIVE.PROCESS_DEF_LIST%><%?NN?ARCHIVE.FOLDER_LIST%>'||chr(13)||chr(10)||'<%?NInclude Incomplete         N?ARCHIVE.IS_DOC_TYPE_NULL#Document Type              %>: <%?NN?ARCHIVE.INCLUDE_INCOMPLETE%><%?NN?ARCHIVE.DOC_TYPE_LIST%>'||chr(13)||chr(10)||'Partners To Archive        : <%ARCHIVE.PARTNER_FOR_ARCHIVE%>'||chr(13)||chr(10)||'Biz Entities To Archive    : <%ARCHIVE.BE_ID_FOR_ARCHIVE%>'||chr(13)||chr(10)||'Is Archive Orphan Record   : <%ARCHIVE.IS_ARCHIVE_ORPHAN_RECORD%>'||chr(13)||chr(10)||chr(13)||chr(10)||'Archive ID                 : <%ARCHIVE.ARCHIVE_ID%>'||chr(13)||chr(10)||chr(13)||chr(10)||'Please verify the problem and restart the operation. (Note: Some documents/processes may have already been archived. It is safe to run the archival again.)'||chr(13)||chr(10)||chr(13)||chr(10)||'Exception : <%Exception.MESSAGE%>'||chr(13)||chr(10)||'Trace:'||chr(13)||chr(10)||'------'||chr(13)||chr(10)||'<%Exception.STACK_TRACE%>'||chr(13)||chr(10)||chr(13)||chr(10)||chr(13)||chr(10)||'Regards,'||chr(13)||chr(10)||'GridTalk Server','','',1,0);


COMMIT;

connect appdb/gridnode;

-- TWX20070617 Update for archive by customer

-- FMI for archiveProcess
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','GWFArchiveProcess','"archive_process_view"');

INSERT INTO "fieldmetainfo" VALUES (NULL,'_uId','UID','"RTProcessUID"','java.lang.Long','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','',0,'0','0','1','1','',999,'displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_engineType','ENGINE_TYPE','"EngineType"','java.lang.String','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','',30,'0','0','1','1','',999,'displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_processType','PROCESS_TYPE','"ProcessType"','java.lang.String','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','',50,'0','0','1','1','',999,'displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_processStartTime','PROCESS_START_TIME','"StartTime"','java.util.Date','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','',0,'0','0','1','1','',999,'displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_processEndTime','PROCESS_END_TIME','"EndTime"','java.util.Date','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','',0,'0','0','1','1','',999,'displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_processUID','PROCESS_UID','"ProcessUId"','java.lang.Long','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','',0,'0','0','1','1','',999,'displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_rtprocessDocUID','RT_PROCESS_DOC_UID','"RTProcessDocUID"','java.lang.Long','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','','0','0','0','0','0','','999','displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_customerBEId','CUSTOMER_BE_ID','"CustomerBEId"','java.lang.String','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','CUSTOMER_BE_ID','4','0','0','0','0','','0','displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_partnerKey','PARTNER_KEY','"PartnerKey"','java.lang.String','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','PARTNER_KEY','50','0','1','1','1','','3','displayable=false','');
INSERT INTO "fieldmetainfo" VALUES (NULL,'_processStatus','PROCESS_STATUS','"ProcessStatus"','java.lang.Integer','com.gridnode.pdip.app.workflow.runtime.model.GWFArchiveProcess','STATUS','0','0','0','0','0','','6','displayable=false','');

COMMIT;