SET DB_HOME=%GRIDTALK_HOME%\pgsql
SET DB_HOST=localhost
SET DB_PORT=35432
SET DB_PASS=gridnode
SET DB_DATA=%GRIDTALK_HOME%\db

SET SVC_NAME=GTAS Database
SET SVC_PASS=gridnode

SET PGHOST=%DB_HOST%
SET PGPORT=%DB_PORT%
SET PGUSER=postgres
REM SET PGPASSWORD=%DB_PASS%
REM SET PGPASSFILE=%APPDATA%\postgresql\pgpass.conf