SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;

DELETE FROM "entitymetainfo" WHERE "EntityName" IN ('UserAccount','UserAccountState');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.user.model.UserAccount','UserAccount','"user_account"');
INSERT INTO "entitymetainfo" VALUES('com.gridnode.pdip.app.user.model.UserAccountState','UserAccountState','"user_account_state"');

--------- UserAccount
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%UserAccount';

INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.user.model.UserAccount','user.uid',20,0,0,0,0,'0',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_id','ID','"ID"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccount','user.userId',15,0,1,1,1,'0',1,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.min=2'||chr(13)||chr(10)||'text.length.max=15');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_name','NAME','"Name"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccount','user.userName',50,0,1,1,1,'0',2,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.min=2'||chr(13)||chr(10)||'text.length.max=50'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_password','PASSWORD','"Password"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccount','user.password',12,1,1,1,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.min=6'||chr(13)||chr(10)||'text.length.max=12'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_phone','PHONE','"Phone"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccount','user.phone',16,0,0,1,1,'0',3,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=16'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_email','EMAIL','"Email"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccount','user.email',255,0,0,1,1,'0',4,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_property','PROPERTY','"Property"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccount','user.property',255,0,0,1,1,'0',5,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_accountState','ACCOUNT_STATE','','com.gridnode.pdip.app.user.model.UserAccountState','com.gridnode.pdip.app.user.model.UserAccount','user.accountState',0,1,0,1,0,'0',999,'','type=embedded'||chr(13)||chr(10)||'embedded.type=accountState'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.pdip.app.user.model.UserAccount','user.version',0,0,0,0,0,'0',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10));

--------- UserAccountState
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%UserAccountState';

INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.app.user.model.UserAccountState','accountState.uid',20,0,0,0,0,'0',999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_userID','USER_ID','"UserID"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccountState','accountState.userId',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=user.userId'||chr(13)||chr(10)||'foreign.display=user.userName'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_state','STATE','"State"','java.lang.Short','com.gridnode.pdip.app.user.model.UserAccountState','accountState.state',1,0,1,1,1,'0',2,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'accountState.state.disabled=0'||chr(13)||chr(10)||'accountState.state.enabled=1'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_numLoginTries','NUM_LOGIN_TRIES','"NumLoginTries"','java.lang.Short','com.gridnode.pdip.app.user.model.UserAccountState','accountState.loginAttempts',2,0,0,1,1,'0',3,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10)||'range.min=0'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isFreeze','IS_FREEZE','"IsFreeze"','java.lang.Boolean','com.gridnode.pdip.app.user.model.UserAccountState','accountState.frozen',0,0,0,1,1,'0',4,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'accountState.frozen.freeze=true'||chr(13)||chr(10)||'accountState.frozen.unfreeze=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_freezeTime','FREEZE_TIME','"FreezeTime"','java.util.Date','com.gridnode.pdip.app.user.model.UserAccountState','accountState.freezeTime',30,0,0,1,1,'0',5,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_lastLoginTime','LAST_LOGIN_TIME','"LastLoginTime"','java.util.Date','com.gridnode.pdip.app.user.model.UserAccountState','accountState.lastLoginTime',30,0,0,0,1,'0',6,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_lastLogoutTime','LAST_LOGOUT_TIME','"LastLogoutTime"','java.util.Date','com.gridnode.pdip.app.user.model.UserAccountState','accountState.lastLogoutTime',30,0,0,0,1,'0',7,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_createTime','CREATE_TIME','"CreateTime"','java.util.Date','com.gridnode.pdip.app.user.model.UserAccountState','accountState.created',30,0,0,0,1,'0',8,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_createBy','CREATE_BY','"CreateBy"','java.lang.String','com.gridnode.pdip.app.user.model.UserAccountState','accountState.createdBy',15,0,0,0,1,'0',9,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.pdip.app.user.model.UserAccountState','accountState.canDelete',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false'||chr(13)||chr(10));
