cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deplib
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\doc
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\sqlscripts
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\web
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf\db.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf\default
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf\entity.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf\jndi.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf\log.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\conf\default\config.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deplib\castor-0.8.11-xml.jar
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deplib\castor-0.8.11.jar
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deplib\log4j-1.1.3.jar
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deplib\webdavclient.jar
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deplib\xerces-1.4.2.jar
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\META-INF
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\sqlscripts
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot\META-INF
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot\META-INF\Search
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot\META-INF\Search\Facade
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot\META-INF\Search\Facade\ejb-jar.xml
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot\META-INF\Search\Facade\jboss.xml
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\ejbroot\META-INF\Search\Facade\MANIFEST.MF
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\META-INF\MANIFEST.MF
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\sqlscripts\base
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\sqlscripts\base\Search
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\sqlscripts\base\Search\populate
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\sqlscripts\base\Search\setup
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client\WEB-INF
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client\WEB-INF\jboss-web.xml
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client\WEB-INF\tlds
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client\WEB-INF\web.xml
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client\WEB-INF\tlds\display.tld
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\deploy\webroot\client\WEB-INF\tlds\search.tld
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects\ant-build.xml
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects\base-Search-dd.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects\global-build.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects\local-build.properties
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects\Search.jpx
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\projects\test_Search.jpx
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\facade
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\helpers
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\facade\ejb
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\facade\ejb\ISearchManagerHome.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\facade\ejb\ISearchManagerObj.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\facade\ejb\SearchManagerBean.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\helpers\FrameworkDbHelper.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\helpers\Logger.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\helpers\QueryHandler.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display\DisplayTag.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display\DisplayTagTEI.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display\FieldDisplay.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display\IDisplayOptions.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display\ResultDisplay.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\src\com\gridnode\pdip\base\search\taglib\display\SelectOption.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\classes
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode\pdip
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode\pdip\base
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode\pdip\base\search
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode\pdip\base\search\facade
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode\pdip\base\search\facade\ejb
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\test\com\gridnode\pdip\base\search\facade\ejb\SearchManagerBeanTest.java
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\web\client
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\web\client\SearchResultTest.jsp
cleardlg /addtosrc /nocheckin C:\sushil_GridApp_1.0\PDIPBaseServices\Search\web\client\SearchTest.jsp
