use appdb;
DELETE FROM entitymetainfo
WHERE ObjectName
IN ('com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo',
    'com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo',
    'com.gridnode.gtas.server.dbarchive.model.FieldValueCollection',
    'com.gridnode.gtas.server.dbarchive.model.AuditFileInfo');

INSERT INTO entitymetainfo VALUES ("com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","DocumentMetaInfo","document_meta_info");
INSERT INTO entitymetainfo VALUES ("com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","ProcessInstanceMetaInfo","process_instance_meta_info");
INSERT INTO entitymetainfo VALUES ("com.gridnode.gtas.server.dbarchive.model.FieldValueCollection","FieldValueCollection","");
INSERT INTO entitymetainfo VALUES ("com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","AuditFileInfo","");

#
# Dumping data for table 'fieldmetainfo'
#
#delete old record
delete from fieldmetainfo where entityobjectname='com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo';

INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeSendEnd","Date_Time_Send_End","DateTimeSendEnd","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeSendEnd","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeSendStart","Date_Time_Send_Start","DateTimeSendStart","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeSendStart","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_folder","Folder","Folder","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.folder","10","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=enum\r\ndocumentMetaInfo.inbound=Inbound\r\ndocumentMetaInfo.outbound=Outbound\r\ndocumentMetaInfo.import=Import\r\ndocumentMetaInfo.export=Export\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_filename","Filename","Filename","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.filename","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");
INSERT INTO fieldmetainfo VALUES(NULL,"_processInstanceID","Process_Instance_ID","ProcessInstanceID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.processInstanceID","200","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=200");
INSERT INTO fieldmetainfo VALUES(NULL,"_processDef","Process_Def","Process_DefID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.processDef","80","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=80");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeExport","Date_Time_Export","DateTimeExport","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeExport","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeImport","Date_Time_Import","DateTimeImport","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeImport","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeCreate","Date_Time_Create","DateTimeCreate","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeCreate","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeReceiveEnd","Date_Time_Receive_End","DateTimeReceiveEnd","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeReceiveEnd","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateTimeReceiveStart","Date_Time_Receive_Start","DateTimeReceiveStart","java.util.Date","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.dateTimeReceiveStart","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_docDateGenerated","Doc_Date_Generated","DocDateGenerated","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.docDateGenrated","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerName","Partner_Name","PartnerName","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.partnerName","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerID","Partner_ID","PartnerID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.partnerID","15","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=15");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerDuns","Partner_Duns","PartnerDuns","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.partnerDuns","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_docNumber","Doc_Number","DocNumber","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.docNumber","50","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=50");
INSERT INTO fieldmetainfo VALUES(NULL,"_docType","Doc_Type","DocType","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.docType","12","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=12");
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=range");
INSERT INTO fieldmetainfo VALUES(NULL,"_uId","UID","UID","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.UID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","","0","0","1","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=enum\r\ncandelete.enabled=true\r\ncandelete.disabled=false");
INSERT INTO fieldmetainfo VALUES(NULL,"_gdocID","GDOC_ID","GdocID","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.gdocID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");
INSERT INTO fieldmetainfo VALUES(NULL,"_originatorID","Originator_ID","OriginatorID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.originatorID","15","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=15");
INSERT INTO fieldmetainfo VALUES(NULL,"_filePath","File_Path","FilePath","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.filePath","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");
INSERT INTO fieldmetainfo VALUES(NULL,"_isArchivedByPI","IS_ARCHIVED_BY_PI","IsArchivedByPI","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.isArchivedByPI","5","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_senderCert","SENDER_CERT","SenderCert","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.senderCert","50","0","0","0","1","","999","displayable=true\r\nmandatory=true\r\neditable=true","type=file\r\file.downloadable=true\r\file.fixedKey=dbarchive.path.estore.cert.directory");
INSERT INTO fieldmetainfo VALUES(NULL,"_receiverCert","RECEIVER_CERT","ReceiverCert","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.receiverCert","50","0","0","0","1","","999","displayable=true\r\nmandatory=true\r\neditable=true","type=file\r\file.downloadable=true\r\file.fixedKey=dbarchive.path.estore.cert.directory");
INSERT INTO fieldmetainfo VALUES(NULL,"_udocFilename","UDOC_FILENAME","UDocFilename","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.udocFilename","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");
INSERT INTO fieldmetainfo VALUES(NULL,'_rnifVersion','RNIF_VERSION','RNIFVersion','java.lang.String','com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo', 'documentMetaInfo.RNIFVersion', 80,'0','0','1','1','', 999, NULL, NULL);
INSERT INTO fieldmetainfo VALUES(NULL,"_pathKey","PATH_KEY","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.pathKey","80","0","1","1","1","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=file");
INSERT INTO fieldmetainfo VALUES(NULL,"_subPathKey","SUB_PATH_KEY","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.subPathKey","80","0","1","1","1","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=80");
INSERT INTO fieldmetainfo VALUES(NULL,"_uiFilename","UI_FILENAME","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.uiFilename","80","0","0","0","1","","999","displayable=true\r\nmandatory=true\r\neditable=true","type=file\r\nfile.downloadable=true\r\nfile.pathKey=documentMetaInfo.pathKey\r\nfile.subPath=subPathKey");
INSERT INTO fieldmetainfo VALUES(NULL,"_processInstanceInfoUID","PROCESS_INSTANCE_INFO_UID","ProcessInstanceInfoUID","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.processInstanceInfoUID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");

INSERT INTO fieldmetainfo VALUES(NULL,"_gdocFilename","GDOC_FILENAME","GdocFilename","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.gdocFilename","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");
INSERT INTO fieldmetainfo VALUES(NULL,"_isOriginalDoc","IS_ORIGINAL_DOC","IsOriginalDoc","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.isOriginalDoc","5","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_isContainAttachment","IS_CONTAIN_ATTACHMENT","IsContainAttachment","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.isContainAttachment","5","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=enum\r\ngeneric.yes=true\r\ngeneric.no=false\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_attachmentFilenames","ATTACHMENT_FILENAMES","AttachmentFilenames","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.attachmentFilenames","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");
INSERT INTO fieldmetainfo VALUES(NULL,"_remark","REMARK","Remark","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.remark","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");

INSERT INTO fieldmetainfo VALUES(NULL,"_receiptAuditFilename","RECEIPT_AUDIT_FILENAME","ReceiptAuditFilename","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.receiptAuditFilename","200","0","0","0","1","","999","displayable=true\r\nmandatory=true\r\neditable=false","type=file\r\nfile.downloadable=true\r\nfile.fixedKey=document.path.as2.audit");
INSERT INTO fieldmetainfo VALUES(NULL,"_docTransStatus","DOC_TRANS_STATUS","DocTransStatus","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo","documentMetaInfo.docTransStatus",255,"0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,"_userTrackingID","USER_TRACKING_ID","UserTrackingID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.DocumentMetaInfo", "documentMetaInfo.userTrackingId",80,"0","0","1","1","", 999,"displayable=true\r\neditable=false\nmandatory=false\r\n","type=text\r\ntext.length.max=80\r\n");


#delete the old record
delete from fieldmetainfo where entityobjectname='com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo';

INSERT INTO fieldmetainfo VALUES(NULL,"_partnerID","Partner_ID","PartnerID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.partnerID","15","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=15");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerName","Partner_Name","PartnerName","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.partnerName","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_docNumber","Doc_Number","DocNumber","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.docNumber","50","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=50");
INSERT INTO fieldmetainfo VALUES(NULL,"_docDateGenerated","Doc_Date_Generated","DocDateGenerated","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.docDateGenerated","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_originatorID","Originator_ID","OriginatorID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.originatorID","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_roleType","Role_Type","RoleType","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.roleType","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_processDef","Process_Def","ProcessDef","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.processDef","80","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=80");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerDuns","Partner_Duns","PartnerDuns","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.partnerDuns","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_processEndDate","Process_End_Date","ProcessEndDate","java.util.Date","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.processEndDate","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_processStartDate","Process_Start_Date","ProcessStartDate","java.util.Date","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.processStartDate","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_processState","Process_State","ProcessState","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.processState","50","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=enum\r\nprocessInstance.state.open=0\r\nprocessInstance.state.running=1\r\nprocessInstance.state.completed=2\r\nprocessInstance.state.suspended=3\r\nprocessInstance.state.abnormallyCompleted=4\r\nprocessInstance.state.abnormallyTerminated=5\r\nprocessInstance.state.abnormallyAborted=6");
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","Version","java.lang.Double","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=range");
INSERT INTO fieldmetainfo VALUES(NULL,"_processInstanceID","Process_Instance_ID","ProcessInstanceID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.processInstanceID","200","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=200");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","CanDelete","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","","0","0","1","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=enum\r\ncandelete.enabled=true\r\ncandelete.disabled=false");
INSERT INTO fieldmetainfo VALUES(NULL,"_uId","UID","UID","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.UID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");
INSERT INTO fieldmetainfo VALUES(NULL,"_assocDocs","ASSOC_DOCS","","java.util.Collection","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.assocDocs","0","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=foreign\r\nforeign.key=documentMetaInfo.uid\r\nforeign.display=documentMetaInfo.filename\r\nforeign.cached=false\r\ncollection=true\r\ncollection.element=java.lang.Long");
INSERT INTO fieldmetainfo VALUES(NULL,"_remark","REMARK","Remark","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo","processInstanceMetaInfo.remark","255","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=255");
INSERT INTO fieldmetainfo VALUES(NULL,"_userTrackingID","USER_TRACKING_ID","UserTrackingID","java.lang.String","com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo", "processInstanceMetaInfo.userTrackingID",80,"0","0","1","1","", 999,"displayable=true\r\neditable=false\nmandatory=false\r\n","type=text\r\ntext.length.max=80\r\n");
INSERT INTO fieldmetainfo VALUES(NULL,'_failedReason','FAILED_REASON','FailedReason','java.lang.Integer','com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo', 'processInstanceMetaInfo.failedReason', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\nmandatory=false\r\n','type=enum\r\nprocessInstance.failReason.retryOut=1\r\nprocessInstance.failReason.actOut=2\r\nprocessInstance.failReason.validateEx=3\r\nprocessInstance.failReason.receiveEx=4\r\nprocessInstance.failReason.userCancel=5\r\n');
INSERT INTO fieldmetainfo VALUES(NULL,'_detailReason','DETAIL_REASON','DetailReason','java.lang.String','com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo', 'processInstanceMetaInfo.detailReason', 250,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=250\r\n');
INSERT INTO fieldmetainfo VALUES(NULL,'_retryNumber','RETRY_NUMBER','RetryNumber','java.lang.Integer','com.gridnode.gtas.server.dbarchive.model.ProcessInstanceMetaInfo', 'processInstanceMetaInfo.retryNumber', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\nmandatory=false\r\n','type=text\r\ntext.length.max=11\r\n');

#add in on 20 OCT 2005
delete from fieldmetainfo where entityobjectname='com.gridnode.gtas.server.dbarchive.model.FieldValueCollection';
INSERT INTO fieldmetainfo VALUES(NULL,"_uId","UID","","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.FieldValueCollection","fieldValueCollection.UID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.FieldValueCollection","","0","0","1","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=enum\r\ncandelete.enabled=true\r\ncandelete.disabled=false");
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","","java.lang.Double","com.gridnode.gtas.server.dbarchive.model.FieldValueCollection","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=range");
INSERT INTO fieldmetainfo VALUES(NULL,"_value","VALUE","","java.util.Collection","com.gridnode.gtas.server.dbarchive.model.FieldValueCollection","fieldValueCollection.value","0","0","1","0","1","","999","displayable=true\r\nmandatory=true\r\neditable=false","type=other\r\ncollection=true\r\ncollection.element=java.lang.Object");


#delete auditFileInfo old record
delete from fieldmetainfo where entityobjectname='com.gridnode.gtas.server.dbarchive.model.AuditFileInfo';

INSERT INTO fieldmetainfo VALUES(NULL,"_uId","UID","","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.UID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");
INSERT INTO fieldmetainfo VALUES(NULL,"_canDelete","CAN_DELETE","","java.lang.Boolean","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","","0","0","1","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=enum\r\ncandelete.enabled=true\r\ncandelete.disabled=false");
INSERT INTO fieldmetainfo VALUES(NULL,"_version","VERSION","","java.lang.Double","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","","0","0","0","0","0","","999","displayable=false\r\nmandatory=false\r\neditable=false","type=range");
INSERT INTO fieldmetainfo VALUES(NULL,"_filename","FILENAME","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.filename","200","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=200");
INSERT INTO fieldmetainfo VALUES(NULL,"_docNo","DOC_NO","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.docNumber","50","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=50");
INSERT INTO fieldmetainfo VALUES(NULL,"_docType","DOC_TYPE","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.docType","12","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=12");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerID","PARTNER_ID","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.partnerID","15","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=15");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerDuns","PARTNER_DUNS","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.partnerDuns","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_partnerName","PARTNER_NAME","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.partnerName","20","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.max=20");
INSERT INTO fieldmetainfo VALUES(NULL,"_dateCreated","DATE_CREATED","","java.util.Date","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.dateTimeCreate","0","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=datetime\r\ndatetime.time=true\r\ndatetime.date=true\r\ndatetime.adjustment=gts");
INSERT INTO fieldmetainfo VALUES(NULL,"_preamble","PREAMBLE","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.preamble","800","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.800");
INSERT INTO fieldmetainfo VALUES(NULL,"_deliveryHeader","DELIVERY_HEADER","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.deliveryHeader","800","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.800");
INSERT INTO fieldmetainfo VALUES(NULL,"_serviceHeader","SERVICE_HEADER","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.serviceHeader","800","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.800");
INSERT INTO fieldmetainfo VALUES(NULL,"_serviceContent","SERVICE_CONTENT","","java.lang.String","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.serviceContent","5000","0","0","0","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=text\r\ntext.length.5000");
INSERT INTO fieldmetainfo VALUES(NULL,"_docMetaInfoUID","DOC_META_INFO_UID","","java.lang.Long","com.gridnode.gtas.server.dbarchive.model.AuditFileInfo","auditFileInfo.docMetaInfoUID","20","0","0","1","1","","999","displayable=true\r\nmandatory=false\r\neditable=false","type=uid");