SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;

DELETE FROM "entitymetainfo" WHERE "EntityName" = 'RNProfile';
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile','"rn_profile"');

---------- RNProfile
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%RNProfile';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.rnif.model.RNProfile' ,'RNProfile.uid',0,0,0 ,1,1,NULL,999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_documentUid','DOCUMENT_UID','"DocumentUid"','java.lang.Long','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.documentUid',0,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processInstanceId','PROCESS_INSTANCE_ID','"ProcessInstanceId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.processInstanceId',200,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processOriginatorId','PROCESS_ORIGINATOR_ID','"ProcessOriginatorId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.processOriginatorId',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processResponderId','PROCESS_RESPONDER_ID','"ProcessResponderId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.processResponderId',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processDefName','PROCESS_DEF_NAME','"ProcessDefName"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.processDefName',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_receiverDomain','RECEIVER_DOMAIN','"ReceiverDomain"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.receiverDomain',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_receiverGlobalBusIdentifier','RECEIVER_GLOBAL_BUS_IDENTIFIER','"ReceiverGlobalBusIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.receiverGlobalBusIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_receiverLocationId','RECEIVER_LOCATION_ID','"ReceiverLocationId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.receiverLocationId',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_senderDomain','SENDER_DOMAIN','"SenderDomain"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.senderDomain',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_senderGlobalBusIdentifier','SENDER_GLOBAL_BUS_IDENTIFIER','"SenderGlobalBusIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.senderGlobalBusIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_senderLocationId','SENDER_LOCATION_ID','"SenderLocationId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.senderLocationId',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_deliveryMessageTrackingId','DELIVERY_MESSAGE_TRACKING_ID','"DeliveryMessageTrackingId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.deliveryMessageTrackingId',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_busActivityIdentifier','BUS_ACTIVITY_IDENTIFIER','"BusActivityIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.busActivityIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_fromGlobalPartnerRoleClassCode','FROM_GLOBAL_PARTNER_ROLE_CLASS_CODE','"FromGlobalPartnerRoleClassCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.fromGlobalPartnerRoleClassCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_fromGlobalBusServiceCode','FROM_GLOBAL_BUS_SERVICE_CODE','"FromGlobalBusServiceCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.fromGlobalBusServiceCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_inReplyToGlobalBusActionCode','IN_REPLY_TO_GLOBAL_BUS_ACTION_CODE','"InReplyToGlobalBusActionCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.inReplyToGlobalBusActionCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_inReplyToMessageStandard','IN_REPLY_TO_MESSAGE_STANDARD','"InReplyToMessageStandard"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.inReplyToMessageStandard',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_inReplyToStandardVersion','IN_REPLY_TO_STANDARD_VERSION','"InReplyToStandardVersion"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.inReplyToStandardVersion',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_inReplyToVersionIdentifier','IN_REPLY_TO_VERSION_IDENTIFIER','"InReplyToVersionIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.inReplyToVersionIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_serviceMessageTrackingId','SERVICE_MESSAGE_TRACKING_ID','"ServiceMessageTrackingId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.serviceMessageTrackingId',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_actionIdentityGlobalBusActionCode','ACTION_IDENTITY_GLOBAL_BUS_ACTION_CODE','"ActionIdentityGlobalBusActionCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.actionIdentityGlobalBusActionCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_actionIdentityToMessageStandard','ACTION_IDENTITY_TO_MESSAGE_STANDARD','"ActionIdentityToMessageStandard"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.actionIdentityToMessageStandard',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_actionIdentityStandardVersion','ACTION_IDENTITY_STANDARD_VERSION','"ActionIdentityStandardVersion"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.actionIdentityStandardVersion',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_actionIdentityVersionIdentifier','ACTION_IDENTITY_VERSION_IDENTIFIER','"ActionIdentityVersionIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.actionIdentityVersionIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_signalIdentityGlobalBusSignalCode','SIGNAL_IDENTITY_GLOBAL_BUS_SIGNAL_CODE','"SignalIdentityGlobalBusSignalCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.signalIdentityGlobalBusSignalCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_signalIdentityVersionIdentifier','SIGNAL_IDENTITY_VERSION_IDENTIFIER','"SignalIdentityVersionIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.signalIdentityVersionIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_toGlobalPartnerRoleClassCode','TO_GLOBAL_PARTNER_ROLE_CLASS_CODE','"ToGlobalPartnerRoleClassCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.toGlobalPartnerRoleClassCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_toGlobalBusServiceCode','TO_GLOBAL_BUS_SERVICE_CODE','"ToGlobalBusServiceCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.toGlobalBusServiceCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_globalUsageCode','GLOBAL_USAGE_CODE','"GlobalUsageCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.globalUsageCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_partnerGlobalBusIdentifier','PARTNER_GLOBAL_BUS_IDENTIFIER','"PartnerGlobalBusIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.partnerGlobalBusIdentifier',0,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_PIPGlobalProcessCode','PIP_GLOBAL_PROCESS_CODE','"PIPGlobalProcessCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.PIPGlobalProcessCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_PIPInstanceIdentifier','PIP_INSTANCE_IDENTIFIER','"PIPInstanceIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.PIPInstanceIdentifier',200,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_PIPVersionIdentifier','PIP_VERSION_IDENTIFIER','"PIPVersionIdentifier"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.PIPVersionIdentifier',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processTransactionId','PROCESS_TRANSACTION_ID','"ProcessTransactionId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.processTransactionId',200,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processActionId','PROCESS_ACTION_ID','"ProcessActionId"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.processActionId',240,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_fromGlobalPartnerClassCode','FROM_GLOBAL_PARTNER_CLASS_CODE','"FromGlobalPartnerClassCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.fromGlobalPartnerClassCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_toGlobalPartnerClassCode','TO_GLOBAL_PARTNER_CLASS_CODE','"ToGlobalPartnerClassCode"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.toGlobalPartnerClassCode',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_numberOfAttas','NUMBER_OF_ATTAS','"NumberOfAttas"','java.lang.Integer','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.numberOfAttas',0,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_isSignalDoc','IS_SIGNAL_DOC','"IsSignalDoc"','java.lang.boolean','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.isSignalDoc',0,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_isRequestMsg','IS_REQUEST_MSG','"IsRequestMsg"','java.lang.boolean','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.IsRequestMsg',0,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_uniqueValue','UNIQUE_VALUE','"UniqueValue"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.uniqueValue',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_attemptCount','ATTEMPT_COUNT','"AttemptCount"','java.lang.Integer','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.attemptCount',0,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_msgDigest','MSG_DIGEST','"MsgDigest"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.msgDigest',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_RNIFVersion','RNIF_VERSION','"RNIFVersion"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.RNIFVersion',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_inResponseToActionID','IN_RESPONSE_TO_ACTION_ID','"InResponseToActionID"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.inResponseToActionID',80,0,0,1,1,'',999,NULL,NULL);
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_userTrackingID','USER_TRACKING_ID','"UserTrackingID"','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile','RNProfile.userTrackingID',80,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
	
	
DELETE FROM "entitymetainfo" WHERE "EntityName" = 'ProcessInstance';
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.rnif.model.ProcessInstance','ProcessInstance',NULL);

---------- ProcessInstance
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ProcessInstance';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_uId','UID','','java.lang.Long','com.gridnode.gtas.server.rnif.model.ProcessInstance' ,'processInstance.uid',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processInstanceId','PROCESS_INSTANCE_ID','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.processInstanceId',200,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=200'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_userTrackingID','USER_TRACKING_ID','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.userTrackingId',80,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));	
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_partner','PARTNER','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.partner',80,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_state','STATE','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.state',50,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'processInstance.state.open=0'||chr(13)||chr(10)||'processInstance.state.running=1'||chr(13)||chr(10)||'processInstance.state.completed=2'||chr(13)||chr(10)||'processInstance.state.suspended=3'||chr(13)||chr(10)||'processInstance.state.abnormallyCompleted=4'||chr(13)||chr(10)||'processInstance.state.abnormallyTerminated=5'||chr(13)||chr(10)||'processInstance.state.abnormallyAborted=6'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_startTime','START_TIME','','java.util.Date','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.startTime',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_endTime','END_TIME','','java.util.Date','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.endTime',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=datetime'||chr(13)||chr(10)||'datetime.adjustment=gts');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_retryNum','RETRY_NUM','','java.lang.Integer','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.retryNum',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=10'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_isFailed','IS_FAILED','','java.lang.Boolean','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.isFailed',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'processInstance.isFailed.true=true'||chr(13)||chr(10)||'processInstance.isFailed.false=false');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_failReason','FAIL_REASON','','java.lang.Integer','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.failReason',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'processInstance.failReason.retryOut=1'||chr(13)||chr(10)||'processInstance.failReason.actOut=2'||chr(13)||chr(10)||'processInstance.failReason.validateEx=3'||chr(13)||chr(10)||'processInstance.failReason.receiveEx=4'||chr(13)||chr(10)||'processInstance.failReason.userCancel=5'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_detailReason','DETAIL_REASON','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.detailReason',250,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=250'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_assocDocs','ASSOC_DOCS','','java.util.Collection','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.assocDocs',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=foreign'||chr(13)||chr(10)||'foreign.key=gridDocument.uid'||chr(13)||chr(10)||'foreign.display=gridDocument.udocFilename'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10)||'collection=true'||chr(13)||chr(10)||'collection.element=java.lang.Long');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_processDefName','PROCESS_DEF_NAME','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.processDefName',80,'0','0','1','1','',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_roleType','ROLE_TYPE','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance','processInstance.roleType',80,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
