// %1023962279379:com.gridnode.pdip.app.deployment.bpss%
/**
 * This software is the proprietary information of GridNode Pte Ltd.
 * Use is subjected to license terms.
 *
 * Copyright 2001-2002 (C) GridNode Pte Ltd. All Rights Reserved.
 *
 * File: 
 *
 ****************************************************************************
 * Date           Author              Changes
 ****************************************************************************
 * Jun 10 2002   Mathew	        Created
 * Jun 13 2002   Mathew         Repackaged
 * Nov 11 2005    Neo Sok Lay         Change to use entityHandler.createEntity
 *                                    to ensure created entity has the correct populated UID
 * Dec 07 2005   Tam Wei Xiang  i)   To remove the depedency on borland xml API.
 *                                   Use GN XML api instead.
 *                              ii)  Change method marshal(), unmarshal(element) to
 *                                   buildElement() and buildModel(element).
 *                              iii) We will use the getParent and setParent method
 *                                   in AbstractBpssModel instead of using XMLObject._getParent
 *                                   and _setParent
 *                              iv)  method validate(boolean) has been removed.   
 */



/**
 * This file is generated by BorlandXML.
 */
package com.gridnode.pdip.app.deploy.manager.bpss;

import java.util.*;

import com.gridnode.pdip.app.deploy.manager.GWFDeployableList;
import com.gridnode.pdip.app.deploy.manager.IGWFDeployable;
import com.gridnode.pdip.app.deploy.manager.util.Utilities;
import com.gridnode.pdip.base.gwfbase.bpss.model.BpssBusinessTrans;
import com.gridnode.pdip.base.gwfbase.bpss.model.BpssProcessSpecEntry;
import com.gridnode.pdip.framework.db.AbstractEntityHandler;
import com.gridnode.pdip.framework.db.EntityHandlerFactory;
import com.gridnode.pdip.framework.exceptions.domain.GWFException;
import com.gridnode.xml.adapters.GNAttribute;
import com.gridnode.xml.adapters.GNElement;
import com.gridnode.xml.adapters.GNXMLDocumentUtility;

/**
 * The BusinessTransaction class represents the element "BusinessTransaction" with the content
 * model defined as follows:
 * <p>
 * &lt;!ELEMENT BusinessTransaction (Documentation*,RequestingBusinessActivity,RespondingBusinessActivity)&gt;<br>
 */
public class BusinessTransaction
  extends AbstractBpssModel
  implements IGWFDeployable
{

  /**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = 5153320712583461522L;

	/** xml tag name of this element. */
  public static String _tagName = "BusinessTransaction";
  
  /** Defines a beginsWhen attribute */
  public GNAttribute beginsWhen = GNXMLDocumentUtility.newAttribute("beginsWhen", ""); 
  
  /** Defines a endsWhen attribute */
  public GNAttribute endsWhen = GNXMLDocumentUtility.newAttribute("endsWhen", ""); 
  
  /** Defines a name attribute */
  public GNAttribute name = GNXMLDocumentUtility.newAttribute("name", ""); 
  
  /** Defines a postCondition attribute */
  public GNAttribute postCondition = GNXMLDocumentUtility.newAttribute("postCondition", "");
  
  /** Defines a isGuaranteedDeliveryRequired attribute */
  public GNAttribute isGuaranteedDeliveryRequired = GNXMLDocumentUtility.newAttribute("isGuaranteedDeliveryRequired", "");
  
  /** Defines a pattern attribute */
  public GNAttribute pattern = GNXMLDocumentUtility.newAttribute("pattern", "");
  
  /** Defines a nameID attribute */
  public GNAttribute nameID = GNXMLDocumentUtility.newAttribute("nameID", "");
  
  /** Defines a preCondition attribute */
  public GNAttribute preCondition = GNXMLDocumentUtility.newAttribute("preCondition", "");
  
  
  /** Defines a list of Documentation objects. */
  protected ArrayList _objDocumentation = new ArrayList();

  /** Defines a RequestingBusinessActivity object */
  protected RequestingBusinessActivity _objRequestingBusinessActivity;

  /** Defines a RespondingBusinessActivity object */
  protected RespondingBusinessActivity _objRespondingBusinessActivity;

  /**
     * Creates an empty BusinessTransaction object
     */
  public BusinessTransaction()
  {
    super();
  }

  /**
     * Gets the value of "beginsWhen" attribute.
     */
  public String getBeginsWhen()
  {
    return beginsWhen.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setBeginsWhen(String value_)
  {
    beginsWhen.setValue(value_);
  }

  /**
     * Gets the value of "endsWhen" attribute.
     */
  public String getEndsWhen()
  {
    return endsWhen.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setEndsWhen(String value_)
  {
    endsWhen.setValue(value_);
  }

  /**
     * Gets the value of "name" attribute.
     */
  public String getName()
  {
    return name.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setName(String value_)
  {
    name.setValue(value_);
  }

  /**
     * Gets the value of "postCondition" attribute.
     */
  public String getPostCondition()
  {
    return postCondition.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setPostCondition(String value_)
  {
    postCondition.setValue(value_);
  }

  /**
     * Gets the value of "isGuaranteedDeliveryRequired" attribute.
     */
  public String getIsGuaranteedDeliveryRequired()
  {
    return isGuaranteedDeliveryRequired.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setIsGuaranteedDeliveryRequired(String value_)
  {
    isGuaranteedDeliveryRequired.setValue(value_);
  }

  /**
     * Gets the value of "pattern" attribute.
     */
  public String getPattern()
  {
    return pattern.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setPattern(String value_)
  {
    pattern.setValue(value_);
  }

  /**
     * Gets the value of "nameID" attribute.
     */
  public String getNameID()
  {
    return nameID.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setNameID(String value_)
  {
    nameID.setValue(value_);
  }

  /**
     * Gets the value of "preCondition" attribute.
     */
  public String getPreCondition()
  {
    return preCondition.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setPreCondition(String value_)
  {
    preCondition.setValue(value_);
  }

  /**
     * Returns an array of Documentation objects. The length of the returned
     * array is zero if the list of Documentation object is empty.
     */
  public Documentation[] getDocumentation()
  {
    return (Documentation[])_objDocumentation.toArray(new Documentation[0]);
  }

  /**
     * Replaces all existing Documentation objects with a new array of
     * Documentation objects.
     * @param objArray    an array of Documentation objects.
     */
  public void setDocumentation(Documentation[] objArray)
  {
    if (objArray == null || objArray.length == 0)
      this._objDocumentation.clear();
    else
    {
      this._objDocumentation = new ArrayList(Arrays.asList(objArray));
      for (int i = 0; i < objArray.length; i++)
      {
        if (objArray[i] != null)
          objArray[i].setParent(this);
      }
    }
  }

  /**
     * Gets the Documentation object at the specified index.
     * @param index    index of the returned object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public Documentation getDocumentation(int index)
  {
    return (Documentation)_objDocumentation.get(index);
  }

  /**
     * Replaces an existing Documentation object at the specified index with
     * a new Documentation object.
     * @param index    index of replaced object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public void setDocumentation(int index, Documentation obj)
  {
    if (obj == null)
      removeDocumentation(index);
    else
    {
      _objDocumentation.set(index, obj);
      obj.setParent(this);
    }
  }

  /**
     * Returns the number of Documentation objects in the list.
     */
  public int getDocumentationCount()
  {
    return _objDocumentation.size();
  }

  /**
     * Returns <code>true</code> if there is no Documentation object in the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean isNoDocumentation()
  {
    return _objDocumentation.size() == 0;
  }

  /**
     * Returns a read-only list of Documentation objects.
     */
  public List getDocumentationList()
  {
    return Collections.unmodifiableList(_objDocumentation);
  }

  /**
     * Adds a new Documentation object at the end of the list.
     * @return <code>true</code> if the new object is added to the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean addDocumentation(Documentation obj)
  {
    if (obj == null)
      return false;
    obj.setParent(this);
    return _objDocumentation.add(obj);
  }

  /**
     * Adds a list of new Documentation objects at the end of the list.
     * @return <code>true</code> if the list was changed; otherwise, the method
     * returns <code>false</code>.
     */
  public boolean addDocumentation(Collection coDocumentation)
  {
    if (coDocumentation == null)
      return false;
    java.util.Iterator it = coDocumentation.iterator();
    while (it.hasNext())
    {
      Object obj = it.next();
      if (obj != null && obj instanceof AbstractBpssModel)
        ((AbstractBpssModel)obj).setParent(this);
    }
    return _objDocumentation.addAll(coDocumentation);
  }

  /**
     * Removes an existing Documentation object at the specified index.
     * @return    The removed object.
     */
  public Documentation removeDocumentation(int index)
  {
    return (Documentation)_objDocumentation.remove(index);
  }

  /**
     * Removes the specified Documentation object.
     * @return <code>true</code> if this list contains the object; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean removeDocumentation(Documentation obj)
  {
    return _objDocumentation.remove(obj);
  }

  /**
     * Clears all Documentation objects from the list.
     */
  public void clearDocumentationList()
  {
    _objDocumentation.clear();
  }

  /**
     * Gets RequestingBusinessActivity object.
     */
  public RequestingBusinessActivity getRequestingBusinessActivity()
  {
    return _objRequestingBusinessActivity;
  }

  /**
     * Replaces the existing RequestingBusinessActivity object with a new object.
     * If you pass in a null value to this method, the RequestingBusinessActivity object is
     * cleared and will not be marshaled.
     * @param obj    A new object.
     */
  public void setRequestingBusinessActivity(RequestingBusinessActivity obj)
  {
    this._objRequestingBusinessActivity = obj;
    if (obj == null)
      return;
    obj.setParent(this);
  }

  /**
     * Gets RespondingBusinessActivity object.
     */
  public RespondingBusinessActivity getRespondingBusinessActivity()
  {
    return _objRespondingBusinessActivity;
  }

  /**
     * Replaces the existing RespondingBusinessActivity object with a new object.
     * If you pass in a null value to this method, the RespondingBusinessActivity object is
     * cleared and will not be marshaled.
     * @param obj    A new object.
     */
  public void setRespondingBusinessActivity(RespondingBusinessActivity obj)
  {
    this._objRespondingBusinessActivity = obj;
    if (obj == null)
      return;
    obj.setParent(this);
  }

  /**
     * Returns a list containing all child elements. Each element in the list is a subclass
     * of XmlObject.
     */
  public java.util.List _getChildren()
  {
    java.util.List children = new java.util.ArrayList();

    /** adds _objDocumentation */
    if (_objDocumentation != null && _objDocumentation.size() > 0)
      children.add(_objDocumentation);

    /** adds _objRequestingBusinessActivity */
    if (_objRequestingBusinessActivity != null)
      children.add(_objRequestingBusinessActivity);

    /** adds _objRespondingBusinessActivity */
    if (_objRespondingBusinessActivity != null)
      children.add(_objRespondingBusinessActivity);
    return children;
  }

  /**
     * Gets the tag name of this element.
     */
  public String get_TagName()
  {
    return _tagName;
  }

  /**
   * DOCUMENT ME!
   * 
   * @param specUId DOCUMENT ME!
   * @param incomplete DOCUMENT ME!
   * @return DOCUMENT ME! 
   * @throws GWFException DOCUMENT ME!
   */
  public int deploy(long specUId, Hashtable incomplete)
             throws GWFException
  {
    GWFDeployableList list = new GWFDeployableList();
    int finalResult = 0;
    if (this.getDocumentationCount() > 0)
    {
      list.addAll(java.util.Arrays.asList(this.getDocumentation()));
      finalResult = Utilities.combineResult(GWF_SUCCESS_DIV, 
                                            list.deploy(specUId, incomplete));
    }
    if (this.getRequestingBusinessActivity() != null)
      finalResult = Utilities.combineResult(GWF_SUCCESS_DIV, 
                                            this.getRequestingBusinessActivity().deploy(
                                                specUId, incomplete));
    if (this.getRespondingBusinessActivity() != null)
      finalResult = Utilities.combineResult(GWF_SUCCESS_DIV, 
                                            this.getRespondingBusinessActivity().deploy(
                                                specUId, incomplete));
    //Deploy attributes to database
    BpssBusinessTrans bpssBizTrans = new BpssBusinessTrans();
    bpssBizTrans.setBusinessTransName(this.getName());
    bpssBizTrans.setPattern(this.getPattern());
    bpssBizTrans.setBeginsWhen(this.getBeginsWhen());
    bpssBizTrans.setEndsWhen(this.getEndsWhen());
    bpssBizTrans.setIsGuaranteedDeliveryRequired(new Boolean(
                                                     this.getIsGuaranteedDeliveryRequired()
        .equals("true") ? true : false));
    bpssBizTrans.setPostCondition(this.getPostCondition());
    bpssBizTrans.setPreCondition(this.getPreCondition());
    bpssBizTrans.setMaxConcurrency(new Integer(1));
    bpssBizTrans.setBpssReqBusinessActivityUId(new Long(0));
    bpssBizTrans.setBpssResBusinessActivityUId(new Long(0));
    //incomplete.put(this, bpssBizTrans);
    try
    {
      AbstractEntityHandler handler = EntityHandlerFactory.getHandlerFor(
                                          BpssBusinessTrans.ENTITY_NAME, true);
      bpssBizTrans = (BpssBusinessTrans)handler.createEntity(bpssBizTrans);
      incomplete.put(this, bpssBizTrans); //NSL20051111 Put the one with UID
      
      BpssProcessSpecEntry bpssProcSpecEntry = new BpssProcessSpecEntry();
      bpssProcSpecEntry.setSpecUId(specUId);
      bpssProcSpecEntry.setEntryName(bpssBizTrans.getBusinessTransName());
      bpssProcSpecEntry.setEntryType(bpssBizTrans.getEntityName());
      bpssProcSpecEntry.setEntryUId(bpssBizTrans.getUId());
      handler = EntityHandlerFactory.getHandlerFor(
                    BpssProcessSpecEntry.ENTITY_NAME, true);
      //handler.create(bpssProcSpecEntry);
      bpssProcSpecEntry = (BpssProcessSpecEntry)handler.createEntity(bpssProcSpecEntry); //NSL20051111

      if (this.getDocumentationCount() > 0)
        list.setParentEntryUId(specUId, bpssProcSpecEntry.getUId());
      if (this.getRequestingBusinessActivity() != null)
        this.getRequestingBusinessActivity().setParentEntryUId(specUId, 
                                                               bpssProcSpecEntry.getUId());
      if (this.getRespondingBusinessActivity() != null)
        this.getRespondingBusinessActivity().setParentEntryUId(specUId, 
                                                               bpssProcSpecEntry.getUId());
    }
    catch (Throwable th)
    {
      //TODO handle RemoteException, ParseException
      System.out.println("Unable to deploy " + bpssBizTrans.getEntityName());
      th.printStackTrace();
      throw new GWFException();
    }
    return finalResult;
  }

  /**
   * DOCUMENT ME!
   * 
   * @param specUId DOCUMENT ME!
   * @param parentEntryUId DOCUMENT ME!
   * @throws GWFException DOCUMENT ME!
   */
  public void setParentEntryUId(long specUId, long parentEntryUId)
                         throws GWFException
  {
    try
    {
      Utilities.setParentEntryUId(specUId, parentEntryUId, this.getName(), 
                                  BpssBusinessTrans.ENTITY_NAME);
    }
    catch (GWFException ex)
    {
      ex.printStackTrace();
      throw new GWFException();
    }
  }
  
  /**
   * Unmarshals the specified "BusinessTransaction" element back to a BusinessTransaction object.
   */
  public BusinessTransaction buildModel(GNElement elem)
  {
  	if (elem == null)
      return null;

      /** Unmarshals "beginsWhen" attribute */
  		super.setAttributeValue(beginsWhen, elem.getAttribute("beginsWhen"));

      /** Unmarshals "endsWhen" attribute */
  		super.setAttributeValue(endsWhen, elem.getAttribute("endsWhen"));

      /** Unmarshals "name" attribute */
  		super.setAttributeValue(name, elem.getAttribute("name"));

      /** Unmarshals "postCondition" attribute */
  		super.setAttributeValue(postCondition, elem.getAttribute("postCondition"));

      /** Unmarshals "isGuaranteedDeliveryRequired" attribute */
  		super.setAttributeValue(isGuaranteedDeliveryRequired, elem.getAttribute("isGuaranteedDeliveryRequired"));

      /** Unmarshals "pattern" attribute */
  		super.setAttributeValue(pattern, elem.getAttribute("pattern"));

      /** Unmarshals "nameID" attribute */
  		super.setAttributeValue(nameID, elem.getAttribute("nameID"));

      /** Unmarshals "preCondition" attribute */
  		super.setAttributeValue(preCondition, elem.getAttribute("preCondition"));
    

    /** Unmarshals a list of "<<_tagName_>>" elements back to Documentation objects. */
    Iterator it1 = elem.getChildren(Documentation._tagName).iterator();
    while (it1.hasNext())
    {
    	Documentation doc = new Documentation();
      addDocumentation(doc.buildModel(
                                                    (GNElement)it1.next()));
    }
    
    /** Unmarshals an element back to a RequestingBusinessActivity object */
    RequestingBusinessActivity reqBZAct = new RequestingBusinessActivity();
    setRequestingBusinessActivity(reqBZAct.buildModel(elem.getChild(
                                                                                                    RequestingBusinessActivity._tagName)));

    /** Unmarshals an element back to a RespondingBusinessActivity object */
    RespondingBusinessActivity respondBZAct = new RespondingBusinessActivity();
    setRespondingBusinessActivity(respondBZAct.buildModel(elem.getChild(
                                                                                                    RespondingBusinessActivity._tagName)));
    return this;
  }
  
  /**
   * Marshals this object to an element.
   */
  public GNElement buildElement()
  {
  	GNElement elem = GNXMLDocumentUtility.newElement(get_TagName());

    /** Marshals "beginsWhen" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, beginsWhen);

    /** Marshals "endsWhen" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, endsWhen);

    /** Marshals "name" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_REQUIRED, name);

    /** Marshals "postCondition" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, postCondition);

    /** Marshals "isGuaranteedDeliveryRequired" attribute */
  	addAttributeToElement(elem, "", isGuaranteedDeliveryRequired);

    /** Marshals "pattern" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, pattern);

    /** Marshals "nameID" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, nameID);

    /** Marshals "preCondition" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, preCondition);

    /** Marshals a list of Documentation objects to elements */
    Iterator it1 = _objDocumentation.iterator();
    while (it1.hasNext())
    {
      Documentation obj = (Documentation)it1.next();
      if (obj != null)
        elem.addElement(obj.buildElement());
    }

    /** Marshals a RequestingBusinessActivity object to an element */
    if (_objRequestingBusinessActivity != null)
      elem.addElement(_objRequestingBusinessActivity.buildElement());

    /** Marshals a RespondingBusinessActivity object to an element */
    if (_objRespondingBusinessActivity != null)
      elem.addElement(_objRespondingBusinessActivity.buildElement());
    return elem;
  }
  
}
