// %1023962282301:com.gridnode.pdip.app.deployment.bpss%
/**
 * This software is the proprietary information of GridNode Pte Ltd.
 * Use is subjected to license terms.
 *
 * Copyright 2001-2002 (C) GridNode Pte Ltd. All Rights Reserved.
 *
 * File: 
 *
 ****************************************************************************
 * Date           Author              Changes
 ****************************************************************************
 * Jun 10 2002   Mathew	        Created
 * Jun 13 2002   Mathew         Repackaged
 * Dec 06 2005   Tam Wei Xiang  i)To remove the depedency on borland xml API.
 *                              Use GN XML api instead.
 *                              ii)Change method marshal(), unmarshal(element) to
 *                              buildElement() and buildModel(element).
 *                              iii) We will use the getParent and setParent method
 *                                   in AbstractBpssModel instead of using XMLObject._getParent
 *                                   and _setParent
 *                              iv)  method validate(boolean) has been removed.
 */



/**
 * This file is generated by BorlandXML.
 */
package com.gridnode.pdip.app.deploy.manager.bpss;

import java.util.*;

import com.gridnode.pdip.app.deploy.manager.IGWFDeployable;
import com.gridnode.pdip.framework.exceptions.domain.GWFException;
import com.gridnode.xml.adapters.GNAttribute;
import com.gridnode.xml.adapters.GNElement;
import com.gridnode.xml.adapters.GNXMLDocumentUtility;

/**
 * The SubstitutionSet class represents the element "SubstitutionSet" with the content
 * model defined as follows:
 * <p>
 * &lt;!ELEMENT SubstitutionSet (DocumentSubstitution|AttributeSubstitution|Documentation)*&gt;<br>
 */
public class SubstitutionSet
  extends AbstractBpssModel
  implements IGWFDeployable
{

  /**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = -8718295346570153570L;

	/** xml tag name of this element. */
  public static String _tagName = "SubstitutionSet";

  
  //TWX
  /** Defines a name attribute */
  public GNAttribute name = GNXMLDocumentUtility.newAttribute("name","");
  
  /** Defines a applyToScope attribute */
  public GNAttribute applyToScope = GNXMLDocumentUtility.newAttribute("applyToScope","");
  
  /** Defines a nameId attribute */
  public GNAttribute nameId = GNXMLDocumentUtility.newAttribute("nameId","");
  //end
  
  /** Defines a list of DocumentSubstitution objects. */
  protected ArrayList _objDocumentSubstitution = new ArrayList();

  /** Defines a list of AttributeSubstitution objects. */
  protected ArrayList _objAttributeSubstitution = new ArrayList();

  /** Defines a list of Documentation objects. */
  protected ArrayList _objDocumentation = new ArrayList();

  /**
     * Creates an empty SubstitutionSet object
     */
  public SubstitutionSet()
  {
    super();
  }

  /**
     * Gets the value of "name" attribute.
     */
  public String getName()
  {
    return name.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setName(String value_)
  {
    name.setValue(value_);
  }

  /**
     * Gets the value of "applyToScope" attribute.
     */
  public String getApplyToScope()
  {
    return applyToScope.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setApplyToScope(String value_)
  {
    applyToScope.setValue(value_);
  }

  /**
     * Gets the value of "nameId" attribute.
     */
  public String getNameId()
  {
    return nameId.getValue();
  }

  /**
     * Replaces the existing attribute value with a new value.
     * @param value    New value.
     */
  public void setNameId(String value_)
  {
    nameId.setValue(value_);
  }

  /**
     * Returns an array of DocumentSubstitution objects. The length of the returned
     * array is zero if the list of DocumentSubstitution object is empty.
     */
  public DocumentSubstitution[] getDocumentSubstitution()
  {
    return (DocumentSubstitution[])_objDocumentSubstitution.toArray(
                 new DocumentSubstitution[0]);
  }

  /**
     * Replaces all existing DocumentSubstitution objects with a new array of
     * DocumentSubstitution objects.
     * @param objArray    an array of DocumentSubstitution objects.
     */
  public void setDocumentSubstitution(DocumentSubstitution[] objArray)
  {
    if (objArray == null || objArray.length == 0)
      this._objDocumentSubstitution.clear();
    else
    {
      this._objDocumentSubstitution = new ArrayList(Arrays.asList(objArray));
      for (int i = 0; i < objArray.length; i++)
      {
        if (objArray[i] != null)
          objArray[i].setParent(this);
      }
    }
  }

  /**
     * Gets the DocumentSubstitution object at the specified index.
     * @param index    index of the returned object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public DocumentSubstitution getDocumentSubstitution(int index)
  {
    return (DocumentSubstitution)_objDocumentSubstitution.get(index);
  }

  /**
     * Replaces an existing DocumentSubstitution object at the specified index with
     * a new DocumentSubstitution object.
     * @param index    index of replaced object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public void setDocumentSubstitution(int index, DocumentSubstitution obj)
  {
    if (obj == null)
      removeDocumentSubstitution(index);
    else
    {
      _objDocumentSubstitution.set(index, obj);
      obj.setParent(this);
    }
  }

  /**
     * Returns the number of DocumentSubstitution objects in the list.
     */
  public int getDocumentSubstitutionCount()
  {
    return _objDocumentSubstitution.size();
  }

  /**
     * Returns <code>true</code> if there is no DocumentSubstitution object in the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean isNoDocumentSubstitution()
  {
    return _objDocumentSubstitution.size() == 0;
  }

  /**
     * Returns a read-only list of DocumentSubstitution objects.
     */
  public List getDocumentSubstitutionList()
  {
    return Collections.unmodifiableList(_objDocumentSubstitution);
  }

  /**
     * Adds a new DocumentSubstitution object at the end of the list.
     * @return <code>true</code> if the new object is added to the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean addDocumentSubstitution(DocumentSubstitution obj)
  {
    if (obj == null)
      return false;
    obj.setParent(this);
    return _objDocumentSubstitution.add(obj);
  }

  /**
     * Adds a list of new DocumentSubstitution objects at the end of the list.
     * @return <code>true</code> if the list was changed; otherwise, the method
     * returns <code>false</code>.
     */
  public boolean addDocumentSubstitution(Collection coDocumentSubstitution)
  {
    if (coDocumentSubstitution == null)
      return false;
    java.util.Iterator it = coDocumentSubstitution.iterator();
    while (it.hasNext())
    {
      Object obj = it.next();
      
      if (obj != null && obj instanceof AbstractBpssModel)
        ((AbstractBpssModel)obj).setParent(this);
        
    }
    return _objDocumentSubstitution.addAll(coDocumentSubstitution);
  }

  /**
     * Removes an existing DocumentSubstitution object at the specified index.
     * @return    The removed object.
     */
  public DocumentSubstitution removeDocumentSubstitution(int index)
  {
    return (DocumentSubstitution)_objDocumentSubstitution.remove(index);
  }

  /**
     * Removes the specified DocumentSubstitution object.
     * @return <code>true</code> if this list contains the object; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean removeDocumentSubstitution(DocumentSubstitution obj)
  {
    return _objDocumentSubstitution.remove(obj);
  }

  /**
     * Clears all DocumentSubstitution objects from the list.
     */
  public void clearDocumentSubstitutionList()
  {
    _objDocumentSubstitution.clear();
  }

  /**
     * Returns an array of AttributeSubstitution objects. The length of the returned
     * array is zero if the list of AttributeSubstitution object is empty.
     */
  public AttributeSubstitution[] getAttributeSubstitution()
  {
    return (AttributeSubstitution[])_objAttributeSubstitution.toArray(
                 new AttributeSubstitution[0]);
  }

  /**
     * Replaces all existing AttributeSubstitution objects with a new array of
     * AttributeSubstitution objects.
     * @param objArray    an array of AttributeSubstitution objects.
     */
  public void setAttributeSubstitution(AttributeSubstitution[] objArray)
  {
    if (objArray == null || objArray.length == 0)
      this._objAttributeSubstitution.clear();
    else
    {
      this._objAttributeSubstitution = new ArrayList(Arrays.asList(objArray));
      for (int i = 0; i < objArray.length; i++)
      {
      	
        if (objArray[i] != null)
          objArray[i].setParent(this);
          
      }
    }
  }

  /**
     * Gets the AttributeSubstitution object at the specified index.
     * @param index    index of the returned object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public AttributeSubstitution getAttributeSubstitution(int index)
  {
    return (AttributeSubstitution)_objAttributeSubstitution.get(index);
  }

  /**
     * Replaces an existing AttributeSubstitution object at the specified index with
     * a new AttributeSubstitution object.
     * @param index    index of replaced object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public void setAttributeSubstitution(int index, AttributeSubstitution obj)
  {
    if (obj == null)
      removeAttributeSubstitution(index);
    else
    {
      _objAttributeSubstitution.set(index, obj);
      obj.setParent(this);
    }
  }

  /**
     * Returns the number of AttributeSubstitution objects in the list.
     */
  public int getAttributeSubstitutionCount()
  {
    return _objAttributeSubstitution.size();
  }

  /**
     * Returns <code>true</code> if there is no AttributeSubstitution object in the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean isNoAttributeSubstitution()
  {
    return _objAttributeSubstitution.size() == 0;
  }

  /**
     * Returns a read-only list of AttributeSubstitution objects.
     */
  public List getAttributeSubstitutionList()
  {
    return Collections.unmodifiableList(_objAttributeSubstitution);
  }

  /**
     * Adds a new AttributeSubstitution object at the end of the list.
     * @return <code>true</code> if the new object is added to the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean addAttributeSubstitution(AttributeSubstitution obj)
  {
    if (obj == null)
      return false;
    obj.setParent(this);
    return _objAttributeSubstitution.add(obj);
  }

  /**
     * Adds a list of new AttributeSubstitution objects at the end of the list.
     * @return <code>true</code> if the list was changed; otherwise, the method
     * returns <code>false</code>.
     */
  public boolean addAttributeSubstitution(Collection coAttributeSubstitution)
  {
    if (coAttributeSubstitution == null)
      return false;
    java.util.Iterator it = coAttributeSubstitution.iterator();
    while (it.hasNext())
    {
      Object obj = it.next();
      
      if (obj != null && obj instanceof AbstractBpssModel)
        ((AbstractBpssModel)obj).setParent(this);
        
    }
    return _objAttributeSubstitution.addAll(coAttributeSubstitution);
  }

  /**
     * Removes an existing AttributeSubstitution object at the specified index.
     * @return    The removed object.
     */
  public AttributeSubstitution removeAttributeSubstitution(int index)
  {
    return (AttributeSubstitution)_objAttributeSubstitution.remove(index);
  }

  /**
     * Removes the specified AttributeSubstitution object.
     * @return <code>true</code> if this list contains the object; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean removeAttributeSubstitution(AttributeSubstitution obj)
  {
    return _objAttributeSubstitution.remove(obj);
  }

  /**
     * Clears all AttributeSubstitution objects from the list.
     */
  public void clearAttributeSubstitutionList()
  {
    _objAttributeSubstitution.clear();
  }

  /**
     * Returns an array of Documentation objects. The length of the returned
     * array is zero if the list of Documentation object is empty.
     */
  public Documentation[] getDocumentation()
  {
    return (Documentation[])_objDocumentation.toArray(new Documentation[0]);
  }

  /**
     * Replaces all existing Documentation objects with a new array of
     * Documentation objects.
     * @param objArray    an array of Documentation objects.
     */
  public void setDocumentation(Documentation[] objArray)
  {
    if (objArray == null || objArray.length == 0)
      this._objDocumentation.clear();
    else
    {
      this._objDocumentation = new ArrayList(Arrays.asList(objArray));
      for (int i = 0; i < objArray.length; i++)
      {
      	
        if (objArray[i] != null)
          objArray[i].setParent(this);
           
      }
    }
  }

  /**
     * Gets the Documentation object at the specified index.
     * @param index    index of the returned object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public Documentation getDocumentation(int index)
  {
    return (Documentation)_objDocumentation.get(index);
  }

  /**
     * Replaces an existing Documentation object at the specified index with
     * a new Documentation object.
     * @param index    index of replaced object.
     * @throws IndexOutOfBoundsException    if index is out of range.
     */
  public void setDocumentation(int index, Documentation obj)
  {
    if (obj == null)
      removeDocumentation(index);
    else
    {
      _objDocumentation.set(index, obj);
      obj.setParent(this);
    }
  }

  /**
     * Returns the number of Documentation objects in the list.
     */
  public int getDocumentationCount()
  {
    return _objDocumentation.size();
  }

  /**
     * Returns <code>true</code> if there is no Documentation object in the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean isNoDocumentation()
  {
    return _objDocumentation.size() == 0;
  }

  /**
     * Returns a read-only list of Documentation objects.
     */
  public List getDocumentationList()
  {
    return Collections.unmodifiableList(_objDocumentation);
  }

  /**
     * Adds a new Documentation object at the end of the list.
     * @return <code>true</code> if the new object is added to the list; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean addDocumentation(Documentation obj)
  {
    if (obj == null)
      return false;
    obj.setParent(this);
    return _objDocumentation.add(obj);
  }

  /**
     * Adds a list of new Documentation objects at the end of the list.
     * @return <code>true</code> if the list was changed; otherwise, the method
     * returns <code>false</code>.
     */
  public boolean addDocumentation(Collection coDocumentation)
  {
    if (coDocumentation == null)
      return false;
    java.util.Iterator it = coDocumentation.iterator();
    while (it.hasNext())
    {
      Object obj = it.next();
      
      if (obj != null && obj instanceof AbstractBpssModel)
        ((AbstractBpssModel)obj).setParent(this);
        
    }
    return _objDocumentation.addAll(coDocumentation);
  }

  /**
     * Removes an existing Documentation object at the specified index.
     * @return    The removed object.
     */
  public Documentation removeDocumentation(int index)
  {
    return (Documentation)_objDocumentation.remove(index);
  }

  /**
     * Removes the specified Documentation object.
     * @return <code>true</code> if this list contains the object; otherwise,
     * the method returns <code>false</code>.
     */
  public boolean removeDocumentation(Documentation obj)
  {
    return _objDocumentation.remove(obj);
  }

  /**
     * Clears all Documentation objects from the list.
     */
  public void clearDocumentationList()
  {
    _objDocumentation.clear();
  }


  /**
     * Returns a list containing all child elements. Each element in the list is a subclass
     * of XmlObject.
     */
  public java.util.List _getChildren()
  {
    java.util.List children = new java.util.ArrayList();

    /** adds _objDocumentSubstitution */
    if (_objDocumentSubstitution != null && 
        _objDocumentSubstitution.size() > 0)
      children.add(_objDocumentSubstitution);

    /** adds _objAttributeSubstitution */
    if (_objAttributeSubstitution != null && 
        _objAttributeSubstitution.size() > 0)
      children.add(_objAttributeSubstitution);

    /** adds _objDocumentation */
    if (_objDocumentation != null && _objDocumentation.size() > 0)
      children.add(_objDocumentation);
    return children;
  }

  /**
     * Gets the tag name of this element.
     */
  public String get_TagName()
  {
    return _tagName;
  }

  /**
   * DOCUMENT ME!
   * 
   * @param specUId DOCUMENT ME!
   * @param incomplete DOCUMENT ME!
   * @return DOCUMENT ME! 
   * @throws GWFException DOCUMENT ME!
   */
  public int deploy(long specUId, Hashtable incomplete)
             throws GWFException
  {
    return 1;
  }

  /**
   * DOCUMENT ME!
   * 
   * @param specUId DOCUMENT ME!
   * @param parentEntryUId DOCUMENT ME!
   * @throws GWFException DOCUMENT ME!
   */
  public void setParentEntryUId(long specUId, long parentEntryUId)
                         throws GWFException
  {
  }
  
  /**
   * Unmarshals the specified "SubstitutionSet" element back to a SubstitutionSet object.
   */
  public SubstitutionSet buildModel(GNElement elem)
  {
  	if (elem == null)
      return null;

      /** Unmarshals "name" attribute */
  	  super.setAttributeValue(name, elem.getAttribute("name"));

      /** Unmarshals "applyToScope" attribute */
  	  super.setAttributeValue(applyToScope, elem.getAttribute("applyToScope"));
      
      /** Unmarshals "nameId" attribute */
  	  super.setAttributeValue(nameId, elem.getAttribute("nameId"));


    /** Unmarshals a list of "<<_tagName_>>" elements back to DocumentSubstitution objects. */
    Iterator it1 = elem.getChildren(DocumentSubstitution._tagName).iterator();
    while (it1.hasNext())
    {	
    	DocumentSubstitution docSub = new DocumentSubstitution();
      addDocumentSubstitution(docSub.buildModel((GNElement)it1.next()));
    }  
    /** Unmarshals a list of "<<_tagName_>>" elements back to AttributeSubstitution objects. */
    Iterator it2 = elem.getChildren(AttributeSubstitution._tagName).iterator();
    while (it2.hasNext())
    {
    	AttributeSubstitution attSub = new AttributeSubstitution();
      addAttributeSubstitution(attSub.buildModel(
                                                        (GNElement)it2.next()));
    }
    /** Unmarshals a list of "<<_tagName_>>" elements back to Documentation objects. */
    Iterator it3 = elem.getChildren(Documentation._tagName).iterator();
    while (it3.hasNext())
    {
    	Documentation doc = new Documentation();
      addDocumentation(doc.buildModel(
                                                (GNElement)it3.next()));
    }
    return this;
  }
  
  /**
   * Marshals this object to an element.
   */
  public GNElement buildElement()
  {
  	GNElement elem = GNXMLDocumentUtility.newElement(get_TagName());

    /** Marshals "name" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, name);

    /** Marshals "applyToScope" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, applyToScope);

    /** Marshals "nameId" attribute */
  	addAttributeToElement(elem, this._ATTR_DEFAULT_IMPLIED, nameId);

    /** Marshals a list of DocumentSubstitution objects to elements */
    Iterator it1 = _objDocumentSubstitution.iterator();
    while (it1.hasNext())
    {
      DocumentSubstitution obj = (DocumentSubstitution)it1.next();
      if (obj != null)
        elem.addElement(obj.buildElement());
    }

    /** Marshals a list of AttributeSubstitution objects to elements */
    Iterator it2 = _objAttributeSubstitution.iterator();
    while (it2.hasNext())
    {
      AttributeSubstitution obj = (AttributeSubstitution)it2.next();
      if (obj != null)
        elem.addElement(obj.buildElement());
    }

    /** Marshals a list of Documentation objects to elements */
    Iterator it3 = _objDocumentation.iterator();
    while (it3.hasNext())
    {
      Documentation obj = (Documentation)it3.next();
      if (obj != null)
        elem.addElement(obj.buildElement());
    }
    return elem;
  }
}