--- --------------------------------------------------------------------------
--- This script creates the User 'JBOSSDB' And creates default table "TIMERS" 
--- 
--- Required user to connect as SYSDBA to grant the necessary privileges
--- --------------------------------------------------------------------------


--
-- Definition for USER JBOSSDB:
--

CREATE USER JBOSSDB
  IDENTIFIED BY "gridnode"
    DEFAULT TABLESPACE GRIDTALK_DATA01
    TEMPORARY TABLESPACE TEMP
    PROFILE "DEFAULT"
    ACCOUNT UNLOCK  QUOTA UNLIMITED ON GRIDTALK_DATA01;

--
-- Grants for USER JBOSSDB
--
-- System Privileges
GRANT CREATE DATABASE LINK TO JBOSSDB;
GRANT ALTER SESSION TO JBOSSDB;
GRANT CREATE PUBLIC SYNONYM TO JBOSSDB;
GRANT CREATE TABLE TO JBOSSDB;
GRANT CREATE PROCEDURE TO JBOSSDB;
GRANT CREATE TYPE TO JBOSSDB;
GRANT CREATE SEQUENCE TO JBOSSDB;
GRANT CREATE SESSION TO JBOSSDB;
GRANT CREATE TRIGGER TO JBOSSDB;
GRANT CREATE SYNONYM TO JBOSSDB;
GRANT CREATE MATERIALIZED VIEW TO JBOSSDB;
GRANT CREATE ROLE TO JBOSSDB;
GRANT CREATE VIEW TO JBOSSDB;

-- Roles
GRANT "CONNECT" TO JBOSSDB;

--Object Privileges
GRANT EXECUTE ON SYS.DBMS_STATS TO JBOSSDB;
/

CONNECT JBOSSDB/gridnode;
---
--- Table structure for table 'TIMERS'
---

CREATE TABLE JBOSSDB.TIMERS
(
  "TIMERID" VARCHAR2(50),
  "TARGETID" VARCHAR2(50) NOT NULL,
  "INITIALDATE" TIMESTAMP(6) NOT NULL,
  "INTERVAL" NUMBER(19,0),
  "INSTANCEPK" BLOB,
  "INFO" BLOB,
  PRIMARY KEY ("TIMERID")
);

CREATE TABLE JBOSSDB."schedule"
(
  "schedule_uid" NUMBER(19),
  "target" VARCHAR2(100),
  "method_name" VARCHAR2(100),
  "method_signature" VARCHAR2(100),
  "start_date" VARCHAR2(20),
  "period" NUMBER(19),
  "repetitions" NUMBER(10),
  "date_format" VARCHAR2(20),
  PRIMARY KEY ("schedule_uid")
);

CREATE SEQUENCE JBOSS_SCHEDULE_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE; 

CREATE TRIGGER JBOSS_SCHEDULE_TRIGGER 
BEFORE INSERT ON "schedule"
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW
BEGIN
     SELECT JBOSS_SCHEDULE_SEQ.NEXTVAL INTO :NEW."schedule_uid" FROM DUAL;
END;
/

COMMIT;