-- -----------------------------------------------------------------
-- This script Creates default data for some of the tables in APPDB
-- -----------------------------------------------------------------


CONNECT APPDB/gridnode;

---
--- data for table 'country_code'
---
INSERT INTO "country_code" VALUES('Andorra',20,'AD','AND');
INSERT INTO "country_code" VALUES('United Arab Emirates',784,'AE','ARE');
INSERT INTO "country_code" VALUES('Afghanistan',4,'AF','AFG');
INSERT INTO "country_code" VALUES('Antigua and Barbuda',28,'AG','ATG');
INSERT INTO "country_code" VALUES('Anguilla',660,'AI','AIA');
INSERT INTO "country_code" VALUES('Albania',8,'AL','ALB');
INSERT INTO "country_code" VALUES('Armenia',51,'AM','ARM');
INSERT INTO "country_code" VALUES('Netherlands Antilles',530,'AN','ANT');
INSERT INTO "country_code" VALUES('Angola',24,'AO','AGO');
INSERT INTO "country_code" VALUES('Argentina',32,'AR','ARG');
INSERT INTO "country_code" VALUES('American Samoa',16,'AS','ASM');
INSERT INTO "country_code" VALUES('Austria',40,'AT','AUT');
INSERT INTO "country_code" VALUES('Australia',36,'AU','AUS');
INSERT INTO "country_code" VALUES('Aruba',533,'AW','ABW');
INSERT INTO "country_code" VALUES('Azerbaijan',31,'AZ','AZE');
INSERT INTO "country_code" VALUES('Bosnia and Herzegovina',70,'BA','BIH');
INSERT INTO "country_code" VALUES('Barbados',52,'BB','BRB');
INSERT INTO "country_code" VALUES('Bangladesh',50,'BD','BGD');
INSERT INTO "country_code" VALUES('Belgium',56,'BE','BEL');
INSERT INTO "country_code" VALUES('Benin',204,'BJ','BEN');
INSERT INTO "country_code" VALUES('Burkina Faso',854,'BF','BFA');
INSERT INTO "country_code" VALUES('Bulgaria',100,'BG','BGR');
INSERT INTO "country_code" VALUES('Bahrain',48,'BH','BHR');
INSERT INTO "country_code" VALUES('Burundi',108,'BI','BDI');
INSERT INTO "country_code" VALUES('Bermuda',60,'BM','BMU');
INSERT INTO "country_code" VALUES('Brunei Darussalam',96,'BN','BRN');
INSERT INTO "country_code" VALUES('Bolivia',68,'BO','BOL');
INSERT INTO "country_code" VALUES('Brazil',76,'BR','BRA');
INSERT INTO "country_code" VALUES('Bahamas',44,'BS','BHS');
INSERT INTO "country_code" VALUES('Bhutan',64,'BT','BTN');
INSERT INTO "country_code" VALUES('Botswana',72,'BW','BWA');
INSERT INTO "country_code" VALUES('Belarus',112,'BY','BLR');
INSERT INTO "country_code" VALUES('Belize',84,'BZ','BLZ');
INSERT INTO "country_code" VALUES('Canada',124,'CA','CAN');
INSERT INTO "country_code" VALUES('Congo, Democratic Republic of the',180,'CD','COD');
INSERT INTO "country_code" VALUES('Central African Republic',140,'CF','CAF');
INSERT INTO "country_code" VALUES('Congo',178,'CG','COG');
INSERT INTO "country_code" VALUES('Switzerland',756,'CH','CHE');
INSERT INTO "country_code" VALUES('Côte d''Ivoire',384,'CI','CIV');
INSERT INTO "country_code" VALUES('Cook Islands',184,'CK','COK');
INSERT INTO "country_code" VALUES('Chile',152,'CL','CHL');
INSERT INTO "country_code" VALUES('Cameroon',120,'CM','CMR');
INSERT INTO "country_code" VALUES('China',156,'CN','CHN');
INSERT INTO "country_code" VALUES('Colombia',170,'CO','COL');
INSERT INTO "country_code" VALUES('Costa Rica',188,'CR','CRI');
INSERT INTO "country_code" VALUES('Cuba',192,'CU','CUB');
INSERT INTO "country_code" VALUES('Cape Verde Islands',132,'CV','CPV');
INSERT INTO "country_code" VALUES('Cyprus',196,'CY','CYP');
INSERT INTO "country_code" VALUES('Czech Republic',203,'CZ','CZE');
INSERT INTO "country_code" VALUES('Germany',276,'DE','DEU');
INSERT INTO "country_code" VALUES('Djibouti',262,'DJ','DJI');
INSERT INTO "country_code" VALUES('Denmark',208,'DK','DNK');
INSERT INTO "country_code" VALUES('Dominica',212,'DM','DMA');
INSERT INTO "country_code" VALUES('Dominican Republic',214,'DO','DOM');
INSERT INTO "country_code" VALUES('Algeria',12,'DZ','DZA');
INSERT INTO "country_code" VALUES('Ecuador',218,'EC','ECU');
INSERT INTO "country_code" VALUES('Estonia',233,'EE','EST');
INSERT INTO "country_code" VALUES('Egypt',818,'EG','EGY');
INSERT INTO "country_code" VALUES('Western Sahara',732,'EH','ESH');
INSERT INTO "country_code" VALUES('Eritrea',232,'ER','ERI');
INSERT INTO "country_code" VALUES('Spain',724,'ES','ESP');
INSERT INTO "country_code" VALUES('Ethiopia',231,'ET','ETH');
INSERT INTO "country_code" VALUES('Finland',246,'FI','FIN');
INSERT INTO "country_code" VALUES('Fiji',242,'FJ','FJI');
INSERT INTO "country_code" VALUES('Falkland Islands (Islas Malvinas)',238,'FK','FLK');
INSERT INTO "country_code" VALUES('Micronesia, Federated States of',583,'FM','FSM');
INSERT INTO "country_code" VALUES('Faeroe Islands',234,'FO','FRO');
INSERT INTO "country_code" VALUES('France',250,'FR','FRA');
INSERT INTO "country_code" VALUES('Gabon',266,'GA','GAB');
INSERT INTO "country_code" VALUES('United Kingdom',826,'GB','GBR');
INSERT INTO "country_code" VALUES('Grenada',308,'GD','GRD');
INSERT INTO "country_code" VALUES('Georgia',268,'GE','GEO');
INSERT INTO "country_code" VALUES('French Guiana',254,'GF','GUF');
INSERT INTO "country_code" VALUES('Ghana',288,'GH','GHA');
INSERT INTO "country_code" VALUES('Gibraltar',292,'GI','GIB');
INSERT INTO "country_code" VALUES('Greenland',304,'GL','GRL');
INSERT INTO "country_code" VALUES('Gambia',270,'GM','GMB');
INSERT INTO "country_code" VALUES('Guinea',324,'GN','GIN');
INSERT INTO "country_code" VALUES('Guadeloupe',312,'GP','GLP');
INSERT INTO "country_code" VALUES('Equatorial Guinea',226,'GQ','GNQ');
INSERT INTO "country_code" VALUES('Greece',300,'GR','GRC');
INSERT INTO "country_code" VALUES('Guatemala',320,'GT','GTM');
INSERT INTO "country_code" VALUES('Guam',316,'GU','GUM');
INSERT INTO "country_code" VALUES('Guinea-Bissau',624,'GW','GNB');
INSERT INTO "country_code" VALUES('Guyana',328,'GY','GUY');
INSERT INTO "country_code" VALUES('Hong Kong Special Administrative Region of China',344,'HK','HKG');
INSERT INTO "country_code" VALUES('Honduras',340,'HN','HND');
INSERT INTO "country_code" VALUES('Croatia',191,'HR','HRV');
INSERT INTO "country_code" VALUES('Haiti',332,'HT','HTI');
INSERT INTO "country_code" VALUES('Hungary',348,'HU','HUN');
INSERT INTO "country_code" VALUES('Indonesia',360,'ID','IDN');
INSERT INTO "country_code" VALUES('Ireland',372,'IE','IRL');
INSERT INTO "country_code" VALUES('Israel',376,'IL','ISR');
INSERT INTO "country_code" VALUES('India',356,'IN','IND');
INSERT INTO "country_code" VALUES('Iraq',368,'IQ','IRQ');
INSERT INTO "country_code" VALUES('Iran (Islamic Republic of)',364,'IR','IRN');
INSERT INTO "country_code" VALUES('Iceland',352,'IS','ISL');
INSERT INTO "country_code" VALUES('Italy',380,'IT','ITA');
INSERT INTO "country_code" VALUES('Jamaica',388,'JM','JAM');
INSERT INTO "country_code" VALUES('Jordan',400,'JO','JOR');
INSERT INTO "country_code" VALUES('Japan',392,'JP','JPN');
INSERT INTO "country_code" VALUES('Kenya',404,'KE','KEN');
INSERT INTO "country_code" VALUES('Kyrgyzstan',417,'KG','KGZ');
INSERT INTO "country_code" VALUES('Cambodia',116,'KH','KHM');
INSERT INTO "country_code" VALUES('Kiribati',296,'KI','KIR');
INSERT INTO "country_code" VALUES('Comoros Islands',174,'KM','COM');
INSERT INTO "country_code" VALUES('Saint Kitts and Nevis',659,'KN','KNA');
INSERT INTO "country_code" VALUES('Korea, Democratic People''s Republic of',408,'KP','PRK');
INSERT INTO "country_code" VALUES('Republic of Korea',410,'KR','KOR');
INSERT INTO "country_code" VALUES('Kuwait',414,'KW','KWT');
INSERT INTO "country_code" VALUES('Cayman Islands',136,'KY','CYM');
INSERT INTO "country_code" VALUES('Kazakhstan',398,'KZ','KAZ');
INSERT INTO "country_code" VALUES('Lao People''s Democratic Republic',418,'LA','LAO');
INSERT INTO "country_code" VALUES('Lebanon',422,'LB','LBN');
INSERT INTO "country_code" VALUES('Saint Lucia',662,'LC','LCA');
INSERT INTO "country_code" VALUES('Liechtenstein',438,'LI','LIE');
INSERT INTO "country_code" VALUES('Sri Lanka',144,'LK','LKA');
INSERT INTO "country_code" VALUES('Liberia',430,'LR','LBR');
INSERT INTO "country_code" VALUES('Lesotho',426,'LS','LSO');
INSERT INTO "country_code" VALUES('Lithuania',440,'LT','LTU');
INSERT INTO "country_code" VALUES('Luxembourg',442,'LU','LUX');
INSERT INTO "country_code" VALUES('Latvia',428,'LV','LVA');
INSERT INTO "country_code" VALUES('Libyan Arab Jamahiriya',434,'LY','LBY');
INSERT INTO "country_code" VALUES('Morocco',504,'MA','MAR');
INSERT INTO "country_code" VALUES('Monaco',492,'MC','MCO');
INSERT INTO "country_code" VALUES('Republic of Moldova',498,'MD','MDA');
INSERT INTO "country_code" VALUES('Madagascar',450,'MG','MDG');
INSERT INTO "country_code" VALUES('Marshall Islands',584,'MH','MHL');
INSERT INTO "country_code" VALUES('Macedonia, The former Yugoslav Republic of',807,'MK','MKD');
INSERT INTO "country_code" VALUES('Mali',466,'ML','MLI');
INSERT INTO "country_code" VALUES('Myanmar',104,'MM','MMR');
INSERT INTO "country_code" VALUES('Mongolia',496,'MN','MNG');
INSERT INTO "country_code" VALUES('Macao Special Administrative Region of China',446,'MO','MAC');
INSERT INTO "country_code" VALUES('Northern Mariana Islands',580,'MP','MNP');
INSERT INTO "country_code" VALUES('Martinique',474,'MQ','MTQ');
INSERT INTO "country_code" VALUES('Mauritania',478,'MR','MRT');
INSERT INTO "country_code" VALUES('Montserrat',500,'MS','MSR');
INSERT INTO "country_code" VALUES('Malta',470,'MT','MLT');
INSERT INTO "country_code" VALUES('Mauritius',480,'MU','MUS');
INSERT INTO "country_code" VALUES('Maldives',462,'MV','MDV');
INSERT INTO "country_code" VALUES('Malawi',454,'MW','MWI');
INSERT INTO "country_code" VALUES('Mexico',484,'MX','MEX');
INSERT INTO "country_code" VALUES('Malaysia',458,'MY','MYS');
INSERT INTO "country_code" VALUES('Mozambique',508,'MZ','MOZ');
INSERT INTO "country_code" VALUES('Namibia',516,'NA','NAM');
INSERT INTO "country_code" VALUES('New Caledonia',540,'NC','NCL');
INSERT INTO "country_code" VALUES('Niger',562,'NE','NER');
INSERT INTO "country_code" VALUES('Norfolk Island',574,'NF','NFK');
INSERT INTO "country_code" VALUES('Nigeria',566,'NG','NGA');
INSERT INTO "country_code" VALUES('Nicaragua',558,'NI','NIC');
INSERT INTO "country_code" VALUES('Netherlands',528,'NL','NLD');
INSERT INTO "country_code" VALUES('Norway',578,'NO','NOR');
INSERT INTO "country_code" VALUES('Nepal',524,'NP','NPL');
INSERT INTO "country_code" VALUES('Nauru',520,'NR','NRU');
INSERT INTO "country_code" VALUES('Niue',570,'NU','NIU');
INSERT INTO "country_code" VALUES('New Zealand',554,'NZ','NZL');
INSERT INTO "country_code" VALUES('Oman',512,'OM','OMN');
INSERT INTO "country_code" VALUES('Panama',591,'PA','PAN');
INSERT INTO "country_code" VALUES('Peru',604,'PE','PER');
INSERT INTO "country_code" VALUES('French Polynesia',258,'PF','PYF');
INSERT INTO "country_code" VALUES('Papua New Guinea',598,'PG','PNG');
INSERT INTO "country_code" VALUES('Philippines',608,'PH','PHL');
INSERT INTO "country_code" VALUES('Pakistan',586,'PK','PAK');
INSERT INTO "country_code" VALUES('Poland',616,'PL','POL');
INSERT INTO "country_code" VALUES('Saint Pierre and Miquelon',666,'PM','SPM');
INSERT INTO "country_code" VALUES('Pitcairn Islands',612,'PN','PCN');
INSERT INTO "country_code" VALUES('Puerto Rico',630,'PR','PRI');
INSERT INTO "country_code" VALUES('Occupied Palestinian Territory',275,'PS','PSE');
INSERT INTO "country_code" VALUES('Portugal',620,'PT','PRT');
INSERT INTO "country_code" VALUES('Palau',585,'PW','PLW');
INSERT INTO "country_code" VALUES('Paraguay',600,'PY','PRY');
INSERT INTO "country_code" VALUES('Qatar',634,'QA','QAT');
INSERT INTO "country_code" VALUES('Reunion',638,'RE','REU');
INSERT INTO "country_code" VALUES('Romania',642,'RO','ROM');
INSERT INTO "country_code" VALUES('Russian Federation',643,'RU','RUS');
INSERT INTO "country_code" VALUES('Rwanda',646,'RW','RWA');
INSERT INTO "country_code" VALUES('Saudi Arabia',682,'SA','SAU');
INSERT INTO "country_code" VALUES('Solomon Islands',90,'SB','SLB');
INSERT INTO "country_code" VALUES('Seychelles',690,'SC','SYC');
INSERT INTO "country_code" VALUES('Sudan',736,'SD','SDN');
INSERT INTO "country_code" VALUES('Sweden',752,'SE','SWE');
INSERT INTO "country_code" VALUES('Singapore',702,'SG','SGP');
INSERT INTO "country_code" VALUES('Saint Helena',654,'SH','SHN');
INSERT INTO "country_code" VALUES('Slovenia',705,'SI','SVN');
INSERT INTO "country_code" VALUES('Svalbard and Jan Mayen Islands',744,'SJ','SJM');
INSERT INTO "country_code" VALUES('Slovakia',703,'SK','SVK');
INSERT INTO "country_code" VALUES('Sierra Leone',694,'SL','SLE');
INSERT INTO "country_code" VALUES('San Marino',674,'SM','SMR');
INSERT INTO "country_code" VALUES('Senegal',686,'SN','SEN');
INSERT INTO "country_code" VALUES('Somalia',706,'SO','SOM');
INSERT INTO "country_code" VALUES('Suriname',740,'SR','SUR');
INSERT INTO "country_code" VALUES('Sao Tome and Principe',678,'ST','STP');
INSERT INTO "country_code" VALUES('El Salvador',222,'SV','SLV');
INSERT INTO "country_code" VALUES('Syrian Arab Republic',760,'SY','SYR');
INSERT INTO "country_code" VALUES('Swaziland',748,'SZ','SWZ');
INSERT INTO "country_code" VALUES('Turks and Caicos Islands',796,'TC','TCA');
INSERT INTO "country_code" VALUES('Chad',148,'TD','TCD');
INSERT INTO "country_code" VALUES('Togo',768,'TG','TGO');
INSERT INTO "country_code" VALUES('Thailand',764,'TH','THA');
INSERT INTO "country_code" VALUES('Tajikistan',762,'TJ','TJK');
INSERT INTO "country_code" VALUES('Tokelau',772,'TK','TKL');
INSERT INTO "country_code" VALUES('Turkmenistan',795,'TM','TKM');
INSERT INTO "country_code" VALUES('Tunisia',788,'TN','TUN');
INSERT INTO "country_code" VALUES('Tonga',776,'TO','TON');
INSERT INTO "country_code" VALUES('East Timor',626,'TP','TMP');
INSERT INTO "country_code" VALUES('Turkey',792,'TR','TUR');
INSERT INTO "country_code" VALUES('Trinidad and Tobago',780,'TT','TTO');
INSERT INTO "country_code" VALUES('Tuvalu',798,'TV','TUV');
INSERT INTO "country_code" VALUES('Taiwan Province of China',158,'TW','TWN');
INSERT INTO "country_code" VALUES('United Republic of Tanzania',834,'TZ','TZA');
INSERT INTO "country_code" VALUES('Ukraine',804,'UA','UKR');
INSERT INTO "country_code" VALUES('Uganda',800,'UG','UGA');
INSERT INTO "country_code" VALUES('United States',840,'US','USA');
INSERT INTO "country_code" VALUES('Uruguay',858,'UY','URY');
INSERT INTO "country_code" VALUES('Uzbekistan',860,'UZ','UZB');
INSERT INTO "country_code" VALUES('Holy See',336,'VA','VAT');
INSERT INTO "country_code" VALUES('Saint Vincent and the Grenadines',670,'VC','VCT');
INSERT INTO "country_code" VALUES('Venezuela',862,'VE','VEN');
INSERT INTO "country_code" VALUES('British Virgin Islands',92,'VG','VGB');
INSERT INTO "country_code" VALUES('United States Virgin Islands',850,'VI','VIR');
INSERT INTO "country_code" VALUES('Viet Nam',704,'VN','VNM');
INSERT INTO "country_code" VALUES('Vanuatu',548,'VU','VUT');
INSERT INTO "country_code" VALUES('Wallis and Futuna Islands',876,'WF','WLF');
INSERT INTO "country_code" VALUES('Samoa',882,'WS','WSM');
INSERT INTO "country_code" VALUES('Yemen',887,'YE','YEM');
INSERT INTO "country_code" VALUES('Mayotte',175,'YT','MYT');
INSERT INTO "country_code" VALUES('Yugoslavia',891,'YU','YUG');
INSERT INTO "country_code" VALUES('South Africa',710,'ZA','ZAF');
INSERT INTO "country_code" VALUES('Zambia',894,'ZM','ZMB');
INSERT INTO "country_code" VALUES('Zimbabwe',716,'ZW','ZWE');


---
--- data for table 'language_code'
---
INSERT INTO "language_code" VALUES('Abkhazian','AB','ABK','ABK');
INSERT INTO "language_code" VALUES('Afar','AA','AAR','AAR');
INSERT INTO "language_code" VALUES('Afrikaans','AF','AFR','AFR');
INSERT INTO "language_code" VALUES('Albanian','SQ','ALB','SQI');
INSERT INTO "language_code" VALUES('Amharic','AM','AMH','AMH');
INSERT INTO "language_code" VALUES('Arabic','AR','ARA','ARA');
INSERT INTO "language_code" VALUES('Armenian','HY','ARM','HYE');
INSERT INTO "language_code" VALUES('Assamese','AS','ASM','ASM');
INSERT INTO "language_code" VALUES('Avestan','AE','AVE','AVE');
INSERT INTO "language_code" VALUES('Aymara','AY','AYM','AYM');
INSERT INTO "language_code" VALUES('Azerbaijani','AZ','AZE','AZE');
INSERT INTO "language_code" VALUES('Bashkir','BA','BAK','BAK');
INSERT INTO "language_code" VALUES('Basque','EU','BAQ','EUS');
INSERT INTO "language_code" VALUES('Belarussian','BE','BEL','BEL');
INSERT INTO "language_code" VALUES('Bengali','BN','BEN','BEN');
INSERT INTO "language_code" VALUES('Bihari','BH','BIH','BIH');
INSERT INTO "language_code" VALUES('Bislama','BI','BIS','BIS');
INSERT INTO "language_code" VALUES('Bosnian','BS','BOS','BOS');
INSERT INTO "language_code" VALUES('Breton','BR','BRE','BRE');
INSERT INTO "language_code" VALUES('Bulgarian','BG','BUL','BUL');
INSERT INTO "language_code" VALUES('Burmese','MY','BUR','MYA');
INSERT INTO "language_code" VALUES('Catalan','CA','CAT','CAT');
INSERT INTO "language_code" VALUES('Chamorro','CH','CHA','CHA');
INSERT INTO "language_code" VALUES('Chechen','CE','CHE','CHE');
INSERT INTO "language_code" VALUES('Chichewa; Nyanja','NY','NYA','NYA');
INSERT INTO "language_code" VALUES('Chinese','ZH','CHI','ZHO');
INSERT INTO "language_code" VALUES('Church Slavic','CU','CHU','CHU');
INSERT INTO "language_code" VALUES('Chuvash','CV','CHV','CHV');
INSERT INTO "language_code" VALUES('Cornish','KW','COR','COR');
INSERT INTO "language_code" VALUES('Corsican','CO','COS','COS');
INSERT INTO "language_code" VALUES('Croatian','HR','SCR','HRV');
INSERT INTO "language_code" VALUES('Czech','CS','CZE','CES');
INSERT INTO "language_code" VALUES('Danish','DA','DAN','DAN');
INSERT INTO "language_code" VALUES('Dutch','NL','DUT','NLD');
INSERT INTO "language_code" VALUES('Dzongkha','DZ','DZO','DZO');
INSERT INTO "language_code" VALUES('English','EN','ENG','ENG');
INSERT INTO "language_code" VALUES('Esperanto','EO','EPO','EPO');
INSERT INTO "language_code" VALUES('Estonian','ET','EST','EST');
INSERT INTO "language_code" VALUES('Faeroese','FO','FAO','FAO');
INSERT INTO "language_code" VALUES('Fijian','FJ','FIJ','FIJ');
INSERT INTO "language_code" VALUES('Finnish','FI','FIN','FIN');
INSERT INTO "language_code" VALUES('French','FR','FRE','FRA');
INSERT INTO "language_code" VALUES('Frisian','FY','FRY','FRY');
INSERT INTO "language_code" VALUES('Gaelic (Scots)','GD','GLA','GLA');
INSERT INTO "language_code" VALUES('Gallegan','GL','GLG','GLG');
INSERT INTO "language_code" VALUES('Georgian','KA','GEO','KAT');
INSERT INTO "language_code" VALUES('German','DE','GER','DEU');
INSERT INTO "language_code" VALUES('Greek (Modern)','EL','GRE','ELL');
INSERT INTO "language_code" VALUES('Guarani','GN','GRN','GRN');
INSERT INTO "language_code" VALUES('Gujarati','GU','GUJ','GUJ');
INSERT INTO "language_code" VALUES('Hebrew','HE','HEB','HEB');
INSERT INTO "language_code" VALUES('Herero','HZ','HER','HER');
INSERT INTO "language_code" VALUES('Hindi','HI','HIN','HIN');
INSERT INTO "language_code" VALUES('Hiri Motu','HO','HMO','HMO');
INSERT INTO "language_code" VALUES('Hungarian','HU','HUN','HUN');
INSERT INTO "language_code" VALUES('Icelandic','IS','ICE','ISL');
INSERT INTO "language_code" VALUES('Indonesian','IN','IND','IND');
INSERT INTO "language_code" VALUES('Interlingua','IA','INA','INA');
INSERT INTO "language_code" VALUES('Interlingue','IE','ILE','ILE');
INSERT INTO "language_code" VALUES('Inuktitut','IU','IKU','IKU');
INSERT INTO "language_code" VALUES('Inupiaq [Inupiak]','IK','IPK','IPK');
INSERT INTO "language_code" VALUES('Irish','GA','GLE','GLE');
INSERT INTO "language_code" VALUES('Italian','IT','ITA','ITA');
INSERT INTO "language_code" VALUES('Japanese','JA','JPN','JPN');
INSERT INTO "language_code" VALUES('Javanese','JV','JAV','JAV');
INSERT INTO "language_code" VALUES('Kalaallisut [Greenlandic]','KL','KAL','KAL');
INSERT INTO "language_code" VALUES('Kannada','KN','KAN','KAN');
INSERT INTO "language_code" VALUES('Kashmiri','KS','KAS','KAS');
INSERT INTO "language_code" VALUES('Kazakh','KK','KAZ','KAZ');
INSERT INTO "language_code" VALUES('Khmer','KM','KHM','KHM');
INSERT INTO "language_code" VALUES('Kikuyu','KI','KIK','KIK');
INSERT INTO "language_code" VALUES('Kinyarwanda','RW','KIN','KIN');
INSERT INTO "language_code" VALUES('Kirghiz','KY','KIR','KIR');
INSERT INTO "language_code" VALUES('Komi','KV','KOM','KOM');
INSERT INTO "language_code" VALUES('Korean','KO','KOR','KOR');
INSERT INTO "language_code" VALUES('Kurdish','KU','KUR','KUR');
INSERT INTO "language_code" VALUES('Laothian','LO','LAO','LAO');
INSERT INTO "language_code" VALUES('Latin','LA','LAT','LAT');
INSERT INTO "language_code" VALUES('Latvian','LV','LAV','LAV');
INSERT INTO "language_code" VALUES('Letzeburgesch','LB','LTZ','LTZ');
INSERT INTO "language_code" VALUES('Lingala','LN','LIN','LIN');
INSERT INTO "language_code" VALUES('Lithuanian','LT','LIT','LIT');
INSERT INTO "language_code" VALUES('Macedonian','MK','MAC','MKD');
INSERT INTO "language_code" VALUES('Malagasy','MG','MLG','MLG');
INSERT INTO "language_code" VALUES('Malay','MS','MAY','MSA');
INSERT INTO "language_code" VALUES('Malayalam','ML','MAL','MAL');
INSERT INTO "language_code" VALUES('Maltese','MT','MLT','MLT');
INSERT INTO "language_code" VALUES('Manx','GV','GLV','GLV');
INSERT INTO "language_code" VALUES('Maori','MI','MAO','MRI');
INSERT INTO "language_code" VALUES('Marathi','MR','MAR','MAR');
INSERT INTO "language_code" VALUES('Marshall','MH','MAH','MAH');
INSERT INTO "language_code" VALUES('Moldavian','MO','MOL','MOL');
INSERT INTO "language_code" VALUES('Mongolian','MN','MON','MON');
INSERT INTO "language_code" VALUES('Nauru','NA','NAU','NAU');
INSERT INTO "language_code" VALUES('Navajo','NV','NAV','NAV');
INSERT INTO "language_code" VALUES('Ndebele, North','ND','NDE','NDE');
INSERT INTO "language_code" VALUES('Ndebele, South','NR','NBL','NBL');
INSERT INTO "language_code" VALUES('Ndonga','NG','NDO','NDO');
INSERT INTO "language_code" VALUES('Nepali','NE','NEP','NEP');
INSERT INTO "language_code" VALUES('Northern Sami','SE','SME','SME');
INSERT INTO "language_code" VALUES('Norwegian','NO','NOR','NOR');
INSERT INTO "language_code" VALUES('Norwegian Bokmai','NB','NOB','NOB');
INSERT INTO "language_code" VALUES('Norwegian Nynorsk','NN','NNO','NNO');
INSERT INTO "language_code" VALUES('Occitan (post 1500); Provencal','OC','OCI','OCI');
INSERT INTO "language_code" VALUES('Oriya','OR','ORI','ORI');
INSERT INTO "language_code" VALUES('Oromo','OM','ORM','ORM');
INSERT INTO "language_code" VALUES('Ossetian; Ossetic','OS','OSS','OSS');
INSERT INTO "language_code" VALUES('Pali','PI','PLI','PLI');
INSERT INTO "language_code" VALUES('Panjabi','PA','PAN','PAN');
INSERT INTO "language_code" VALUES('Persian','FA','PER','FAS');
INSERT INTO "language_code" VALUES('Polish','PL','POL','POL');
INSERT INTO "language_code" VALUES('Portuguese','PT','POR','POR');
INSERT INTO "language_code" VALUES('Pushto','PS','PUS','PUS');
INSERT INTO "language_code" VALUES('Quechua','QU','QUE','QUE');
INSERT INTO "language_code" VALUES('Rhaeto-Romance','RM','ROH','ROH');
INSERT INTO "language_code" VALUES('Romanian','RO','RUM','RON');
INSERT INTO "language_code" VALUES('Rundi','RN','RUN','RUN');
INSERT INTO "language_code" VALUES('Russian','RU','RUS','RUS');
INSERT INTO "language_code" VALUES('Samoan','SM','SMO','SMO');
INSERT INTO "language_code" VALUES('Sangro','SG','SAG','SAG');
INSERT INTO "language_code" VALUES('Sanskrit','SA','SAN','SAN');
INSERT INTO "language_code" VALUES('Sardinian','SC','SRD','SRD');
INSERT INTO "language_code" VALUES('Serbian','SR','SCC','SRP');
INSERT INTO "language_code" VALUES('Shona','SN','SNA','SNA');
INSERT INTO "language_code" VALUES('Sindhi','SD','SND','SND');
INSERT INTO "language_code" VALUES('Sinhalese [Singhalese]','SI','SNH','SIN');
INSERT INTO "language_code" VALUES('Slovak','SK','SLO','SLK');
INSERT INTO "language_code" VALUES('Slovenian','SL','SLV','SLV');
INSERT INTO "language_code" VALUES('Somali','SO','SOM','SOM');
INSERT INTO "language_code" VALUES('Sotho, Southern','ST','SOT','SOT');
INSERT INTO "language_code" VALUES('Spanish','ES','SPA','SPA');
INSERT INTO "language_code" VALUES('Sudanese','SU','SUN','SUN');
INSERT INTO "language_code" VALUES('Swahili','SW','SWA','SWA');
INSERT INTO "language_code" VALUES('Swati','SS','SSW','SSW');
INSERT INTO "language_code" VALUES('Swedish','SV','SWE','SWE');
INSERT INTO "language_code" VALUES('Tagalog','TL','TAG','TGL');
INSERT INTO "language_code" VALUES('Tahitian','TY','TAH','TAH');
INSERT INTO "language_code" VALUES('Tajik','TG','TAJ','TGK');
INSERT INTO "language_code" VALUES('Tamil','TA','TAM','TAM');
INSERT INTO "language_code" VALUES('Tatar','TT','TAT','TAT');
INSERT INTO "language_code" VALUES('Telugu','TE','TEL','TEL');
INSERT INTO "language_code" VALUES('Thai','TH','THA','THA');
INSERT INTO "language_code" VALUES('Tibetan','BO','TIB','BOD');
INSERT INTO "language_code" VALUES('Tsonga','TS','TSO','TSO');
INSERT INTO "language_code" VALUES('Tswana','TN','TSN','TSN');
INSERT INTO "language_code" VALUES('Turkish','TR','TUR','TUR');
INSERT INTO "language_code" VALUES('Turkmen','TK','TUK','TUK');
INSERT INTO "language_code" VALUES('Twi','TW','TWI','TWI');
INSERT INTO "language_code" VALUES('Uighur','UG','UIG','UIG');
INSERT INTO "language_code" VALUES('Ukrainian','UK','UKR','UKR');
INSERT INTO "language_code" VALUES('Urdu','UR','URD','URD');
INSERT INTO "language_code" VALUES('Uzbek','UZ','UZB','UZB');
INSERT INTO "language_code" VALUES('Vietnamese','VI','VIE','VIE');
INSERT INTO "language_code" VALUES('Volapuk','VO','VOL','VOL');
INSERT INTO "language_code" VALUES('Welsh','CY','WEL','CYM');
INSERT INTO "language_code" VALUES('Wolof','WO','WOL','WOL');
INSERT INTO "language_code" VALUES('Xhosa','XH','XHO','XHO');
INSERT INTO "language_code" VALUES('Yiddish','YI','YID','YID');
INSERT INTO "language_code" VALUES('Zhuang','ZA','ZHA','ZHA');
INSERT INTO "language_code" VALUES('Zulu','ZU','ZUL','ZUL');

---
--- data for table 'gncategory'
---
INSERT INTO "gncategory" ("Code", "Name", "NodeUsage") VALUES ('GNC', 'GridNode Commercial', 'Live');
INSERT INTO "gncategory" ("Code", "Name", "NodeUsage") VALUES ('GNS', 'GridNode Support', 'Live');
INSERT INTO "gncategory" ("Code", "Name", "NodeUsage") VALUES ('GNL', 'GridNode Lab', 'Test');
INSERT INTO "gncategory" ("Code", "Name", "NodeUsage") VALUES ('GNT', 'GridNode Trial', 'Trial');
INSERT INTO "gncategory" ("Code", "Name", "NodeUsage") VALUES ('GNO', 'GridNode Other', 'Live');
INSERT INTO "gncategory" ("Code", "Name", "NodeUsage") VALUES ('GNM', 'GridNode Master', 'Server');

---
--- data for table 'referencenum'
---
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('OneToMany',6,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_activity',38,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_application',20,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_formalparam',88,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_package',8,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_process',8,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_tool',22,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_transition',34,-1);
INSERT INTO "referencenum" ("RefName", "LastRefNum", "MaxRefNum") VALUES ('xpdl_transitionrestriction',5,-1);

COMMIT;