SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;


DELETE FROM "entitymetainfo" WHERE "EntityName" IN ('ProcedureDefFile','UserProcedure','JavaProcedure','ShellExecutable','SoapProcedure','ParamDef','ReturnDef');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','ProcedureDefFile','"procedure_definition_file"');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.UserProcedure','UserProcedure','"user_procedure"');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.JavaProcedure','JavaProcedure','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.ShellExecutable','ShellExecutable','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.SoapProcedure','SoapProcedure','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.ParamDef','ParamDef','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.pdip.base.userprocedure.model.ReturnDef','ReturnDef','');


--------- UserProcedure.
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%UserProcedure';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.uid',20,0,0,0,0,'0',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.pdip.base.userprocedure.model.UserProcedure','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.pdip.base.userprocedure.model.UserProcedure','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_name','NAME','"Name"','java.lang.String','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.name',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=30'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_description','DESCRIPTION','"Description"','java.lang.String','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.description',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_isSynchronous','IS_SYNCHRONOUS','"IsSynchronous"','java.lang.Boolean','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.isSynchronous',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'userProcedure.isSynchronous.yes=true'||chr(13)||chr(10)||'userProcedure.isSynchronous.no=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_procType','PROC_TYPE','"ProcType"','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procType',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'userProcedure.procType.executable=1'||chr(13)||chr(10)||'userProcedure.procType.java=2'||chr(13)||chr(10)||'userProcedure.procType.soap=3'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_procDefFile','PROC_DEF_FILE','"ProcDefFile"','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procDefFile',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=procedureDefFile.uid'||chr(13)||chr(10)||'foreign.display=procedureDefFile.name'||chr(13)||chr(10)||'foreign.cached=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_procDef','PROC_DEF','"ProcDef"','com.gridnode.pdip.base.userprocedure.model.ProcedureDef','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procDef',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=dynamic'||chr(13)||chr(10)||'dynamic.types=shellExecutable;javaProcedure;soapProcedure'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_procParamList','PROC_PARAM_LIST','"ProcParamList"','java.util.Vector','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procParamList',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=embedded'||chr(13)||chr(10)||'embedded.type=paramDef'||chr(13)||chr(10)||'collection=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_returnDataType','RETURN_DATA_TYPE','"ReturnDataType"','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.returnDataType',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'userProcedure.returnDataType.string=1'||chr(13)||chr(10)||'userProcedure.returnDataType.integer=2'||chr(13)||chr(10)||'userProcedure.returnDataType.long=3'||chr(13)||chr(10)||'userProcedure.returnDataType.double=4'||chr(13)||chr(10)||'userProcedure.returnDataType.boolean=5'||chr(13)||chr(10)||'userProcedure.returnDataType.date=6'||chr(13)||chr(10)||'userProcedure.returnDataType.object=7'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_defAction','DEF_ACTION','"DefAction"','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.defAction',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'userProcedure.defAction.continue=1'||chr(13)||chr(10)||'userProcedure.defAction.abort=2'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_defAlert','DEF_ALERT','"DefAlert"','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.defAlert',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=alert.uid'||chr(13)||chr(10)||'foreign.display=alert.description'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_procReturnList','PROC_RETURN_LIST','"ProcReturnList"','java.util.Vector','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.procReturnList',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=embedded'||chr(13)||chr(10)||'embedded.type=returnDef'||chr(13)||chr(10)||'collection=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_gridDocField','GRID_DOC_FIELD','"GridDocField"','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.UserProcedure','userProcedure.gridDocField',0,0,0,0,0,'0',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'gridDocument.custom1=77'||chr(13)||chr(10)||'gridDocument.custom2=78'||chr(13)||chr(10)||'gridDocument.custom3=79'||chr(13)||chr(10)||'gridDocument.custom4=80'||chr(13)||chr(10)||'gridDocument.custom5=81'||chr(13)||chr(10)||'gridDocument.custom6=82'||chr(13)||chr(10)||'gridDocument.custom7=83'||chr(13)||chr(10)||'gridDocument.custom8=84'||chr(13)||chr(10)||'gridDocument.custom9=85'||chr(13)||chr(10)||'gridDocument.custom10=86'||chr(13)||chr(10));

--------- ProcedureDefinition File.
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ProcedureDefFile';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.uid',20,0,0,0,0,'0',999,'displayable=false'||chr(13)||chr(10)||'editable=false','type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=range');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_canDelete','CAN_DELETE','"CanDelete"','java.lang.Boolean','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'candelete.enabled=true'||chr(13)||chr(10)||'candelete.disabled=false');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_name','NAME','"Name"','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.name',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_description','DESCRIPTION','"Description"','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.description',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_type','TYPE','"Type"','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.type',15,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'procedureDefFile.type.executable=1'||chr(13)||chr(10)||'procedureDefFile.type.java=2'||chr(13)||chr(10)||'procedureDefFile.type.soap=3'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_fileName','FILE_NAME','"FileName"','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.fileName',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=file'||chr(13)||chr(10)||'file.downloadable=false'||chr(13)||chr(10)||'file.pathKey=procedureDefFile.filePath'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_filePath','FILE_PATH','"FilePath"','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ProcedureDefFile','procedureDefFile.filePath',30,0,0,0,1,'0',1,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=file'||chr(13)||chr(10));

--------- JavaProcedure -- Note SQLName is empty as this are entities are not persistant. To Confirm regd cmdLineExpr (CMDLineExpression).
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%JavaProcedure';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_classPath','CLASS_PATH','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.classPath',80,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_className','CLASS_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.className',80,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_methodName','METHOD_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.methodName',80,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_jvmOptions','JVM_OPTIONS','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.jvmOptions',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_arguments','ARGUMENTS','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.arguments',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=150');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_isLocal','IS_LOCAL','','java.lang.Boolean','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.isLocal',0,0,0,0,0,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true','type=enum'||chr(13)||chr(10)||'javaProcedure.isLocal.true=true'||chr(13)||chr(10)||'javaProcedure.isLocal.false=false');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.JavaProcedure','javaProcedure.type',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'javaProcedure.type.executable=1'||chr(13)||chr(10)||'javaProcedure.type.java=2'||chr(13)||chr(10)||'javaProcedure.type.soap=3'||chr(13)||chr(10));

--------- ShellExecutable -- Note SQLName is empty as this are entities are not persistant
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ShellExecutable';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_arguments','ARGUMENTS','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ShellExecutable','shellExecutable.arguments',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=150');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ShellExecutable','shellExecutable.type',0,0,0,0,0,'',999,'displayable=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'shellExecutable.type.executable=1'||chr(13)||chr(10)||'shellExecutable.type.java=2'||chr(13)||chr(10)||'shellExecutable.type.soap=3'||chr(13)||chr(10));

--------- SoapProcedure -- Note SQLName is empty as this are entities are not persistant. To Confirm regd cmdLineExpr (CMDLineExpression).
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%SoapProcedure';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_methodName','METHOD_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.methodName',80,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.type',0,0,0,0,0,'','999','displayable=false'||chr(13)||chr(10)||'editable=false','type=enum'||chr(13)||chr(10)||'soapProcedure.type.executable=1'||chr(13)||chr(10)||'soapProcedure.type.java=2'||chr(13)||chr(10)||'soapProcedure.type.soap=3'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_username','USER_NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.userName',80,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_password','PASSWORD','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.SoapProcedure','soapProcedure.password',80,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
--------- ParamDef -- Note SQLName is empty as this are entities are not persistant
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ParamDef';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_name','NAME','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.name',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_description','DESCRIPTION','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.description',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_source','SOURCE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.source',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'paramDef.source.userDefined=1'||chr(13)||chr(10)||'paramDef.source.gdoc=2'||chr(13)||chr(10)||'paramDef.source.udoc=3'||chr(13)||chr(10)||'paramDef.source.attachments=4'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_type','TYPE','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.type',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'paramDef.type.string=1'||chr(13)||chr(10)||'paramDef.type.integer=2'||chr(13)||chr(10)||'paramDef.type.long=3'||chr(13)||chr(10)||'paramDef.type.double=4'||chr(13)||chr(10)||'paramDef.type.boolean=5'||chr(13)||chr(10)||'paramDef.type.date=6'||chr(13)||chr(10)||'paramDef.type.object=7'||chr(13)||chr(10)||'paramDef.type.datahandler=8'||chr(13)||chr(10)||'paramDef.type.datahandlerArray=9'||chr(13)||chr(10)||'paramDef.type.stringArray=10'||chr(13)||chr(10)||'paramDef.type.byteArray=11'||chr(13)||chr(10)||'paramDef.type.byteArrayArray=12'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_value','VALUE','','java.lang.Object','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.value',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_dateFormat','DATE_FORMAT','','java.lang.String','com.gridnode.pdip.base.userprocedure.model.ParamDef','paramDef.dateFormat',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'paramDef.dateFormat.format1=ddMMyyHHmmss'||chr(13)||chr(10)||'paramDef.dateFormat.format2=ddMMyyyyHHmmss'||chr(13)||chr(10)||'paramDef.dateFormat.format3=MMddyyHHmmss'||chr(13)||chr(10)||'paramDef.dateFormat.format4=MMddyyyyHHmmss'||chr(13)||chr(10)||'paramDef.dateFormat.format5=yyMMddHHmmss'||chr(13)||chr(10)||'paramDef.dateFormat.format6=yyyyMMddHHmmss'||chr(13)||chr(10)||'paramDef.dateFormat.format7=yyyyMMdd'||chr(13)||chr(10)||'paramDef.dateFormat.format8=yyMMdd'||chr(13)||chr(10)||'paramDef.dateFormat.format9=ddMMyyyy'||chr(13)||chr(10)||'paramDef.dateFormat.format10=ddMMyy'||chr(13)||chr(10)||'paramDef.dateFormat.format11=MMddyyyy'||chr(13)||chr(10)||'paramDef.dateFormat.format12=MMddyy');

--------- ReturnDef -- Note SQLName is empty as this are entities are not persistant
DELETE FROM "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ReturnDef';
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_operator','OPERATOR','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.operator',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'returnDef.operator.equal=0'||chr(13)||chr(10)||'returnDef.operator.less=1'||chr(13)||chr(10)||'returnDef.operator.lessOrEqual=2'||chr(13)||chr(10)||'returnDef.operator.greaterOrEqual=3'||chr(13)||chr(10)||'returnDef.operator.greater=4'||chr(13)||chr(10)||'returnDef.operator.notEqual=5'||chr(13)||chr(10)||'returnDef.operator.between=6'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_value','VALUE','','java.lang.Object','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.value',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=30');
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_action','ACTION','','java.lang.Integer','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.actionType',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'returnDef.actionType.continue=1'||chr(13)||chr(10)||'returnDef.actionType.abort=2'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES (DEFAULT,'_alert','ALERT','','java.lang.Long','com.gridnode.pdip.base.userprocedure.model.ReturnDef','returnDef.alert',30,0,0,0,1,'0',1,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=alert.uid'||chr(13)||chr(10)||'foreign.display=alert.description'||chr(13)||chr(10));
