USE appdb;

ALTER DATABASE appdb CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE country_code CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE entitymetainfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE fieldmetainfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE gncategory CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE language_code CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE referencenum CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
 
 
USE userdb;

ALTER DATABASE userdb CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE access_right CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE action CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE activation_record CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE active_track_record CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE alert CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE alert_action CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE alert_category CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE alert_list CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE alert_trigger CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE alert_type CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE attachment CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE attachmentregistry CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE biz_cert_mapping CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_bin_coll CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_bin_coll_act CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_biz_partner_role CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_biz_tran CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_biz_tran_activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_businessdocument CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_coll_activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_completion_state CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_documentation CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_documentenvelope CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_fork CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_join CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_multiparty_coll CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_proc_spec CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_proc_spec_entry CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_req_biz_activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_res_biz_activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_start CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bpss_transition CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE business_entity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE certificate CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE channel_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE comm_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE connection_status CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE coy_profile CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE data_bytedata CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE data_contextdata CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE data_stringdata CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE document_type CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE domain_identifier CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE feature CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE file_type CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE grid_document CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE gridform_definition CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE gridform_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE gridnode CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE gridtalk_license CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE gridtalk_mapping_rule CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_alarm CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_date CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_event CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_int CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_property CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_string CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_text CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ical_todo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE jms_router CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE license CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE mapping_file CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE mapping_rule CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE message_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE packaging_profile CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE partner CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE partner_function CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE partner_group CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE partner_type CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
# ALTER TABLE pf_trigger CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `trigger` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE port CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE procedure_definition_file CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE process_act CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE process_def CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE process_mapping CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE registry_connect_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

DROP INDEX registry_obj_idx ON registry_object_map;
ALTER TABLE registry_object_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE UNIQUE INDEX registry_obj_idx ON registry_object_map (RegistryObjectKey, RegistryObjectType, RegistryQueryUrl(250));

ALTER TABLE reminder_alert CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE resource_link CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE response_track_record CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE rfc CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE rn_profile CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE role CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE rtactivity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE rtprocess CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE rtprocessdoc CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE rtrestriction CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE search_query CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE security_profile CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE service_assignment CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE session_audit CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE shared_resource CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE subject_role CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE trans_activation_state CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE user_account CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE user_account_state CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE user_procedure CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE webservice CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE whitepage CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE workflow_activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE worklistuser CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE worklistvalue CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpath_mapping CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_activity CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_application CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_complexdatatype CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_datafield CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_externalpackage CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_formalparam CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_package CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_participant CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_participantlist CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_process CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_subflow CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE xpdl_tool CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_transition CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_transitionref CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_transitionrestriction CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE xpdl_typedeclaration CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
