# Change Log
# 16 Jul 2003 GT 2.2 I1 [Neo Sok Lay] Add fieldmetainfo for new column CanDelete in process_def table.

USE appdb;

DELETE FROM entitymetainfo WHERE EntityName = 'ProcessDef';
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.app.rnif.model.ProcessDef', 'ProcessDef','process_def');
DELETE FROM entitymetainfo WHERE EntityName = 'ProcessAct';
INSERT INTO entitymetainfo VALUES ('com.gridnode.pdip.app.rnif.model.ProcessAct', 'ProcessAct','process_act');

DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ProcessDef';
INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.pdip.app.rnif.model.ProcessDef' ,'processDef.uid', 0, 0, 0 , 1, 1, NULL, 999, 'displayable=false\r\neditable=false\r\nmandatory=false\r\n','type=uid\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_requestAct','REQUEST_ACT','','com.gridnode.pdip.app.rnif.model.ProcessAct','com.gridnode.pdip.app.rnif.model.ProcessDef','processDef.requestAct','0','0','0','1','1','','999','displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=embedded\r\nembedded.type=processAct');
INSERT INTO fieldmetainfo VALUES (NULL,'_responseAct','RESPONSE_ACT','','com.gridnode.pdip.app.rnif.model.ProcessAct','com.gridnode.pdip.app.rnif.model.ProcessDef','processDef.responseAct','0','0','0','1','1','','999','displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=dynamic\r\dynamic.types=processAct');
INSERT INTO fieldmetainfo VALUES (NULL,'_defName','DEF_NAME','DefName','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.defName', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\nmandatory=true\r\neditable.create=true\r\n','type=text\r\ntext.length.min=3\r\ntext.length.max=50');
INSERT INTO fieldmetainfo VALUES (NULL,'_actionTimeOut','ACTION_TIME_OUT','ActionTimeOut','java.lang.Integer','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.actionTimeOut', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=text\r\ntext.length.max=10\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_processType','PROCESS_TYPE','ProcessType','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.processType', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\neditable.create=true\r\nmandatory=true\r\n','type=enum\r\nprocessDef.processType.single=SingleActionProcess\r\nprocessDef.processType.double=TwoActionProcess');
INSERT INTO fieldmetainfo VALUES (NULL,'_RNIFVersion','RNIF_VERSION','RNIFVersion','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.rnifVersion', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=true\r\n','type=enum\r\nprocessDef.rnifVersion.rnif_1_1=RNIF1.1\r\nprocessDef.rnifVersion.rnif_2_0=RNIF2.0');
INSERT INTO fieldmetainfo VALUES (NULL,'_fromPartnerRoleClassCode','FROM_PARTNER_ROLE_CLASS_CODE','FromPartnerRoleClassCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.fromPartnerRoleClassCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_fromBizServiceCode','FROM_BIZ_SERVICE_CODE','FromBizServiceCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.fromBizServiceCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_fromPartnerClassCode','FROM_PARTNER_CLASS_CODE','FromPartnerClassCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.fromPartnerClassCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gToPartnerRoleClassCode','G_TO_PARTNER_ROLE_CLASS_CODE','GToPartnerRoleClassCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.toPartnerRoleClassCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gToBizServiceCode','G_TO_BIZ_SERVICE_CODE','GToBizServiceCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.toBizServiceCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gToPartnerClassCode','G_TO_PARTNER_CLASS_CODE','GToPartnerClassCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.toPartnerClassCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gProcessIndicatorCode','G_PROCESS_INDICATOR_CODE','GProcessIndicatorCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.processIndicatorCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_versionIdentifier','VERSION_IDENTIFIER','VersionIdentifier','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.versionIdentifier', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gUsageCode','G_USAGE_CODE','GUsageCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.usageCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');

INSERT INTO fieldmetainfo VALUES (NULL,'_requestDocThisDocIdentifier','REQUEST_DOC_THIS_DOC_IDENTIFIER','RequestDocThisDocIdentifier','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.requestDocThisDocIdentifier', 150,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=text\r\ntext.length.max=150\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_responseDocThisDocIdentifier','RESPONSE_DOC_THIS_DOC_IDENTIFIER','ResponseDocThisDocIdentifier','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.responseDocThisDocIdentifier', 150,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=text\r\ntext.length.max=150\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_responseDocRequestDocIdentifier','RESPONSE_DOC_REQUEST_DOC_IDENTIFIER','ResponseDocRequestDocIdentifier','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.responseDocRequestDocIdentifier', 150,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=text\r\ntext.length.max=150\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_userTrackingIdentifier','USER_TRACKING_IDENTIFIER','UserTrackingIdentifier','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.userTrackingIdentifier', 150,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=text\r\ntext.length.max=150\r\n');

INSERT INTO fieldmetainfo VALUES (NULL,'_isSynchronous','IS_SYNCHRONOUS','IsSynchronous','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.isSynchronous', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessDef.isSynchronous.true=true\r\nprocessDef.isSynchronous.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_canDelete','CAN_DELETE','CanDelete','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessDef', 'processDef.isSynchronous', 0,'0','0','1','1','', 999, 'displayable=false\r\neditable=false\r\nmandatory=false\r\n','type=enum\r\ngeneric.yes=true\r\ngeneric.false=false');



DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ProcessAct';
INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.pdip.app.rnif.model.ProcessAct' ,'processAct.uid', 0, 0, 0 , 1, 1, '', 999, 'displayable=false\r\neditable=false\r\nmandatory=false\r\n','type=uid\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_processDefUid','PROCESS_DEF_UID','ProcessDefUid','java.lang.Integer','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.processDefUid', 0,'0','0','1','1','', 999, 'displayable=false\r\neditable=false\r\nmandatory=false\r\n', '');
INSERT INTO fieldmetainfo VALUES (NULL,'_processDefAct','PROCESS_DEF_ACT','ProcessDefAct','java.lang.Integer','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.processDefAct', 0,'0','0','1','1','', 999, 'displayable=false\r\neditable=false\r\nmandatory=false\r\n', 'type=enum\r\nprocessAct.processDefAct.request=1\r\nprocessAct.processDefAct.response=2');
INSERT INTO fieldmetainfo VALUES (NULL,'_msgType','MSG_TYPE','MsgType','java.lang.Long','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.msgType', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=foreign\r\nforeign.key=mappingFile.uid\r\nforeign.display=mappingFile.name\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_retries','RETRIES','Retries','java.lang.Integer','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.retries', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=range\r\nrange.max=65535\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_timeToAcknowledge','TIME_TO_ACKNOWLEDGE','TimeToAcknowledge','java.lang.Integer','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.timeToAcknowledge', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=text\r\ntext.length.max=10\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_isAuthorizationRequired','IS_AUTHORIZATION_REQUIRED','IsAuthorizationRequired','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.isAuthorizationRequired', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.isAuthorizationRequired.true=true\r\nprocessAct.isAuthorizationRequired.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_isNonRepudiationRequired','IS_NON_REPUDIATION_REQUIRED','IsNonRepudiationRequired','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.isNonRepudiationRequired', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.isNonRepudiationRequired.true=true\r\nprocessAct.isNonRepudiationRequired.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_isSecureTransportRequired','IS_SECURE_TRANSPORT_REQUIRED','IsSecureTransportRequired','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.isSecureTransportRequired', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.isSecureTransportRequired.true=true\r\nprocessAct.isSecureTransportRequired.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_bizActivityIdentifier','BIZ_ACTIVITY_IDENTIFIER','BizActivityIdentifier','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.bizActivityIdentifier', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_gBizActionCode','G_BIZ_ACTION_CODE','GBizActionCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.bizActionCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=true\r\n','type=text\r\ntext.length.max=50\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_dictFile','DICT_FILE','DictFile','java.lang.Long','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.dictFile', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=foreign\r\nforeign.key=mappingFile.uid\r\nforeign.display=mappingFile.name\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_XMLSchema','XML_SCHEMA','XMLSchema','java.lang.Long','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.xmlSchema', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true','type=foreign\r\nforeign.key=mappingFile.uid\r\nforeign.display=mappingFile.name\r\n');
INSERT INTO fieldmetainfo VALUES (NULL,'_isCompressRequired','IS_COMPRESS_REQUIRED','IsCompressRequired','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.isCompressRequired', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.isCompressRequired.true=true\r\nprocessAct.isCompressRequired.false=false');

#INSERT INTO fieldmetainfo VALUES (NULL,'_gDigestAlgCode','G_DIGEST_ALG_CODE','GDigestAlgCode','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.digestAlgCode', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.digestAlgCode.sha=SHA1\r\nprocessAct.digestAlgCode.md5=MD5');
INSERT INTO fieldmetainfo VALUES (NULL,'_disableDTD','DISABLE_DTD','DisableDTD','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.disableDtd', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.disableDtd.true=true\r\nprocessAct.disableDtd.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_disableSchema','DISABLE_SCHEMA','DisableSchema','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.disableSchema', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.disableSchema.true=true\r\nprocessAct.disableSchema.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_disableEncryption','DISABLE_ENCRYPTION','DisableEncryption','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.disableEncryption', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.disableEncryption.true=true\r\nprocessAct.disableEncryption.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_disableSignature','DISABLE_SIGNATURE','DisableSignature','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.disableSignature', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.disableSignature.true=true\r\nprocessAct.disableSignature.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_validateAtSender','VALIDATE_AT_SENDER','ValidateAtSender','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.validateAtSender', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.validateAtSender.true=true\r\nprocessAct.validateAtSender.false=false');
INSERT INTO fieldmetainfo VALUES (NULL,'_onlyEncryptPayload','ONLY_ENCRYPT_PAYLOAD','OnlyEncryptPayload','java.lang.Boolean','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.onlyEncryptPayload', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.onlyEncryptPayload.true=true\r\nprocessAct.onlyEncryptPayload.false=false');

INSERT INTO fieldmetainfo VALUES (NULL,'_digestAlgorithm','DIGEST_ALGORITHM','DigestAlgorithm','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.digestAlgorithm', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\r\nmandatory=false\r\n','type=enum\r\nprocessAct.digestAlgorithm.sha=1.3.14.3.2.26\r\nprocessAct.digestAlgorithm.md5=1.2.840.113549.2.5');
#INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionAlgorithm','ENCRYPTION_ALGORITHM','EncryptionAlgorithm','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.encryptionAlgorithm', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=enum\r\nprocessAct.encryptionAlgorithm.RC5_ALG=RC5-0x10-32-16/CBC/PKCS5Padding\r\nprocessAct.encryptionAlgorithm.TDES_ALG=1.2.840.113549.3.7\r\nprocessAct.encryptionAlgorithm.RC2_ALG=1.2.840.113549.3.2');
INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionAlgorithm','ENCRYPTION_ALGORITHM','EncryptionAlgorithm','java.lang.String','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.encryptionAlgorithm', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=enum\r\nprocessAct.encryptionAlgorithm.TDES_ALG=1.2.840.113549.3.7\r\nprocessAct.encryptionAlgorithm.RC2_ALG=1.2.840.113549.3.2');
INSERT INTO fieldmetainfo VALUES (NULL,'_encryptionAlgorithmLength','ENCRYPTION_ALGORITHM_LENGTH','EncryptionAlgorithmLength','java.lang.Integer','com.gridnode.pdip.app.rnif.model.ProcessAct', 'processAct.encryptionAlgorithmLength', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=true\nmandatory=false\r\n','type=range\r\nrange.max=65535\r\n');




