/**
 * This software is the proprietary information of GridNode Pte Ltd.
 * Use is subjected to license terms.
 *
 * Copyright 2001-2003 (C) GridNode Pte Ltd. All Rights Reserved.
 *
 * File: ICommonHeaders.java
 *
 ****************************************************************************
 * Date           Author              Changes
 ****************************************************************************
 * Oct 26 2003    Jagadeesh           Created
 * Apr 19 2004    Guo Jianyu          Added COMPRESSION_TYPE
 * Nov 30 2005    Neo Sok Lay         Change be.uuid.url to be.uddi.url
 * Oct 07 2010    Tam Wei Xiang       #1897 - Added COMM_CONNECTION_TYPE
 */
package com.gridnode.pdip.framework.messaging;

/**
 * The ICommonHeaders Interface is the root interface for all
 * Message common headers. It defines the common headers keys,
 * used while Sending or Reciving a Message.
 *
 *
 * @author Jagadeesh
 * @since 2.3
 *
 */
public interface ICommonHeaders
{

  public static final String HEADER_CATEGORY =
    IHeaderCategory.CATEGORY_COMMON_HEADERS;

  /***  The below are sub category within CommonHeaders ******/

  //Category for Header Info.
  public static final String CATEGORY_HEADER_INFO = "header.info";

  //Category for Message Info.
  public static final String CATEGORY_MESSAGE_INFO = "message.info";

  //Category for PayLoad Info.
  public static final String CATEGORY_PAYLOAD_INFO = "payload.info";

  //Category for Sender Info.
  public static final String CATEGORY_SENDER_INFO = "sender.info";

  //Category for Recipient Info.
  public static final String CATEGORY_RECIPIENT_INFO = "recipient.info";

  //Category for Comm Info.
  public static final String CATEGORY_COMM_INFO = "comm.info";

  //Category for Security Info.
  public static final String CATEGORY_SECURITY_INFO = "security.info";
  
  //Category for Audit Trail Info
  public static final String CATEGORY_AUDIT_TRAIL_INFO = "onlineTracking.info";
  
  //Header Key for Version of this Message (ex: "020000" corresponds to backward compatible message.)
  public static final String VERSION = CATEGORY_HEADER_INFO + ".version";

  //Header Key for Message Event_ID,(as every message has a respective ack message id)
  public static final String MSG_EVENT_ID = CATEGORY_MESSAGE_INFO + ".event.id";

  //Header Key for Message Event_SUB_ID.
  public static final String MSG_EVENT_SUB_ID =
    CATEGORY_MESSAGE_INFO + ".event.sub.id";

  //Header key for Message Transaction Id (generated by Business Logic )
  public static final String MSG_TRANSACTION_ID =
    CATEGORY_MESSAGE_INFO + ".transaction.id";

  //Header Key for Message ProcessId (value assigned by Business Logic)
  public static final String MSG_PROCESS_ID =
    CATEGORY_MESSAGE_INFO + ".process.id";

  //Header key for <<MESSAGE>> PayLoad Type, (ex: Rosettanet Payload)
  public static final String PAYLOAD_TYPE =
    CATEGORY_PAYLOAD_INFO + ".payload.type";

  //Header key for identifying PayLoad Group.
  public static final String PAYLOAD_GROUP =
    CATEGORY_PAYLOAD_INFO + ".payload.group";
  
  

  public static final String PAYLOAD_ID = CATEGORY_PAYLOAD_INFO + ".payload.id";

  public static final String PAYLOAD_IS_ZIP = CATEGORY_PAYLOAD_INFO + ".is.zip";

        public static final String  PAYLOAD_IS_SPLIT = CATEGORY_PAYLOAD_INFO + ".is.split";

        public static final String PAYLOAD_BLK_SPLIT_SIZE = CATEGORY_PAYLOAD_INFO + ".blk.split.size";

        public static final String PAYLOAD_BLK_SPLIT_THRESHOLD = CATEGORY_PAYLOAD_INFO + ".blk.split.threshold";

  public static final String SENDER_ID = CATEGORY_SENDER_INFO + ".sender.id";

  public static final String SENDER_BE_ID =
    CATEGORY_SENDER_INFO + ".sender.be.id";

  public static final String SENDER_BE_GNID =
    CATEGORY_SENDER_INFO + ".sender.be.gnid";

  public static final String SENDER_BE_DUNS =
    CATEGORY_SENDER_INFO + ".sender.be.duns";

  public static final String SENDER_BE_UDDI_URL =
    CATEGORY_SENDER_INFO + ".sender.be.uddi.url";

  public static final String SENDER_BE_UUID =
    CATEGORY_SENDER_INFO + ".sender.be.uuid";

  public static final String RECIPENT_BE_ID =
    CATEGORY_RECIPIENT_INFO + ".recipient.be.id";

  public static final String RECIPENT_BE_GNID =
    CATEGORY_RECIPIENT_INFO + ".recipient.be.gnid";

  public static final String RECIPENT_BE_DUNS =
    CATEGORY_RECIPIENT_INFO + ".recipient.be.duns";

  public static final String RECIPENT_BE_UDDI_URL =
    CATEGORY_RECIPIENT_INFO + ".recipient.be.uddi.url";

  public static final String RECIPENT_BE_UUID =
    CATEGORY_RECIPIENT_INFO + ".recipient.be.uuid";

  public static final String COMM_CHANNEL =
    CATEGORY_COMM_INFO + ".comm.channel";

  public static final String COMM_PROTOCOL_TYPE =
    CATEGORY_COMM_INFO + ".comm.protocol.type";

  public static final String COMM_ENDPOINT_URL =
    CATEGORY_COMM_INFO + ".comm.endpoint.url";

  //TWX #1897 20100930 Indicate the type of the incoming connection. For web services, or the
  //future IB FTP support, the connection type is "direct".
  public static final String COMM_CONNECTION_TYPE = 
    CATEGORY_COMM_INFO + ".comm.connection.type";
  
  public static final String ENCRYPT_TYPE =
    CATEGORY_SECURITY_INFO + ".encrypt.type";

  public static final String ENCRYPT_LEVEL =
    CATEGORY_SECURITY_INFO + ".encrypt.level";

  public static final String ENCRYPT_CERT_ISSUER_NAME =
    CATEGORY_SECURITY_INFO + ".encrypt.cert.issuer.name";

  public static final String ENCRYPT_CERT_SERIAL_NUM =
    CATEGORY_SECURITY_INFO + ".encrypt.cert.serial.num";

  public static final String SIGN_TYPE = CATEGORY_SECURITY_INFO + ".sign.type";

  public static final String SIGN_DIGEST_TYPE =
    CATEGORY_SECURITY_INFO + ".sign.digest.algorithm";

  public static final String SIGN_CERT_ISSUER_NAME =
    CATEGORY_SECURITY_INFO + ".sign.cert.issuer.name";

  public static final String SIGN_CERT_SERIAL_NUM =
    CATEGORY_SECURITY_INFO + ".sign.cert.serial.num";

  public static final String COMM_GNCI = CATEGORY_COMM_INFO + ".comm.gnci";

  public static final String COMPRESSION_TYPE =
    CATEGORY_SECURITY_INFO + ".compression.type";

  public static final String IS_SMIME =
    CATEGORY_SECURITY_INFO + ".isSMIME";

  public static final String SMIME_ACTION_SEQUENCE =
    CATEGORY_SECURITY_INFO + ".smime.action.sequence";
  
  public static final String TRACING_ID = 
    CATEGORY_AUDIT_TRAIL_INFO +".tracing.id";
}
