SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;

DELETE from "entitymetainfo" WHERE "EntityName" IN ('GnCategory','GridNode','ConnectionStatus');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.gridnode.model.GnCategory','GnCategory','"gncategory"');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.gridnode.model.GridNode','GridNode','"gridnode"');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.gridnode.model.ConnectionStatus','ConnectionStatus','"connection_status"');

---------- GnCategory
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%GnCategory';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_name','CATEGORY_NAME','"Name"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GnCategory','gnCategory.name',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_code','CATEGORY_CODE','"Code"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GnCategory','gnCategory.code',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_nodeUsage','NODE_USAGE','"NodeUsage"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GnCategory','gnCategory.nodeUsage',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text');

---------- GridNode
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%gridnode.model.GridNode';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.uid',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_id','ID','"ID"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.id',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_name','NAME','"Name"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.name',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_category','CATEGORY','"Category"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.category',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=gnCategory.code'||chr(13)||chr(10)||'foreign.display=gnCategory.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_state','STATE','"State"','java.lang.Short','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.state',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'gridNode.state.me=0'||chr(13)||chr(10)||'gridNode.state.deleted=1'||chr(13)||chr(10)||'gridNode.state.active=2'||chr(13)||chr(10)||'gridNode.state.inactive=3'||chr(13)||chr(10)||'gridNode.state.gm=4'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_activationReason','ACTIVATION_REASON','"ActivationReason"','java.lang.String','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.activationReason',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtCreated','DT_CREATED','"DTCreated"','java.sql.Timestamp','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.dtCreated',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtReqActivate','DT_REQ_ACTIVATE','"DTReqActivate"','java.sql.Timestamp','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.dtReqActivate',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtActivated','DT_ACTIVATED','"DTActivated"','java.sql.Timestamp','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.dtActivated',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtDeactivated','DT_DEACTIVATED','"DTDeactivated"','java.sql.Timestamp','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.dtDeactivated',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_coyProfileUID','COY_PROFILE_UID','"CoyProfileUID"','java.lang.Long','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.coyProfileUid',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=coyProfile.uid'||chr(13)||chr(10)||'foreign.display=coyProfile.coyName'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10)||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_version','VERSION','"Version"','java.lang.Double','com.gridnode.gtas.server.gridnode.model.GridNode','gridNode.version',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10));

---------- ConnectionStatus
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ConnectionStatus';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.uid',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_nodeID','GRIDNODE_ID','"NodeID"','java.lang.String','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.gridnodeId',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=gridnode.id'||chr(13)||chr(10)||'foreign.display=gridnode.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_statusFlag','STATUS_FLAG','"StatusFlag"','java.lang.Short','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.statusFlag',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'connectionStatus.statusFlag.online=0'||chr(13)||chr(10)||'connectionStatus.statusFlag.offline=1'||chr(13)||chr(10)||'connectionStatus.statusFlag.connecting=2'||chr(13)||chr(10)||'connectionStatus.statusFlag.reconnecting=3'||chr(13)||chr(10)||'connectionStatus.statusFlag.disconnectng=4'||chr(13)||chr(10)||'connectionStatus.statusFlag.expired=5'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtLastOnline','DT_LAST_ONLINE','"DTLastOnline"','java.sql.Timestamp','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.dtLastOnline',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtLastOffline','DT_LAST_OFFLINE','"DTLastOffline"','java.sql.Timestamp','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.dtLastOffline',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_reconnectionKey','RECONNECTION_KEY','"ReconnectionKey"','java.lang.String','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.reconnectionKey',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),NULL);
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_connectedServerNode','CONNECTED_SERVER_NODE','"ConnectedServerNode"','java.lang.String','com.gridnode.gtas.server.gridnode.model.ConnectionStatus','connectionStatus.connectedServerNode',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=gridnode.id'||chr(13)||chr(10)||'foreign.display=gridnode.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));

