# 05 Dec 2003 GT 2.1 [Neo Sok Lay] Increase column size for ProcessInstanceId,PIPInstanceIdentifier,ProcessTransactionId,ProcessActionId in RNProfile
#                                  and ProcessInstance

USE appdb;

	DELETE FROM entitymetainfo WHERE EntityName = 'RNProfile';
	INSERT INTO entitymetainfo VALUES ('com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile','rn_profile');

	DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%RNProfile';
	INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','UID','java.lang.Long','com.gridnode.gtas.server.rnif.model.RNProfile' ,'RNProfile.uid', 0, 0, 0 , 1, 1, NULL, 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_documentUid','DOCUMENT_UID','DocumentUid','java.lang.Long','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.documentUid', 0,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_processInstanceId','PROCESS_INSTANCE_ID','ProcessInstanceId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.processInstanceId', 200,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_processOriginatorId','PROCESS_ORIGINATOR_ID','ProcessOriginatorId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.processOriginatorId', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_processResponderId','PROCESS_RESPONDER_ID','ProcessResponderId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.processResponderId', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_processDefName','PROCESS_DEF_NAME','ProcessDefName','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.processDefName', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_receiverDomain','RECEIVER_DOMAIN','ReceiverDomain','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.receiverDomain', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_receiverGlobalBusIdentifier','RECEIVER_GLOBAL_BUS_IDENTIFIER','ReceiverGlobalBusIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.receiverGlobalBusIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_receiverLocationId','RECEIVER_LOCATION_ID','ReceiverLocationId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.receiverLocationId', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_senderDomain','SENDER_DOMAIN','SenderDomain','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.senderDomain', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_senderGlobalBusIdentifier','SENDER_GLOBAL_BUS_IDENTIFIER','SenderGlobalBusIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.senderGlobalBusIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_senderLocationId','SENDER_LOCATION_ID','SenderLocationId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.senderLocationId', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_deliveryMessageTrackingId','DELIVERY_MESSAGE_TRACKING_ID','DeliveryMessageTrackingId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.deliveryMessageTrackingId', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_busActivityIdentifier','BUS_ACTIVITY_IDENTIFIER','BusActivityIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.busActivityIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_fromGlobalPartnerRoleClassCode','FROM_GLOBAL_PARTNER_ROLE_CLASS_CODE','FromGlobalPartnerRoleClassCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.fromGlobalPartnerRoleClassCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_fromGlobalBusServiceCode','FROM_GLOBAL_BUS_SERVICE_CODE','FromGlobalBusServiceCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.fromGlobalBusServiceCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_inReplyToGlobalBusActionCode','IN_REPLY_TO_GLOBAL_BUS_ACTION_CODE','InReplyToGlobalBusActionCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.inReplyToGlobalBusActionCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_inReplyToMessageStandard','IN_REPLY_TO_MESSAGE_STANDARD','InReplyToMessageStandard','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.inReplyToMessageStandard', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_inReplyToStandardVersion','IN_REPLY_TO_STANDARD_VERSION','InReplyToStandardVersion','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.inReplyToStandardVersion', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_inReplyToVersionIdentifier','IN_REPLY_TO_VERSION_IDENTIFIER','InReplyToVersionIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.inReplyToVersionIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_serviceMessageTrackingId','SERVICE_MESSAGE_TRACKING_ID','ServiceMessageTrackingId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.serviceMessageTrackingId', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_actionIdentityGlobalBusActionCode','ACTION_IDENTITY_GLOBAL_BUS_ACTION_CODE','ActionIdentityGlobalBusActionCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.actionIdentityGlobalBusActionCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_actionIdentityToMessageStandard','ACTION_IDENTITY_TO_MESSAGE_STANDARD','ActionIdentityToMessageStandard','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.actionIdentityToMessageStandard', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_actionIdentityStandardVersion','ACTION_IDENTITY_STANDARD_VERSION','ActionIdentityStandardVersion','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.actionIdentityStandardVersion', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_actionIdentityVersionIdentifier','ACTION_IDENTITY_VERSION_IDENTIFIER','ActionIdentityVersionIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.actionIdentityVersionIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_signalIdentityGlobalBusSignalCode','SIGNAL_IDENTITY_GLOBAL_BUS_SIGNAL_CODE','SignalIdentityGlobalBusSignalCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.signalIdentityGlobalBusSignalCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_signalIdentityVersionIdentifier','SIGNAL_IDENTITY_VERSION_IDENTIFIER','SignalIdentityVersionIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.signalIdentityVersionIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_toGlobalPartnerRoleClassCode','TO_GLOBAL_PARTNER_ROLE_CLASS_CODE','ToGlobalPartnerRoleClassCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.toGlobalPartnerRoleClassCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_toGlobalBusServiceCode','TO_GLOBAL_BUS_SERVICE_CODE','ToGlobalBusServiceCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.toGlobalBusServiceCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_globalUsageCode','GLOBAL_USAGE_CODE','GlobalUsageCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.globalUsageCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_partnerGlobalBusIdentifier','PARTNER_GLOBAL_BUS_IDENTIFIER','PartnerGlobalBusIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.partnerGlobalBusIdentifier', 0,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_PIPGlobalProcessCode','PIP_GLOBAL_PROCESS_CODE','PIPGlobalProcessCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.PIPGlobalProcessCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_PIPInstanceIdentifier','PIP_INSTANCE_IDENTIFIER','PIPInstanceIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.PIPInstanceIdentifier', 200,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_PIPVersionIdentifier','PIP_VERSION_IDENTIFIER','PIPVersionIdentifier','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.PIPVersionIdentifier', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_processTransactionId','PROCESS_TRANSACTION_ID','ProcessTransactionId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.processTransactionId', 200,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_processActionId','PROCESS_ACTION_ID','ProcessActionId','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.processActionId', 240,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_fromGlobalPartnerClassCode','FROM_GLOBAL_PARTNER_CLASS_CODE','FromGlobalPartnerClassCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.fromGlobalPartnerClassCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_toGlobalPartnerClassCode','TO_GLOBAL_PARTNER_CLASS_CODE','ToGlobalPartnerClassCode','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.toGlobalPartnerClassCode', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_numberOfAttas','NUMBER_OF_ATTAS','NumberOfAttas','java.lang.Integer','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.numberOfAttas', 0,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_isSignalDoc','IS_SIGNAL_DOC','IsSignalDoc','java.lang.boolean','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.isSignalDoc', 0,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_isRequestMsg','IS_REQUEST_MSG','IsRequestMsg','java.lang.boolean','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.IsRequestMsg', 0,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_uniqueValue','UNIQUE_VALUE','UniqueValue','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.uniqueValue', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_attemptCount','ATTEMPT_COUNT','AttemptCount','java.lang.Integer','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.attemptCount', 0,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_msgDigest','MSG_DIGEST','MsgDigest','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.msgDigest', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_RNIFVersion','RNIF_VERSION','RNIFVersion','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.RNIFVersion', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_inResponseToActionID','IN_RESPONSE_TO_ACTION_ID','InResponseToActionID','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.inResponseToActionID', 80,'0','0','1','1','', 999, NULL, NULL);
	INSERT INTO fieldmetainfo VALUES (NULL,'_userTrackingID','USER_TRACKING_ID','UserTrackingID','java.lang.String','com.gridnode.gtas.server.rnif.model.RNProfile', 'RNProfile.userTrackingID', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=80\r\n');
	
	
  DELETE FROM entitymetainfo WHERE EntityName = 'ProcessInstance';
	INSERT INTO entitymetainfo VALUES ('com.gridnode.gtas.server.rnif.model.ProcessInstance', 'ProcessInstance', NULL);

	DELETE FROM fieldmetainfo WHERE EntityObjectName LIKE '%ProcessInstance';
	INSERT INTO fieldmetainfo VALUES (NULL,'_uId','UID','','java.lang.Long','com.gridnode.gtas.server.rnif.model.ProcessInstance' ,'processInstance.uid', 0, 0, 0 , 1, 1, NULL, 999, 'displayable=false\r\neditable=false\r\nmandatory=false\r\n','type=uid\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_processInstanceId','PROCESS_INSTANCE_ID','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.processInstanceId', 200,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=200\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_userTrackingID','USER_TRACKING_ID','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.userTrackingId', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=80\r\n');	
	INSERT INTO fieldmetainfo VALUES (NULL,'_partner','PARTNER','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.partner', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=80\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_state','STATE','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.state', 50,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n',
	     'type=enum\r\nprocessInstance.state.open=0\r\nprocessInstance.state.running=1\r\nprocessInstance.state.completed=2\r\nprocessInstance.state.suspended=3\r\nprocessInstance.state.abnormallyCompleted=4\r\nprocessInstance.state.abnormallyTerminated=5\r\nprocessInstance.state.abnormallyAborted=6\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_startTime','START_TIME','','java.util.Date','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.startTime', 0,'0','0','1','1','', 999, 'displayable=true\r\nmandatory=false\r\neditable=false','type=datetime\r\ndatetime.adjustment=gts');
	INSERT INTO fieldmetainfo VALUES (NULL,'_endTime','END_TIME','','java.util.Date','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.endTime', 0,'0','0','1','1','', 999,'displayable=true\r\nmandatory=false\r\neditable=false','type=datetime\r\ndatetime.adjustment=gts');
	INSERT INTO fieldmetainfo VALUES (NULL,'_retryNum','RETRY_NUM','','java.lang.Integer','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.retryNum', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\nmandatory=false\r\n','type=text\r\ntext.length.max=10\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_isFailed','IS_FAILED','','java.lang.Boolean','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.isFailed', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\nmandatory=false\r\n','type=enum\r\nprocessInstance.isFailed.true=true\r\nprocessInstance.isFailed.false=false');
	INSERT INTO fieldmetainfo VALUES (NULL,'_failReason','FAIL_REASON','','java.lang.Integer','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.failReason', 0,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\r\nmandatory=false\r\n',
	     'type=enum\r\nprocessInstance.failReason.retryOut=1\r\nprocessInstance.failReason.actOut=2\r\nprocessInstance.failReason.validateEx=3\r\nprocessInstance.failReason.receiveEx=4\r\nprocessInstance.failReason.userCancel=5\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_detailReason','DETAIL_REASON','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.detailReason', 250,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=250\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_assocDocs','ASSOC_DOCS','','java.util.Collection','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.assocDocs', 0,'0','0','1','1','', 999, 'displayable=true\r\nmandatory=false\r\neditable=false',
	     'type=foreign\r\nforeign.key=gridDocument.uid\r\nforeign.display=gridDocument.udocFilename\r\nforeign.cached=false\r\ncollection=true\r\ncollection.element=java.lang.Long');
	INSERT INTO fieldmetainfo VALUES (NULL,'_processDefName','PROCESS_DEF_NAME','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.processDefName', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=80\r\n');
	INSERT INTO fieldmetainfo VALUES (NULL,'_roleType','ROLE_TYPE','','java.lang.String','com.gridnode.gtas.server.rnif.model.ProcessInstance', 'processInstance.roleType', 80,'0','0','1','1','', 999, 'displayable=true\r\neditable=false\nmandatory=false\r\n','type=text\r\ntext.length.max=80\r\n');
