SET client_encoding = 'UTF8';
SET check_function_bodies = false;
SET client_min_messages = warning;
SET search_path = appdb;

------------ Entity meta info
DELETE from "entitymetainfo" WHERE "EntityName" IN ('SearchGridNodeCriteria','SearchGridNodeQuery','SearchedGridNode','ActivationRecord','GridNodeActivation');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','SearchGridNodeCriteria','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.activation.model.SearchGridNodeQuery','SearchGridNodeQuery','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.activation.model.SearchedGridNode','SearchedGridNode','');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.activation.model.ActivationRecord','ActivationRecord','"activation_record"');
INSERT INTO "entitymetainfo" VALUES ('com.gridnode.gtas.server.activation.model.GridNodeActivation','GridNodeActivation','');

---------- SearchGridNodeCriteria
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%SearchGridNodeCriteria';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_criteriaType','CRITERIA','','java.lang.Short','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.criteriaType',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'searchGridNodeCriteria.criteriaType.none=1'||chr(13)||chr(10)||'searchGridNodeCriteria.criteriaType.gridNode=2'||chr(13)||chr(10)||'searchGridNodeCriteria.criteriaType.whitePage=3'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_matchType','MATCH','','java.lang.Short','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.matchType',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'searchGridNodeCriteria.matchType.all=1'||chr(13)||chr(10)||'searchGridNodeCriteria.matchType.any=2'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gridnodeID','GRIDNODE_ID','','java.lang.Integer','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.gridNodeId',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10)||'range.min=1'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gridnodeName','GRIDNODE_NAME','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.gridNodeName',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_category','CATEGORY','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.category',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=gnCategory.code'||chr(13)||chr(10)||'foreign.display=gnCategory.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_busDesc','BUSINESS_DESC','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.businessDesc',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dUNS','DUNS','CONTACT_PERSON','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.duns',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=20'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_contactPerson','CONTACT_PERSON','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.contactPerson',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=80'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_email','EMAIL','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.email',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_tel','TEL','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.tel',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=16'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_fax','FAX','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.fax',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=16'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_website','WEBSITE','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.website',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10)||'text.length.max=255'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_country','COUNTRY','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','searchGridNodeCriteria.country',0,0,0,1,1,'',999,'displayable=true'||chr(13)||chr(10)||'editable=true'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10)||'editable.display=false'||chr(13)||chr(10),'type=foreign'||chr(13)||chr(10)||'foreign.key=countryCode.alpha3Code'||chr(13)||chr(10)||'foreign.display=countryCode.name'||chr(13)||chr(10)||'foreign.cached=false'||chr(13)||chr(10));

---------- SearchGridNodeQuery
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%SearchGridNodeQuery';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_searchID','SEARCH_ID','','java.lang.Long','com.gridnode.gtas.server.activation.model.SearchGridNodeQuery','searchGridNodeQuery.searchId',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtSubmitted','DT_SUBMITTED','','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.SearchGridNodeQuery','searchGridNodeQuery.dtSubmitted',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtResponded','DT_RESPONDED','','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.SearchGridNodeQuery','searchGridNodeQuery.dtResponded',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_criteria','CRITERIA','','com.gridnode.gtas.server.activation.model.SearchGridNodeCriteria','com.gridnode.gtas.server.activation.model.SearchGridNodeQuery','searchGridNodeQuery.criteria',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=embedded'||chr(13)||chr(10)||'embedded.type=searchGridNodeCriteria');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_results','RESULTS','','java.util.Collection','com.gridnode.gtas.server.activation.model.SearchGridNodeQuery','searchGridNodeQuery.results',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'collection=true'||chr(13)||chr(10)||'type=embedded'||chr(13)||chr(10)||'embedded.type=searchedGridNode'||chr(13)||chr(10));

---------- SearchedGridNode
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%SearchedGridNode';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gridnodeID','GRIDNODE_ID','','java.lang.Integer','com.gridnode.gtas.server.activation.model.SearchedGridNode','searchedGridNode.gridNodeId',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=range'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gridnodeName','GRIDNODE_NAME','','java.lang.String','com.gridnode.gtas.server.activation.model.SearchedGridNode','searchedGridNode.gridNodeName',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_state','STATE','','java.lang.Short','com.gridnode.gtas.server.activation.model.SearchedGridNode','searchedGridNode.state',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'searchedGridNode.state.me=0'||chr(13)||chr(10)||'searchedGridNode.state.active=1'||chr(13)||chr(10)||'searchedGridNode.state.inactive=2'||chr(13)||chr(10)||'searchedGridNode.state.pending=3'||chr(13)||chr(10));

---------- ActivationRecord
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%ActivationRecord';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_uId','UID','"UID"','java.lang.Long','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.uid',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=uid'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_currentType','CURRENT_TYPE','"CurrentType"','java.lang.Short','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.currentType',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'activationRecord.currentType.activation=0'||chr(13)||chr(10)||'activationRecord.currentType.deactivation=1'||chr(13)||chr(10)||'activationRecord.currentType.approval=2'||chr(13)||chr(10)||'activationRecord.currentType.denial=3'||chr(13)||chr(10)||'activationRecord.currentType.abortion=4'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_actDirection','ACT_DIRECTION','"ActDirection"','java.lang.Short','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.actDirection',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'activationRecord.actDirection.incoming=1'||chr(13)||chr(10)||'activationRecord.actDirection.outgoing=2'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_deactDirection','DEACT_DIRECTION','"DeactDirection"','java.lang.Short','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.deactDirection',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'activationRecord.deactDirection.incoming=1'||chr(13)||chr(10)||'activationRecord.deactDirection.outgoing=2'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gridnodeID','GRIDNODE_ID','"GridNodeID"','java.lang.Integer','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.gridNodeId',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=range'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_gridnodeName','GRIDNODE_NAME','"GridNodeName"','java.lang.String','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.gridNodeName',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtRequested','DT_REQUESTED','"DTRequested"','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.dtRequested',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtApproved','DT_APPROVED','"DTApproved"','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.dtApproved',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtAborted','DT_ABORTED','"DTAborted"','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.dtAborted',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtDenied','DT_DENIED','"DTDenied"','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.dtDenied',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_dtDeactivated','DT_DEACTIVATED','"DTDeactivated"','java.sql.Timestamp','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.dtDeactivated',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=datetime'||chr(13)||chr(10)||'datetime.date=true'||chr(13)||chr(10)||'datetime.time=true'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_isLatest','IS_LATEST','"IsLatest"','java.lang.Boolean','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.isLatest',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_activationDetails','ACTIVATION_DETAILS','"ActivationDetails"','com.gridnode.gtas.server.activation.model.GridNodeActivation','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.activationDetails',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=embedded'||chr(13)||chr(10)||'embedded.type=gridNodeActivation');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_transCompleted','TRANS_COMPLETED','"TransCompleted"','java.lang.Boolean','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.isTransCompleted',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=enum'||chr(13)||chr(10)||'generic.yes=true'||chr(13)||chr(10)||'generic.no=false');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_transFailReason','TRANS_FAIL_REASON','"TransFailReason"','java.lang.String','com.gridnode.gtas.server.activation.model.ActivationRecord','activationRecord.transFailReason',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'type=text');

---------- GridNodeActivation
DELETE from "fieldmetainfo" WHERE "EntityObjectName" LIKE '%GridNodeActivation';
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_activateReason','ACTIVATE_REASON','','java.lang.String','com.gridnode.gtas.server.activation.model.GridNodeActivation','gridNodeActivation.activateReason',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'type=text'||chr(13)||chr(10));
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_requestDetails','REQUEST_DETAILS','','com.gridnode.gtas.server.enterprise.sync.models.SyncGridNode','com.gridnode.gtas.server.activation.model.GridNodeActivation','gridNodeActivation.requestDetails',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_approveDetails','APPROVE_DETAILS','','com.gridnode.gtas.server.enterprise.sync.models.SyncGridNode','com.gridnode.gtas.server.activation.model.GridNodeActivation','gridNodeActivation.approveDetails',0,0,0,1,1,NULL,999,'displayable=false'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'mandatory=false'||chr(13)||chr(10),'');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_requestorBeList','REQUESTOR_BE_LIST','','java.util.Collection','com.gridnode.gtas.server.activation.model.GridNodeActivation','gridNodeActivation.requestorBeList',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.create=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'collection=true'||chr(13)||chr(10)||'type=foreign'||chr(13)||chr(10)||'foreign.key=businessEntity.uid'||chr(13)||chr(10)||'foreign.display=businessEntity.id'||chr(13)||chr(10)||'foreign.additionalDisplay=enterpriseId'||chr(13)||chr(10)||'foreign.cached=true');
INSERT INTO "fieldmetainfo" VALUES(DEFAULT,'_approverBeList','APPROVER_BE_LIST','','java.util.Collection','com.gridnode.gtas.server.activation.model.GridNodeActivation','gridNodeActivation.approverBeList',0,0,0,1,1,NULL,999,'displayable=true'||chr(13)||chr(10)||'editable=false'||chr(13)||chr(10)||'editable.update=true'||chr(13)||chr(10)||'mandatory=true'||chr(13)||chr(10),'collection=true'||chr(13)||chr(10)||'type=foreign'||chr(13)||chr(10)||'foreign.key=businessEntity.uid'||chr(13)||chr(10)||'foreign.display=businessEntity.id'||chr(13)||chr(10)||'foreign.additionalDisplay=enterpriseId'||chr(13)||chr(10)||'foreign.cached=true');
